Fluid structure interaction suite: PDEs::DistributedLagrange< dim, spacedim, LacType > Class Template Reference
PDEs::DistributedLagrange< dim, spacedim, LacType > Class Template Reference
#include <distributed_lagrange.h>
Public Member Functions
DistributedLagrange ()
void run ()
Public Member Functions inherited from ParameterAcceptor
ParameterAcceptor (const std::string &section_name="")
virtual ~ParameterAcceptor () override
virtual void declare_parameters (ParameterHandler &prm)
virtual void parse_parameters (ParameterHandler &prm)
std::string get_section_name () const
std::vector< std::string > get_section_path () const
void add_parameter (const std::string &entry, ParameterType &parameter, const std::string &documentation="", ParameterHandler &prm_=prm, const Patterns::PatternBase &pattern=*Patterns::Tools::Convert< ParameterType >::to_pattern())
void enter_subsection (const std::string &subsection)
void leave_subsection ()
void enter_my_subsection (ParameterHandler &prm)
void leave_my_subsection (ParameterHandler &prm)
void serialize (Archive &ar, const unsigned int version)
void subscribe (std::atomic< bool > *const validity, const std::string &identifier="") const
void unsubscribe (std::atomic< bool > *const validity, const std::string &identifier="") const
unsigned int n_subscriptions () const
void list_subscribers (StreamType &stream) const
void list_subscribers () const
void subscribe (std::atomic< bool > *const validity, const std::string &identifier="") const
void unsubscribe (std::atomic< bool > *const validity, const std::string &identifier="") const
unsigned int n_subscriptions () const
void list_subscribers (StreamType &stream) const
void list_subscribers () const
Public Member Functions inherited from Subscriptor
Subscriptor ()
Subscriptor (const Subscriptor &)
Subscriptor (Subscriptor &&) noexcept
virtual ~Subscriptor ()
Subscriptor & operator= (const Subscriptor &)
Subscriptor & operator= (Subscriptor &&) noexcept
void serialize (Archive &ar, const unsigned int version)
void subscribe (std::atomic< bool > *const validity, const std::string &identifier="") const
void unsubscribe (std::atomic< bool > *const validity, const std::string &identifier="") const
unsigned int n_subscriptions () const
void list_subscribers (StreamType &stream) const
void list_subscribers () const
void subscribe (std::atomic< bool > *const validity, const std::string &identifier="") const
void unsubscribe (std::atomic< bool > *const validity, const std::string &identifier="") const
unsigned int n_subscriptions () const
void list_subscribers (StreamType &stream) const
void list_subscribers () const
Private Member Functions
void generate_grids ()
void setup_system ()
void assemble_system ()
void solve ()
void output_results (const unsigned int cycle)
Private Attributes
bool use_direct_solver
PDEs::LinearProblem< spacedim, spacedim, LacType > space
GridTools::Cache< spacedim, spacedim > space_cache
PDEs::LinearProblem< dim, spacedim, LacType > embedded
GridTools::Cache< dim, spacedim > embedded_cache
ParsedTools::NonMatchingCoupling< dim, spacedim > coupling
LacType::SparsityPattern coupling_sparsity
LacType::SparseMatrix coupling_matrix
ParsedLAC::InverseOperator mass_solver
Additional Inherited Members
Static Public Member Functions inherited from ParameterAcceptor
static void initialize (const std::string &filename="", const std::string &output_filename="", const ParameterHandler::OutputStyle output_style_for_output_filename=ParameterHandler::Short, ParameterHandler &prm=ParameterAcceptor::prm, const ParameterHandler::OutputStyle output_style_for_filename=ParameterHandler::DefaultStyle)
static void initialize (std::istream &input_stream, ParameterHandler &prm=ParameterAcceptor::prm)
static void clear ()
static void parse_all_parameters (ParameterHandler &prm=ParameterAcceptor::prm)
static void declare_all_parameters (ParameterHandler &prm=ParameterAcceptor::prm)
static ::ExceptionBase & ExcInUse (int arg1, std::string arg2, std::string arg3)
static ::ExceptionBase & ExcNoSubscriber (std::string arg1, std::string arg2)
Static Public Member Functions inherited from Subscriptor
static ::ExceptionBase & ExcInUse (int arg1, std::string arg2, std::string arg3)
static ::ExceptionBase & ExcNoSubscriber (std::string arg1, std::string arg2)
Public Attributes inherited from ParameterAcceptor
boost::signals2::signal< void()> declare_parameters_call_back
boost::signals2::signal< void()> parse_parameters_call_back
Static Public Attributes inherited from ParameterAcceptor
static ParameterHandler prm
Protected Attributes inherited from ParameterAcceptor
const std::string section_name
std::vector< std::string > subsections
Detailed Description
template<int dim, int spacedim = dim, typename LacType = LAC::LAdealii>
class PDEs::DistributedLagrange< dim, spacedim, LacType >
Definition at line 53 of file distributed_lagrange.h.
Constructor & Destructor Documentation
DistributedLagrange()
template<int dim, int spacedim, typename LacType > PDEs::DistributedLagrange< dim, spacedim, LacType >::DistributedLagrange
Definition at line 35 of file distributed_lagrange.cc.
References triangulation.
Member Function Documentation
run()
template<int dim, int spacedim, typename LacType > void PDEs::DistributedLagrange< dim, spacedim, LacType >::run
Definition at line 266 of file distributed_lagrange.cc.
References deallog, LogStream::depth_console(), Utilities::int_to_string(), LogStream::pop(), and LogStream::push().
generate_grids()
template<int dim, int spacedim, typename LacType > void PDEs::DistributedLagrange< dim, spacedim, LacType >::generate_grids private
Definition at line 49 of file distributed_lagrange.cc.
setup_system()
template<int dim, int spacedim, typename LacType > void PDEs::DistributedLagrange< dim, spacedim, LacType >::setup_system private
Definition at line 69 of file distributed_lagrange.cc.
assemble_system()
template<int dim, int spacedim, typename LacType > void PDEs::DistributedLagrange< dim, spacedim, LacType >::assemble_system private
Definition at line 88 of file distributed_lagrange.cc.
References VectorOperation::add, cell_matrix(), copy(), VectorOperation::insert, VectorTools::interpolate(), MeshWorker::ScratchData< dim, spacedim >::reinit(), update_gradients, update_JxW_values, update_quadrature_points, and update_values.
solve()
template<int dim, int spacedim, typename LacType > void PDEs::DistributedLagrange< dim, spacedim, LacType >::solve private
Definition at line 210 of file distributed_lagrange.cc.
References identity_operator(), lambda, and transpose_operator().
output_results()
template<int dim, int spacedim, typename LacType > void PDEs::DistributedLagrange< dim, spacedim, LacType >::output_results (const unsigned int cycle) private
Definition at line 255 of file distributed_lagrange.cc.
Member Data Documentation
use_direct_solver
template<int dim, int spacedim = dim, typename LacType = LAC::LAdealii> bool PDEs::DistributedLagrange< dim, spacedim, LacType >::use_direct_solver private
Definition at line 77 of file distributed_lagrange.h.
space
template<int dim, int spacedim = dim, typename LacType = LAC::LAdealii> PDEs::LinearProblem<spacedim, spacedim, LacType> PDEs::DistributedLagrange< dim, spacedim, LacType >::space private
Definition at line 79 of file distributed_lagrange.h.
space_cache
template<int dim, int spacedim = dim, typename LacType = LAC::LAdealii> GridTools::Cache<spacedim, spacedim> PDEs::DistributedLagrange< dim, spacedim, LacType >::space_cache private
Definition at line 80 of file distributed_lagrange.h.
embedded
template<int dim, int spacedim = dim, typename LacType = LAC::LAdealii> PDEs::LinearProblem<dim, spacedim, LacType> PDEs::DistributedLagrange< dim, spacedim, LacType >::embedded private
Definition at line 82 of file distributed_lagrange.h.
embedded_cache
template<int dim, int spacedim = dim, typename LacType = LAC::LAdealii> GridTools::Cache<dim, spacedim> PDEs::DistributedLagrange< dim, spacedim, LacType >::embedded_cache private
Definition at line 83 of file distributed_lagrange.h.
coupling
template<int dim, int spacedim = dim, typename LacType = LAC::LAdealii> ParsedTools::NonMatchingCoupling<dim, spacedim> PDEs::DistributedLagrange< dim, spacedim, LacType >::coupling private
Definition at line 85 of file distributed_lagrange.h.
coupling_sparsity
template<int dim, int spacedim = dim, typename LacType = LAC::LAdealii> LacType::SparsityPattern PDEs::DistributedLagrange< dim, spacedim, LacType >::coupling_sparsity private
Definition at line 87 of file distributed_lagrange.h.
coupling_matrix
template<int dim, int spacedim = dim, typename LacType = LAC::LAdealii> LacType::SparseMatrix PDEs::DistributedLagrange< dim, spacedim, LacType >::coupling_matrix private
Definition at line 88 of file distributed_lagrange.h.
mass_solver
template<int dim, int spacedim = dim, typename LacType = LAC::LAdealii> ParsedLAC::InverseOperator PDEs::DistributedLagrange< dim, spacedim, LacType >::mass_solver private
Definition at line 90 of file distributed_lagrange.h.
The documentation for this class was generated from the following files:
include/pdes/distributed_lagrange.h
source/pdes/distributed_lagrange.cc