Fluid structure interaction suite: ParsedTools::SymbolicFunction< dim > Class Template Reference
ParsedTools::SymbolicFunction< dim > Class Template Reference
A wrapper for the Functions::SymbolicFunction class.
#include <symbolic_function.h>
Public Member Functions
SymbolicFunction (const std::string &section_name="", const std::string &expression="", const std::string &function_description="Function expression")
Build a SymbolicFunction based on the ParameterAcceptor class.
operator Functions::SymbolicFunction< dim > & ()
Act as an actual Functions::SymbolicFunction, so that we can pass this object to any function that expects a Functions::Function object.
Functions::SymbolicFunction< dim > & operator() ()
Act as an actual Functions::SymbolicFunction.
Public Member Functions inherited from ParameterAcceptor
ParameterAcceptor (const std::string &section_name="")
virtual ~ParameterAcceptor () override
virtual void declare_parameters (ParameterHandler &prm)
virtual void parse_parameters (ParameterHandler &prm)
std::string get_section_name () const
std::vector< std::string > get_section_path () const
void add_parameter (const std::string &entry, ParameterType &parameter, const std::string &documentation="", ParameterHandler &prm_=prm, const Patterns::PatternBase &pattern=*Patterns::Tools::Convert< ParameterType >::to_pattern())
void enter_subsection (const std::string &subsection)
void leave_subsection ()
void enter_my_subsection (ParameterHandler &prm)
void leave_my_subsection (ParameterHandler &prm)
void serialize (Archive &ar, const unsigned int version)
void subscribe (std::atomic< bool > *const validity, const std::string &identifier="") const
void unsubscribe (std::atomic< bool > *const validity, const std::string &identifier="") const
unsigned int n_subscriptions () const
void list_subscribers (StreamType &stream) const
void list_subscribers () const
void subscribe (std::atomic< bool > *const validity, const std::string &identifier="") const
void unsubscribe (std::atomic< bool > *const validity, const std::string &identifier="") const
unsigned int n_subscriptions () const
void list_subscribers (StreamType &stream) const
void list_subscribers () const
Public Member Functions inherited from Subscriptor
Subscriptor ()
Subscriptor (const Subscriptor &)
Subscriptor (Subscriptor &&) noexcept
virtual ~Subscriptor ()
Subscriptor & operator= (const Subscriptor &)
Subscriptor & operator= (Subscriptor &&) noexcept
void serialize (Archive &ar, const unsigned int version)
void subscribe (std::atomic< bool > *const validity, const std::string &identifier="") const
void unsubscribe (std::atomic< bool > *const validity, const std::string &identifier="") const
unsigned int n_subscriptions () const
void list_subscribers (StreamType &stream) const
void list_subscribers () const
void subscribe (std::atomic< bool > *const validity, const std::string &identifier="") const
void unsubscribe (std::atomic< bool > *const validity, const std::string &identifier="") const
unsigned int n_subscriptions () const
void list_subscribers (StreamType &stream) const
void list_subscribers () const
Private Attributes
std::unique_ptr< Functions::SymbolicFunction< dim > > symbolic_function
The actual Functions::SymbolicFunction object.
const unsigned int n_components
The number of components of the function.
Additional Inherited Members
Static Public Member Functions inherited from ParameterAcceptor
static void initialize (const std::string &filename="", const std::string &output_filename="", const ParameterHandler::OutputStyle output_style_for_output_filename=ParameterHandler::Short, ParameterHandler &prm=ParameterAcceptor::prm, const ParameterHandler::OutputStyle output_style_for_filename=ParameterHandler::DefaultStyle)
static void initialize (std::istream &input_stream, ParameterHandler &prm=ParameterAcceptor::prm)
static void clear ()
static void parse_all_parameters (ParameterHandler &prm=ParameterAcceptor::prm)
static void declare_all_parameters (ParameterHandler &prm=ParameterAcceptor::prm)
static ::ExceptionBase & ExcInUse (int arg1, std::string arg2, std::string arg3)
static ::ExceptionBase & ExcNoSubscriber (std::string arg1, std::string arg2)
Static Public Member Functions inherited from Subscriptor
static ::ExceptionBase & ExcInUse (int arg1, std::string arg2, std::string arg3)
static ::ExceptionBase & ExcNoSubscriber (std::string arg1, std::string arg2)
Public Attributes inherited from ParameterAcceptor
boost::signals2::signal< void()> declare_parameters_call_back
boost::signals2::signal< void()> parse_parameters_call_back
Static Public Attributes inherited from ParameterAcceptor
static ParameterHandler prm
Protected Attributes inherited from ParameterAcceptor
const std::string section_name
std::vector< std::string > subsections
Detailed Description
template<int dim>
class ParsedTools::SymbolicFunction< dim >
A wrapper for the Functions::SymbolicFunction class.
Definition at line 165 of file symbolic_function.h.
Constructor & Destructor Documentation
SymbolicFunction()
template<int dim> ParsedTools::SymbolicFunction< dim >::SymbolicFunction (const std::string & section_name = "", const std::string & expression = "", const std::string & function_description = "Function expression")
Build a SymbolicFunction based on the ParameterAcceptor class.
An example usage of this class is the following:
ParsedTools::SymbolicFunction<dim> my_function("Rhs
function","2*x+y"); auto value = my_function().value(some_point);
The above snippet of code will delcare the ParameterAcceptor::prm ParameterHandler with the following entries:
subsection RHS function
  set Function expression = "2*x+y"
end
Definition at line 26 of file symbolic_function.cc.
References ParameterHandler::add_action(), ParameterAcceptor::add_parameter(), AssertThrow, ParameterAcceptor::enter_my_subsection(), ExcMessage(), ParameterAcceptor::leave_my_subsection(), ParsedTools::SymbolicFunction< dim >::n_components, ParameterAcceptor::prm, and ParsedTools::SymbolicFunction< dim >::symbolic_function.
Member Function Documentation
operator Functions::SymbolicFunction< dim > &()
template<int dim> ParsedTools::SymbolicFunction< dim >::operator Functions::SymbolicFunction< dim > & () inline
Act as an actual Functions::SymbolicFunction, so that we can pass this object to any function that expects a Functions::Function object.
Definition at line 197 of file symbolic_function.h.
References ParsedTools::SymbolicFunction< dim >::symbolic_function.
operator()()
template<int dim> Functions::SymbolicFunction<dim>& ParsedTools::SymbolicFunction< dim >::operator() () inline
Act as an actual Functions::SymbolicFunction.
Definition at line 206 of file symbolic_function.h.
References ParsedTools::SymbolicFunction< dim >::symbolic_function.
Member Data Documentation
symbolic_function
template<int dim> std::unique_ptr<Functions::SymbolicFunction<dim> > ParsedTools::SymbolicFunction< dim >::symbolic_function private
The actual Functions::SymbolicFunction object.
Definition at line 215 of file symbolic_function.h.
Referenced by ParsedTools::SymbolicFunction< dim >::operator Functions::SymbolicFunction< dim > &(), ParsedTools::SymbolicFunction< dim >::operator()(), and ParsedTools::SymbolicFunction< dim >::SymbolicFunction().
n_components
template<int dim> const unsigned int ParsedTools::SymbolicFunction< dim >::n_components private
The number of components of the function.
This number is constructed from the expression given at construction time. If you reinitialize the function, make sure you use the same number of components, or an exception will be thrown.
Definition at line 223 of file symbolic_function.h.
Referenced by ParsedTools::SymbolicFunction< dim >::SymbolicFunction().
The documentation for this class was generated from the following files:
include/parsed_tools/symbolic_function.h
source/symbolic_function.cc