Fluid structure interaction suite: PDEs::MPI::Stokes< dim > Class Template Reference
PDEs::MPI::Stokes< dim > Class Template Reference
Solve the Stokes problem, in parallel.
#include <stokes.h>
Public Types
using ScratchData = typename LinearProblem< dim >::ScratchData
using CopyData = typename LinearProblem< dim >::CopyData
Public Types inherited from PDEs::MPI::LinearProblem< dim >
using CopyData = MeshWorker::CopyData< 1, 1, 1 >
Default CopyData object, used in the WorkStream class.
using ScratchData = MeshWorker::ScratchData< dim, dim >
Default ScratchData object, used in the workstream class.
Public Member Functions
Stokes ()
Constructor.
virtual ~Stokes ()=default
Destroy the Stokes object.
Public Member Functions inherited from PDEs::MPI::LinearProblem< dim >
LinearProblem (const std::string &component_names="u", const std::string &problem_name="")
Constructor.
virtual ~LinearProblem ()=default
Virtual destructor.
virtual void run ()
Main entry point of the problem.
Public Member Functions inherited from ParameterAcceptor
ParameterAcceptor (const std::string &section_name="")
virtual ~ParameterAcceptor () override
virtual void declare_parameters (ParameterHandler &prm)
virtual void parse_parameters (ParameterHandler &prm)
std::string get_section_name () const
std::vector< std::string > get_section_path () const
void add_parameter (const std::string &entry, ParameterType &parameter, const std::string &documentation="", ParameterHandler &prm_=prm, const Patterns::PatternBase &pattern=*Patterns::Tools::Convert< ParameterType >::to_pattern())
void enter_subsection (const std::string &subsection)
void leave_subsection ()
void enter_my_subsection (ParameterHandler &prm)
void leave_my_subsection (ParameterHandler &prm)
void serialize (Archive &ar, const unsigned int version)
void subscribe (std::atomic< bool > *const validity, const std::string &identifier="") const
void unsubscribe (std::atomic< bool > *const validity, const std::string &identifier="") const
unsigned int n_subscriptions () const
void list_subscribers (StreamType &stream) const
void list_subscribers () const
void subscribe (std::atomic< bool > *const validity, const std::string &identifier="") const
void unsubscribe (std::atomic< bool > *const validity, const std::string &identifier="") const
unsigned int n_subscriptions () const
void list_subscribers (StreamType &stream) const
void list_subscribers () const
Public Member Functions inherited from Subscriptor
Subscriptor ()
Subscriptor (const Subscriptor &)
Subscriptor (Subscriptor &&) noexcept
virtual ~Subscriptor ()
Subscriptor & operator= (const Subscriptor &)
Subscriptor & operator= (Subscriptor &&) noexcept
void serialize (Archive &ar, const unsigned int version)
void subscribe (std::atomic< bool > *const validity, const std::string &identifier="") const
void unsubscribe (std::atomic< bool > *const validity, const std::string &identifier="") const
unsigned int n_subscriptions () const
void list_subscribers (StreamType &stream) const
void list_subscribers () const
void subscribe (std::atomic< bool > *const validity, const std::string &identifier="") const
void unsubscribe (std::atomic< bool > *const validity, const std::string &identifier="") const
unsigned int n_subscriptions () const
void list_subscribers (StreamType &stream) const
void list_subscribers () const
Protected Member Functions
virtual void assemble_system_one_cell (const typename DoFHandler< dim >::active_cell_iterator &cell, ScratchData &scratch, CopyData &copy) override
Explicitly assemble the Stokes problem on a single cell.
virtual void solve () override
Make sure we initialize the right type of linear solver.
Protected Member Functions inherited from PDEs::MPI::LinearProblem< dim >
virtual void assemble_system_one_cell (const typename DoFHandler< dim, dim >::active_cell_iterator &cell, ScratchData &scratch, CopyData &copy)
Assemble the local system matrix on cell, using scratch for FEValues and other expensive scratch objects, and store the result in the copy object.
virtual void copy_one_cell (const CopyData &copy)
Distribute the data that has been assembled by assemble_system_on_cell() to the global matrix and rhs.
virtual void estimate (Vector< float > &error_per_cell) const
Perform a posteriori error estimation, and store the results in the error_per_cell vector.
void mark (const Vector< float > &error_per_cell)
According to the chosen strategy, mark some cells for refinement, possibily using the error_per_cell vector.
void refine ()
Refine the grid.
virtual void setup_system ()
Initial setup: distribute degrees of freedom, make all vectors and matrices of the right size, initialize functions and pointers.
virtual void assemble_system ()
Actually loop over cells, and assemble the global system.
virtual void output_results (const unsigned cycle) const
Output the solution and the grid in a format that can be read by Paraview or Visit.
virtual void print_system_info () const
print some information about the current processes/mpi/ranks/etc.
Protected Attributes
ParsedTools::Constants constants
ParsedLAC::ILUPreconditioner ilu_preconditioner
const FEValuesExtractors::Vector velocity
const FEValuesExtractors::Scalar pressure
Protected Attributes inherited from PDEs::MPI::LinearProblem< dim >
boost::signals2::signal< void()> add_constraints_call_back
A signal that is called at the end of setup_system()
boost::signals2::signal< void()> setup_system_call_back
A signal that is called at the end of setup_system()
boost::signals2::signal< void()> assemble_system_call_back
A signal that is called at the end of assemble_system()
boost::signals2::signal< void(ParsedTools::DataOut< dim, dim > &)> add_data_vector
Connect to this signal to add data additional vectors to the output system.
const std::string component_names
Comma seperated names of components.
const unsigned int n_components
Number of components.
const std::string problem_name
Name of the problem to solve.
const std::string section_name
Name of the section to use within the parameter file.
MPI_Comm mpi_communicator
Global mpi communicator.
int number_of_threads
Number of threads to use for multi-threaded assembly.
ConditionalOStream pcout
Output only on processor zero.
TimerOutput timer
Timing information.
ParsedTools::GridGenerator< dim, dim > grid_generator
A wrapper around GridIn, GridOut, and GridGenerator namespace.
ParsedTools::GridRefinement grid_refinement
Grid refinement and error estimation.
parallel::distributed::Triangulation< dim, dim > triangulation
The problem triangulation.
ParsedTools::FiniteElement< dim, dim > finite_element
A wrapper around deal.II FiniteElement classes.
std::unique_ptr< Mapping< dim, dim > > mapping
The Mapping between reference and real elements.
DoFHandler< dim, dim > dof_handler
Handler of degrees of freedom.
AffineConstraints< double > constraints
Hanging nodes and essential boundary conditions.
std::vector< types::global_dof_index > dofs_per_block
Dofs per block.
std::vector< IndexSet > locally_owned_dofs
All degrees of freedom owned by this MPI process.
std::vector< IndexSet > locally_relevant_dofs
All degrees of freedom needed for output and error estimation.
LA::MPI::BlockSparseMatrix system_block_matrix
System matrix.
LA::MPI::BlockVector locally_relevant_block_solution
A read only copy of the solution vector used for output and error estimation.
LA::MPI::BlockVector block_solution
Solution vector.
LA::MPI::BlockVector system_block_rhs
The system right hand side.
Vector< float > error_per_cell
Storage for local error estimator.
ParsedLAC::InverseOperator inverse_operator
Inverse operator.
ParsedLAC::AMGPreconditioner preconditioner
Preconditioner.
ParsedTools::Function< dim > forcing_term
The actual function to use as a forcing term.
ParsedTools::Function< dim > exact_solution
The actual function to use as a exact solution when computing the errors.
ParsedTools::BoundaryConditions< dim > boundary_conditions
Boundary conditions used in this class.
ParsedTools::ConvergenceTable error_table
This is a wrapper around the ParsedConvergenceTable class, that allows you to specify what error to computes, and how to compute them.
ParsedTools::DataOut< dim, dim > data_out
Wrapper around the DataOut class.
Protected Attributes inherited from ParameterAcceptor
const std::string section_name
std::vector< std::string > subsections
Additional Inherited Members
Static Public Member Functions inherited from ParameterAcceptor
static void initialize (const std::string &filename="", const std::string &output_filename="", const ParameterHandler::OutputStyle output_style_for_output_filename=ParameterHandler::Short, ParameterHandler &prm=ParameterAcceptor::prm, const ParameterHandler::OutputStyle output_style_for_filename=ParameterHandler::DefaultStyle)
static void initialize (std::istream &input_stream, ParameterHandler &prm=ParameterAcceptor::prm)
static void clear ()
static void parse_all_parameters (ParameterHandler &prm=ParameterAcceptor::prm)
static void declare_all_parameters (ParameterHandler &prm=ParameterAcceptor::prm)
static ::ExceptionBase & ExcInUse (int arg1, std::string arg2, std::string arg3)
static ::ExceptionBase & ExcNoSubscriber (std::string arg1, std::string arg2)
Static Public Member Functions inherited from Subscriptor
static ::ExceptionBase & ExcInUse (int arg1, std::string arg2, std::string arg3)
static ::ExceptionBase & ExcNoSubscriber (std::string arg1, std::string arg2)
Public Attributes inherited from ParameterAcceptor
boost::signals2::signal< void()> declare_parameters_call_back
boost::signals2::signal< void()> parse_parameters_call_back
Static Public Attributes inherited from ParameterAcceptor
static ParameterHandler prm
Detailed Description
template<int dim>
class PDEs::MPI::Stokes< dim >
Solve the Stokes problem, in parallel.
Definition at line 33 of file stokes.h.
Member Typedef Documentation
ScratchData
template<int dim> using PDEs::MPI::Stokes< dim >::ScratchData = typename LinearProblem<dim>::ScratchData
Definition at line 47 of file stokes.h.
CopyData
template<int dim> using PDEs::MPI::Stokes< dim >::CopyData = typename LinearProblem<dim>::CopyData
Definition at line 48 of file stokes.h.
Constructor & Destructor Documentation
Stokes()
template<int dim> PDEs::MPI::Stokes< dim >::Stokes
Constructor.
Initialize all parameters, including the base class, and make sure the class is ready to run.
Definition at line 29 of file stokes.cc.
~Stokes()
template<int dim> virtual PDEs::MPI::Stokes< dim >::~Stokes () virtual default
Destroy the Stokes object.
Member Function Documentation
assemble_system_one_cell()
template<int dim> void PDEs::MPI::Stokes< dim >::assemble_system_one_cell (const typename DoFHandler< dim >::active_cell_iterator & cell, ScratchData & scratch, CopyData & copy) override protected virtual
Explicitly assemble the Stokes problem on a single cell.
Definition at line 64 of file stokes.cc.
References cell_matrix(), copy(), and DoFHandler< dim, spacedim >::reinit().
solve()
template<int dim> void PDEs::MPI::Stokes< dim >::solve override protected virtual
Make sure we initialize the right type of linear solver.
Reimplemented from PDEs::MPI::LinearProblem< dim >.
Definition at line 117 of file stokes.cc.
References block_back_substitution(), deallog, and inverse_operator().
Member Data Documentation
constants
template<int dim> ParsedTools::Constants PDEs::MPI::Stokes< dim >::constants protected
Definition at line 66 of file stokes.h.
ilu_preconditioner
template<int dim> ParsedLAC::ILUPreconditioner PDEs::MPI::Stokes< dim >::ilu_preconditioner protected
Definition at line 67 of file stokes.h.
velocity
template<int dim> const FEValuesExtractors::Vector PDEs::MPI::Stokes< dim >::velocity protected
Definition at line 69 of file stokes.h.
pressure
template<int dim> const FEValuesExtractors::Scalar PDEs::MPI::Stokes< dim >::pressure protected
Definition at line 70 of file stokes.h.
The documentation for this class was generated from the following files:
include/pdes/mpi/stokes.h
source/pdes/mpi/stokes.cc