Fluid structure interaction suite: PDEs::LinearViscoElasticity< dim, spacedim, LacType > Class Template Reference
PDEs::LinearViscoElasticity< dim, spacedim, LacType > Class Template Reference
#include <linear_visco_elasticity.h>
Public Types
using ScratchData = typename LinearProblem< dim, spacedim, LacType >::ScratchData
using CopyData = typename LinearProblem< dim, spacedim, LacType >::CopyData
using VectorType = typename LinearProblem< dim, spacedim, LacType >::VectorType
Public Types inherited from PDEs::LinearProblem< dim, dim, LAC::LAdealii >
using ARKode = typename SUNDIALS::ARKode< typename LAC::LAdealii ::BlockVector >
SUNDIALS time integrator.
using Triangulation = typename std::conditional< dim==1, parallel::shared::Triangulation< dim, spacedim >, parallel::distributed::Triangulation< dim, spacedim > >::type
Make sure we can run also in 1d, where parallel distributed triangulations are not available, and we can only use parallel shared ones.
using CopyData = MeshWorker::CopyData< 1, 1, 1 >
Default CopyData object, used in the WorkStream class.
using ScratchData = MeshWorker::ScratchData< dim, spacedim >
Default ScratchData object, used in the workstream class.
using BlockVectorType = typename LAC::LAdealii ::BlockVector
Block vector type.
using VectorType = typename BlockVectorType::BlockType
Vector type.
using BlockMatrixType = typename LAC::LAdealii ::BlockSparseMatrix
Block matrix type.
Public Member Functions
LinearViscoElasticity ()
Constructor.
virtual ~LinearViscoElasticity ()=default
Destroy the LinearElasticity object.
void postprocess ()
Compute energy integrals.
Public Member Functions inherited from PDEs::LinearProblem< dim, dim, LAC::LAdealii >
LinearProblem (const std::string &component_names="u", const std::string &problem_name="")
Constructor.
virtual ~LinearProblem ()=default
Virtual destructor.
virtual void run ()
Main entry point of the problem.
void run_steady_state ()
Solve a steady state problem.
void run_quasi_static ()
Solve a quasi static problem.
void run_transient ()
Solve a dynamic problem.
virtual void setup_transient (ARKode &arkode)
Setup the transient problem.
virtual void assemble_system_one_cell (const typename DoFHandler< dim, spacedim >::active_cell_iterator &cell, ScratchData &scratch, CopyData &copy)
Assemble the local system matrix on cell, using scratch for FEValues and other expensive scratch objects, and store the result in the copy object.
virtual void copy_one_cell (const CopyData &copy)
Distribute the data that has been assembled by assemble_system_on_cell() to the global matrix and rhs.
virtual void estimate (Vector< float > &error_per_cell) const
Perform a posteriori error estimation, and store the results in the error_per_cell vector.
void mark (const Vector< float > &error_per_cell)
According to the chosen strategy, mark some cells for refinement, possibily using the error_per_cell vector.
void refine ()
Refine the grid.
virtual void setup_system ()
Initial setup: distribute degrees of freedom, make all vectors and matrices of the right size, initialize functions and pointers.
virtual void output_results (const unsigned cycle) const
Output the solution and the grid in a format that can be read by Paraview or Visit.
virtual void print_system_info () const
print some information about the current processes/mpi/ranks/etc.
Public Member Functions inherited from ParameterAcceptor
ParameterAcceptor (const std::string &section_name="")
virtual ~ParameterAcceptor () override
virtual void declare_parameters (ParameterHandler &prm)
virtual void parse_parameters (ParameterHandler &prm)
std::string get_section_name () const
std::vector< std::string > get_section_path () const
void add_parameter (const std::string &entry, ParameterType &parameter, const std::string &documentation="", ParameterHandler &prm_=prm, const Patterns::PatternBase &pattern=*Patterns::Tools::Convert< ParameterType >::to_pattern())
void enter_subsection (const std::string &subsection)
void leave_subsection ()
void enter_my_subsection (ParameterHandler &prm)
void leave_my_subsection (ParameterHandler &prm)
void serialize (Archive &ar, const unsigned int version)
void subscribe (std::atomic< bool > *const validity, const std::string &identifier="") const
void unsubscribe (std::atomic< bool > *const validity, const std::string &identifier="") const
unsigned int n_subscriptions () const
void list_subscribers (StreamType &stream) const
void list_subscribers () const
void subscribe (std::atomic< bool > *const validity, const std::string &identifier="") const
void unsubscribe (std::atomic< bool > *const validity, const std::string &identifier="") const
unsigned int n_subscriptions () const
void list_subscribers (StreamType &stream) const
void list_subscribers () const
Public Member Functions inherited from Subscriptor
Subscriptor ()
Subscriptor (const Subscriptor &)
Subscriptor (Subscriptor &&) noexcept
virtual ~Subscriptor ()
Subscriptor & operator= (const Subscriptor &)
Subscriptor & operator= (Subscriptor &&) noexcept
void serialize (Archive &ar, const unsigned int version)
void subscribe (std::atomic< bool > *const validity, const std::string &identifier="") const
void unsubscribe (std::atomic< bool > *const validity, const std::string &identifier="") const
unsigned int n_subscriptions () const
void list_subscribers (StreamType &stream) const
void list_subscribers () const
void subscribe (std::atomic< bool > *const validity, const std::string &identifier="") const
void unsubscribe (std::atomic< bool > *const validity, const std::string &identifier="") const
unsigned int n_subscriptions () const
void list_subscribers (StreamType &stream) const
void list_subscribers () const
Protected Member Functions
virtual void assemble_system () override
Explicitly assemble the LinearViscoElasticity problem.
virtual void solve () override
Make sure we initialize the right type of linear solver.
Protected Attributes
const FEValuesExtractors::Vector displacement
Displacement field extractor.
const FEValuesExtractors::Vector velocity
Velocity field extractor.
ParsedTools::Constants constants_0
Constants of the first material.
ParsedTools::Constants constants_1
Constants of the second material.
std::set< types::material_id > material_ids_0
Material ids of the first material.
std::set< types::material_id > material_ids_1
Material ids of the second material.
ParsedTools::MappingEulerian< dim, spacedim > eulerian_mapping
Mapping from reference configuration to deformed configuration.
double dt
Time step.
double current_time
Current time.
unsigned int current_cycle
Current cycle.
LacType::BlockVector current_displacement
LacType::BlockVector current_displacement_locally_relevant
Protected Attributes inherited from ParameterAcceptor
const std::string section_name
std::vector< std::string > subsections
Additional Inherited Members
Static Public Member Functions inherited from ParameterAcceptor
static void initialize (const std::string &filename="", const std::string &output_filename="", const ParameterHandler::OutputStyle output_style_for_output_filename=ParameterHandler::Short, ParameterHandler &prm=ParameterAcceptor::prm, const ParameterHandler::OutputStyle output_style_for_filename=ParameterHandler::DefaultStyle)
static void initialize (std::istream &input_stream, ParameterHandler &prm=ParameterAcceptor::prm)
static void clear ()
static void parse_all_parameters (ParameterHandler &prm=ParameterAcceptor::prm)
static void declare_all_parameters (ParameterHandler &prm=ParameterAcceptor::prm)
static ::ExceptionBase & ExcInUse (int arg1, std::string arg2, std::string arg3)
static ::ExceptionBase & ExcNoSubscriber (std::string arg1, std::string arg2)
Static Public Member Functions inherited from Subscriptor
static ::ExceptionBase & ExcInUse (int arg1, std::string arg2, std::string arg3)
static ::ExceptionBase & ExcNoSubscriber (std::string arg1, std::string arg2)
Public Attributes inherited from PDEs::LinearProblem< dim, dim, LAC::LAdealii >
boost::signals2::signal< void()> check_consistency_call_back
Check consistency of the problem.
boost::signals2::signal< void()> add_constraints_call_back
A signal that is called at the end of setup_system()
boost::signals2::signal< void()> setup_system_call_back
A signal that is called at the end of setup_system()
boost::signals2::signal< void()> output_results_call_back
A signal that is called at the end of output_results()
boost::signals2::signal< void()> assemble_system_call_back
A signal that is called at the end of assemble_system()
boost::signals2::signal< void(ParsedTools::DataOut< dim, spacedim > &)> add_data_vector
Connect to this signal to add data additional vectors to the output system.
boost::signals2::signal< void(const double &time, const double &time_step, const unsigned int &time_step_number)> advance_time_call_back
Connect to this signal to receive time information.
const std::string component_names
Comma seperated names of components.
const unsigned int n_components
Number of components.
const std::string problem_name
Name of the problem to solve.
const std::string section_name
Name of the section to use within the parameter file.
MPI_Comm mpi_communicator
Global mpi communicator.
const unsigned int mpi_rank
The mpi rank of this process.
const unsigned int mpi_size
The number of mpi processes.
int number_of_threads
Number of threads to use for multi-threaded assembly.
unsigned int verbosity_level
Verbosity level of deallog.
TimerOutput timer
Timing information.
EvolutionType evolution_type
Describe the type of time evolution of the problem.
ParsedTools::GridGenerator< dim, spacedim > grid_generator
A wrapper around GridIn, GridOut, and GridGenerator namespace.
ParsedTools::GridRefinement grid_refinement
Grid refinement and error estimation.
Triangulation triangulation
The problem triangulation.
ParsedTools::FiniteElement< dim, spacedim > finite_element
A wrapper around deal.II FiniteElement classes.
std::unique_ptr< Mapping< dim, spacedim > > mapping
The Mapping between reference and real elements.
DoFHandler< dim, spacedim > dof_handler
Handler of degrees of freedom.
AffineConstraints< double > constraints
Hanging nodes and essential boundary conditions.
std::vector< types::global_dof_index > dofs_per_block
Dofs per block.
std::vector< IndexSet > locally_owned_dofs
All degrees of freedom owned by this MPI process.
std::vector< IndexSet > locally_relevant_dofs
All degrees of freedom needed for output and error estimation.
LAC::LAdealii ::BlockSparsityPattern sparsity
System sparsity pattern.
LAC::LAdealii ::BlockSparseMatrix matrix
System matrix.
LAC::LAdealii ::BlockSparseMatrix mass_matrix
System matrix.
LAC::LAdealii ::BlockVector locally_relevant_solution
A read only copy of the solution vector used for output and error estimation.
LAC::LAdealii ::BlockVector solution
Solution vector.
LAC::LAdealii ::BlockVector rhs
The system right hand side.
Vector< float > error_per_cell
Storage for local error estimator.
ParsedLAC::InverseOperator inverse_operator
Inverse operator.
LAC::LAdealii ::AMG preconditioner
Preconditioner.
ParsedLAC::InverseOperator mass_inverse_operator
Inverse operator for the mass matrix.
LAC::LAdealii ::AMG mass_preconditioner
Preconditioner for the mass matrix.
ParsedTools::Function< spacedim > forcing_term
The actual function to use as a forcing term.
ParsedTools::Function< spacedim > exact_solution
The actual function to use as a exact solution when computing the errors.
ParsedTools::Function< spacedim > initial_value
Only used for transient problems.
ParsedTools::BoundaryConditions< spacedim > boundary_conditions
Boundary conditions used in this class.
ParsedTools::ConvergenceTable error_table
This is a wrapper around the ParsedConvergenceTable class, that allows you to specify what error to computes, and how to compute them.
ParsedTools::DataOut< dim, spacedim > data_out
Wrapper around the DataOut class.
double start_time
Initial time for transient and quasi stati simulations.
double end_time
Final time for transient and quasi-static simulations.
double desired_start_step_size
Initial step size for transient and quasi-static simulations.
unsigned int output_frequency
How often to output the solution.
ParsedTools::Proxy< typename SUNDIALS::ARKode< typename LAC::LAdealii ::BlockVector >::AdditionalData > ark_ode_data
Configuration used to setup transient simulations.
boost::signals2::signal< void(ARKode &)> setup_arkode_call_back
Signal that is triggered after creating the arkode object.
Public Attributes inherited from ParameterAcceptor
boost::signals2::signal< void()> declare_parameters_call_back
boost::signals2::signal< void()> parse_parameters_call_back
Static Public Attributes inherited from ParameterAcceptor
static ParameterHandler prm
Detailed Description
template<int dim, int spacedim = dim, class LacType = LAC::LAdealii>
class PDEs::LinearViscoElasticity< dim, spacedim, LacType >
Definition at line 44 of file linear_visco_elasticity.h.
Member Typedef Documentation
ScratchData
template<int dim, int spacedim = dim, class LacType = LAC::LAdealii> using PDEs::LinearViscoElasticity< dim, spacedim, LacType >::ScratchData = typename LinearProblem<dim, spacedim, LacType>::ScratchData
Definition at line 59 of file linear_visco_elasticity.h.
CopyData
template<int dim, int spacedim = dim, class LacType = LAC::LAdealii> using PDEs::LinearViscoElasticity< dim, spacedim, LacType >::CopyData = typename LinearProblem<dim, spacedim, LacType>::CopyData
Definition at line 61 of file linear_visco_elasticity.h.
VectorType
template<int dim, int spacedim = dim, class LacType = LAC::LAdealii> using PDEs::LinearViscoElasticity< dim, spacedim, LacType >::VectorType = typename LinearProblem<dim, spacedim, LacType>::VectorType
Definition at line 64 of file linear_visco_elasticity.h.
Constructor & Destructor Documentation
LinearViscoElasticity()
template<int dim, int spacedim, class LacType > PDEs::LinearViscoElasticity< dim, spacedim, LacType >::LinearViscoElasticity
Constructor.
Initialize all parameters, including the base class, and make sure the class is ready to run.
Definition at line 28 of file linear_visco_elasticity.cc.
~LinearViscoElasticity()
template<int dim, int spacedim = dim, class LacType = LAC::LAdealii> virtual PDEs::LinearViscoElasticity< dim, spacedim, LacType >::~LinearViscoElasticity () virtual default
Destroy the LinearElasticity object.
Member Function Documentation
postprocess()
template<int dim, int spacedim, class LacType > void PDEs::LinearViscoElasticity< dim, spacedim, LacType >::postprocess
Compute energy integrals.
Definition at line 245 of file linear_visco_elasticity.cc.
References ParsedTools::Components::get_cell_quadrature(), scalar_product(), Utilities::MPI::sum(), triangulation, update_gradients, update_JxW_values, update_quadrature_points, and update_values.
assemble_system()
template<int dim, int spacedim, class LacType > void PDEs::LinearViscoElasticity< dim, spacedim, LacType >::assemble_system override protected virtual
Explicitly assemble the LinearViscoElasticity problem.
Reimplemented from PDEs::LinearProblem< dim, dim, LAC::LAdealii >.
Definition at line 109 of file linear_visco_elasticity.cc.
References VectorOperation::add, cell_matrix(), copy(), first, ParsedTools::Components::get_cell_quadrature(), matrix, scalar_product(), triangulation, update_gradients, update_JxW_values, update_quadrature_points, and update_values.
solve()
template<int dim, int spacedim, class LacType > void PDEs::LinearViscoElasticity< dim, spacedim, LacType >::solve override protected virtual
Make sure we initialize the right type of linear solver.
Reimplemented from PDEs::LinearProblem< dim, dim, LAC::LAdealii >.
Definition at line 228 of file linear_visco_elasticity.cc.
References inverse_operator(), and matrix.
Member Data Documentation
displacement
template<int dim, int spacedim = dim, class LacType = LAC::LAdealii> const FEValuesExtractors::Vector PDEs::LinearViscoElasticity< dim, spacedim, LacType >::displacement protected
Displacement field extractor.
Definition at line 88 of file linear_visco_elasticity.h.
velocity
template<int dim, int spacedim = dim, class LacType = LAC::LAdealii> const FEValuesExtractors::Vector PDEs::LinearViscoElasticity< dim, spacedim, LacType >::velocity protected
Velocity field extractor.
Definition at line 93 of file linear_visco_elasticity.h.
constants_0
template<int dim, int spacedim = dim, class LacType = LAC::LAdealii> ParsedTools::Constants PDEs::LinearViscoElasticity< dim, spacedim, LacType >::constants_0 protected
Constants of the first material.
Definition at line 98 of file linear_visco_elasticity.h.
constants_1
template<int dim, int spacedim = dim, class LacType = LAC::LAdealii> ParsedTools::Constants PDEs::LinearViscoElasticity< dim, spacedim, LacType >::constants_1 protected
Constants of the second material.
Definition at line 103 of file linear_visco_elasticity.h.
material_ids_0
template<int dim, int spacedim = dim, class LacType = LAC::LAdealii> std::set<types::material_id> PDEs::LinearViscoElasticity< dim, spacedim, LacType >::material_ids_0 protected
Material ids of the first material.
Definition at line 108 of file linear_visco_elasticity.h.
material_ids_1
template<int dim, int spacedim = dim, class LacType = LAC::LAdealii> std::set<types::material_id> PDEs::LinearViscoElasticity< dim, spacedim, LacType >::material_ids_1 protected
Material ids of the second material.
Definition at line 113 of file linear_visco_elasticity.h.
eulerian_mapping
template<int dim, int spacedim = dim, class LacType = LAC::LAdealii> ParsedTools::MappingEulerian<dim, spacedim> PDEs::LinearViscoElasticity< dim, spacedim, LacType >::eulerian_mapping protected
Mapping from reference configuration to deformed configuration.
Definition at line 118 of file linear_visco_elasticity.h.
dt
template<int dim, int spacedim = dim, class LacType = LAC::LAdealii> double PDEs::LinearViscoElasticity< dim, spacedim, LacType >::dt protected
Time step.
Definition at line 123 of file linear_visco_elasticity.h.
current_time
template<int dim, int spacedim = dim, class LacType = LAC::LAdealii> double PDEs::LinearViscoElasticity< dim, spacedim, LacType >::current_time protected
Current time.
Definition at line 128 of file linear_visco_elasticity.h.
current_cycle
template<int dim, int spacedim = dim, class LacType = LAC::LAdealii> unsigned int PDEs::LinearViscoElasticity< dim, spacedim, LacType >::current_cycle protected
Current cycle.
Definition at line 133 of file linear_visco_elasticity.h.
current_displacement
template<int dim, int spacedim = dim, class LacType = LAC::LAdealii> LacType::BlockVector PDEs::LinearViscoElasticity< dim, spacedim, LacType >::current_displacement protected
Definition at line 135 of file linear_visco_elasticity.h.
current_displacement_locally_relevant
template<int dim, int spacedim = dim, class LacType = LAC::LAdealii> LacType::BlockVector PDEs::LinearViscoElasticity< dim, spacedim, LacType >::current_displacement_locally_relevant protected
Definition at line 136 of file linear_visco_elasticity.h.
The documentation for this class was generated from the following files:
include/pdes/linear_visco_elasticity.h
source/pdes/linear_visco_elasticity.cc