Fluid structure interaction suite: PDEs::SerialPoisson< dim, spacedim > Class Template Reference
PDEs::SerialPoisson< dim, spacedim > Class Template Reference
Serial Poisson problem.
#include <serial_poisson.h>
Public Member Functions
SerialPoisson ()
void run ()
Public Member Functions inherited from ParameterAcceptor
ParameterAcceptor (const std::string &section_name="")
virtual ~ParameterAcceptor () override
virtual void declare_parameters (ParameterHandler &prm)
virtual void parse_parameters (ParameterHandler &prm)
std::string get_section_name () const
std::vector< std::string > get_section_path () const
void add_parameter (const std::string &entry, ParameterType &parameter, const std::string &documentation="", ParameterHandler &prm_=prm, const Patterns::PatternBase &pattern=*Patterns::Tools::Convert< ParameterType >::to_pattern())
void enter_subsection (const std::string &subsection)
void leave_subsection ()
void enter_my_subsection (ParameterHandler &prm)
void leave_my_subsection (ParameterHandler &prm)
void serialize (Archive &ar, const unsigned int version)
void subscribe (std::atomic< bool > *const validity, const std::string &identifier="") const
void unsubscribe (std::atomic< bool > *const validity, const std::string &identifier="") const
unsigned int n_subscriptions () const
void list_subscribers (StreamType &stream) const
void list_subscribers () const
void subscribe (std::atomic< bool > *const validity, const std::string &identifier="") const
void unsubscribe (std::atomic< bool > *const validity, const std::string &identifier="") const
unsigned int n_subscriptions () const
void list_subscribers (StreamType &stream) const
void list_subscribers () const
Public Member Functions inherited from Subscriptor
Subscriptor ()
Subscriptor (const Subscriptor &)
Subscriptor (Subscriptor &&) noexcept
virtual ~Subscriptor ()
Subscriptor & operator= (const Subscriptor &)
Subscriptor & operator= (Subscriptor &&) noexcept
void serialize (Archive &ar, const unsigned int version)
void subscribe (std::atomic< bool > *const validity, const std::string &identifier="") const
void unsubscribe (std::atomic< bool > *const validity, const std::string &identifier="") const
unsigned int n_subscriptions () const
void list_subscribers (StreamType &stream) const
void list_subscribers () const
void subscribe (std::atomic< bool > *const validity, const std::string &identifier="") const
void unsubscribe (std::atomic< bool > *const validity, const std::string &identifier="") const
unsigned int n_subscriptions () const
void list_subscribers (StreamType &stream) const
void list_subscribers () const
Protected Member Functions
void setup_system ()
void assemble_system ()
void solve ()
void output_results (const unsigned cycle) const
Protected Attributes
const std::string component_names = "u"
How we identify the component names.
Tools::ParsedGridGenerator< dim, spacedim > grid_generator
Tools::ParsedGridRefinement grid_refinement
Triangulation< dim, spacedim > triangulation
Tools::ParsedFiniteElement< dim, spacedim > finite_element
DoFHandler< dim, spacedim > dof_handler
std::unique_ptr< Mapping< dim, spacedim > > mapping
AffineConstraints< double > constraints
SparsityPattern sparsity_pattern
SparseMatrix< double > system_matrix
Vector< double > solution
Vector< double > system_rhs
Tools::ParsedInverseOperator inverse_operator
Tools::ParsedAMGPreconditioner preconditioner
Tools::ParsedConstants constants
Tools::ParsedSymbolicFunction< spacedim > forcing_term
Tools::ParsedSymbolicFunction< spacedim > exact_solution
Tools::ParsedBoundaryConditions< spacedim > boundary_conditions
ParsedConvergenceTable error_table
Tools::ParsedDataOut< dim, spacedim > data_out
unsigned int console_level = 1
Protected Attributes inherited from ParameterAcceptor
const std::string section_name
std::vector< std::string > subsections
Additional Inherited Members
Static Public Member Functions inherited from ParameterAcceptor
static void initialize (const std::string &filename="", const std::string &output_filename="", const ParameterHandler::OutputStyle output_style_for_output_filename=ParameterHandler::Short, ParameterHandler &prm=ParameterAcceptor::prm, const ParameterHandler::OutputStyle output_style_for_filename=ParameterHandler::DefaultStyle)
static void initialize (std::istream &input_stream, ParameterHandler &prm=ParameterAcceptor::prm)
static void clear ()
static void parse_all_parameters (ParameterHandler &prm=ParameterAcceptor::prm)
static void declare_all_parameters (ParameterHandler &prm=ParameterAcceptor::prm)
static ::ExceptionBase & ExcInUse (int arg1, std::string arg2, std::string arg3)
static ::ExceptionBase & ExcNoSubscriber (std::string arg1, std::string arg2)
Static Public Member Functions inherited from Subscriptor
static ::ExceptionBase & ExcInUse (int arg1, std::string arg2, std::string arg3)
static ::ExceptionBase & ExcNoSubscriber (std::string arg1, std::string arg2)
Public Attributes inherited from ParameterAcceptor
boost::signals2::signal< void()> declare_parameters_call_back
boost::signals2::signal< void()> parse_parameters_call_back
Static Public Attributes inherited from ParameterAcceptor
static ParameterHandler prm
Detailed Description
template<int dim, int spacedim = dim>
class PDEs::SerialPoisson< dim, spacedim >
Serial Poisson problem.
Solve the Poisson equation in arbitrary dimensions and space dimensions. When dim and spacedim are not the same, we solve the LaplaceBeltrami equation.
\[ \begin{cases} - \Delta u = f & \text{ in } \Omega \subset R^{\text{spacedim}}\\ u = u_D & \text{ on } \partial \Omega_D \\ \frac{\partial u}{\partial n} u = u_N & \text{ on } \partial \Omega_N \\ \frac{\partial u}{\partial n} u + \rho u= u_R & \text{ on } \partial \Omega_R \end{cases} \]
Definition at line 65 of file serial_poisson.h.
Constructor & Destructor Documentation
SerialPoisson()
template<int dim, int spacedim> PDEs::SerialPoisson< dim, spacedim >::SerialPoisson
Definition at line 12 of file serial_poisson.cc.
References triangulation.
Member Function Documentation
assemble_system()
template<int dim, int spacedim> void PDEs::SerialPoisson< dim, spacedim >::assemble_system protected
Definition at line 88 of file serial_poisson.cc.
References cell_matrix(), deallog, FEValues< dim, spacedim >::dof_indices(), ReferenceCell::face_reference_cell(), ReferenceCell::get_gauss_type_quadrature(), FEValues< dim, spacedim >::JxW(), local_dof_indices, FEValues< dim, spacedim >::quadrature_point(), FEValues< dim, spacedim >::quadrature_point_indices(), FEValues< dim, spacedim >::reinit(), FEValues< dim, spacedim >::shape_grad(), FEValues< dim, spacedim >::shape_value(), update_gradients, update_JxW_values, update_quadrature_points, and update_values.
output_results()
template<int dim, int spacedim> void PDEs::SerialPoisson< dim, spacedim >::output_results (const unsigned cycle) const protected
Definition at line 191 of file serial_poisson.cc.
References deallog, Utilities::int_to_string(), and Utilities::needed_digits().
run()
template<int dim, int spacedim> void PDEs::SerialPoisson< dim, spacedim >::run
Definition at line 208 of file serial_poisson.cc.
References deallog, LogStream::depth_console(), Utilities::int_to_string(), LogStream::pop(), LogStream::push(), and triangulation.
Referenced by main().
setup_system()
template<int dim, int spacedim> void PDEs::SerialPoisson< dim, spacedim >::setup_system protected
Definition at line 45 of file serial_poisson.cc.
References AssertThrow, deallog, ExcMessage(), get_default_linear_mapping(), DoFTools::make_hanging_node_constraints(), DoFTools::make_sparsity_pattern(), reference_cell(), and triangulation.
solve()
template<int dim, int spacedim> void PDEs::SerialPoisson< dim, spacedim >::solve protected
Definition at line 177 of file serial_poisson.cc.
References deallog, and inverse_operator().
Member Data Documentation
boundary_conditions
template<int dim, int spacedim = dim> Tools::ParsedBoundaryConditions<spacedim> PDEs::SerialPoisson< dim, spacedim >::boundary_conditions protected
Definition at line 114 of file serial_poisson.h.
component_names
template<int dim, int spacedim = dim> const std::string PDEs::SerialPoisson< dim, spacedim >::component_names = "u" protected
How we identify the component names.
Definition at line 89 of file serial_poisson.h.
console_level
template<int dim, int spacedim = dim> unsigned int PDEs::SerialPoisson< dim, spacedim >::console_level = 1 protected
Definition at line 123 of file serial_poisson.h.
constants
template<int dim, int spacedim = dim> Tools::ParsedConstants PDEs::SerialPoisson< dim, spacedim >::constants protected
Definition at line 111 of file serial_poisson.h.
constraints
template<int dim, int spacedim = dim> AffineConstraints<double> PDEs::SerialPoisson< dim, spacedim >::constraints protected
Definition at line 102 of file serial_poisson.h.
data_out
template<int dim, int spacedim = dim> Tools::ParsedDataOut<dim, spacedim> PDEs::SerialPoisson< dim, spacedim >::data_out mutable protected
Definition at line 120 of file serial_poisson.h.
dof_handler
template<int dim, int spacedim = dim> DoFHandler<dim, spacedim> PDEs::SerialPoisson< dim, spacedim >::dof_handler protected
Definition at line 98 of file serial_poisson.h.
error_table
template<int dim, int spacedim = dim> ParsedConvergenceTable PDEs::SerialPoisson< dim, spacedim >::error_table protected
Definition at line 117 of file serial_poisson.h.
exact_solution
template<int dim, int spacedim = dim> Tools::ParsedSymbolicFunction<spacedim> PDEs::SerialPoisson< dim, spacedim >::exact_solution protected
Definition at line 113 of file serial_poisson.h.
finite_element
template<int dim, int spacedim = dim> Tools::ParsedFiniteElement<dim, spacedim> PDEs::SerialPoisson< dim, spacedim >::finite_element protected
Definition at line 97 of file serial_poisson.h.
forcing_term
template<int dim, int spacedim = dim> Tools::ParsedSymbolicFunction<spacedim> PDEs::SerialPoisson< dim, spacedim >::forcing_term protected
Definition at line 112 of file serial_poisson.h.
grid_generator
template<int dim, int spacedim = dim> Tools::ParsedGridGenerator<dim, spacedim> PDEs::SerialPoisson< dim, spacedim >::grid_generator protected
Definition at line 92 of file serial_poisson.h.
grid_refinement
template<int dim, int spacedim = dim> Tools::ParsedGridRefinement PDEs::SerialPoisson< dim, spacedim >::grid_refinement protected
Definition at line 93 of file serial_poisson.h.
inverse_operator
template<int dim, int spacedim = dim> Tools::ParsedInverseOperator PDEs::SerialPoisson< dim, spacedim >::inverse_operator protected
Definition at line 107 of file serial_poisson.h.
mapping
template<int dim, int spacedim = dim> std::unique_ptr<Mapping<dim, spacedim> > PDEs::SerialPoisson< dim, spacedim >::mapping protected
Definition at line 99 of file serial_poisson.h.
preconditioner
template<int dim, int spacedim = dim> Tools::ParsedAMGPreconditioner PDEs::SerialPoisson< dim, spacedim >::preconditioner protected
Definition at line 108 of file serial_poisson.h.
solution
template<int dim, int spacedim = dim> Vector<double> PDEs::SerialPoisson< dim, spacedim >::solution protected
Definition at line 105 of file serial_poisson.h.
sparsity_pattern
template<int dim, int spacedim = dim> SparsityPattern PDEs::SerialPoisson< dim, spacedim >::sparsity_pattern protected
Definition at line 103 of file serial_poisson.h.
system_matrix
template<int dim, int spacedim = dim> SparseMatrix<double> PDEs::SerialPoisson< dim, spacedim >::system_matrix protected
Definition at line 104 of file serial_poisson.h.
system_rhs
template<int dim, int spacedim = dim> Vector<double> PDEs::SerialPoisson< dim, spacedim >::system_rhs protected
Definition at line 106 of file serial_poisson.h.
triangulation
template<int dim, int spacedim = dim> Triangulation<dim, spacedim> PDEs::SerialPoisson< dim, spacedim >::triangulation protected
Definition at line 94 of file serial_poisson.h.
The documentation for this class was generated from the following files:
include/serial_poisson.h
source/serial_poisson.cc