Fluid structure interaction suite: PDEs::Serial::ReducedLagrange< dim, spacedim > Class Template Reference
PDEs::Serial::ReducedLagrange< dim, spacedim > Class Template Reference
#include <reduced_lagrange.h>
Public Member Functions
ReducedLagrange ()
void run ()
Public Member Functions inherited from ParameterAcceptor
ParameterAcceptor (const std::string &section_name="")
virtual ~ParameterAcceptor () override
virtual void declare_parameters (ParameterHandler &prm)
virtual void parse_parameters (ParameterHandler &prm)
std::string get_section_name () const
std::vector< std::string > get_section_path () const
void add_parameter (const std::string &entry, ParameterType &parameter, const std::string &documentation="", ParameterHandler &prm_=prm, const Patterns::PatternBase &pattern=*Patterns::Tools::Convert< ParameterType >::to_pattern())
void enter_subsection (const std::string &subsection)
void leave_subsection ()
void enter_my_subsection (ParameterHandler &prm)
void leave_my_subsection (ParameterHandler &prm)
void serialize (Archive &ar, const unsigned int version)
void subscribe (std::atomic< bool > *const validity, const std::string &identifier="") const
void unsubscribe (std::atomic< bool > *const validity, const std::string &identifier="") const
unsigned int n_subscriptions () const
void list_subscribers (StreamType &stream) const
void list_subscribers () const
void subscribe (std::atomic< bool > *const validity, const std::string &identifier="") const
void unsubscribe (std::atomic< bool > *const validity, const std::string &identifier="") const
unsigned int n_subscriptions () const
void list_subscribers (StreamType &stream) const
void list_subscribers () const
Public Member Functions inherited from Subscriptor
Subscriptor ()
Subscriptor (const Subscriptor &)
Subscriptor (Subscriptor &&) noexcept
virtual ~Subscriptor ()
Subscriptor & operator= (const Subscriptor &)
Subscriptor & operator= (Subscriptor &&) noexcept
void serialize (Archive &ar, const unsigned int version)
void subscribe (std::atomic< bool > *const validity, const std::string &identifier="") const
void unsubscribe (std::atomic< bool > *const validity, const std::string &identifier="") const
unsigned int n_subscriptions () const
void list_subscribers (StreamType &stream) const
void list_subscribers () const
void subscribe (std::atomic< bool > *const validity, const std::string &identifier="") const
void unsubscribe (std::atomic< bool > *const validity, const std::string &identifier="") const
unsigned int n_subscriptions () const
void list_subscribers (StreamType &stream) const
void list_subscribers () const
Private Member Functions
void generate_grids_and_fes ()
void adjust_embedded_grid (const bool apply_delta_refinement=true)
void update_basis_functions ()
void setup_dofs ()
void setup_coupling ()
void assemble_system ()
void solve ()
void output_results (const unsigned int cycle)
Private Attributes
const std::string component_names = "u"
unsigned int coupling_quadrature_order = 3
unsigned int delta_refinement = 0
unsigned int console_level = 1
bool use_direct_solver = true
unsigned int n_basis = 1
Triangulation< spacedim > space_grid
std::unique_ptr< FiniteElement< spacedim > > space_fe
std::unique_ptr< MappingFE< spacedim > > space_mapping
std::unique_ptr< GridTools::Cache< spacedim, spacedim > > space_grid_tools_cache
DoFHandler< spacedim > space_dh
Triangulation< dim, spacedim > embedded_grid
std::unique_ptr< FiniteElement< dim, spacedim > > embedded_fe
DoFHandler< dim, spacedim > embedded_dh
std::unique_ptr< FiniteElement< dim, spacedim > > embedded_configuration_fe
DoFHandler< dim, spacedim > embedded_configuration_dh
Vector< double > embedded_configuration
SparsityPattern stiffness_sparsity
SparseMatrix< double > stiffness_matrix
SparsityPattern coupling_sparsity
SparseMatrix< double > coupling_matrix
SparsityPattern embedded_sparsity
SparseMatrix< double > embedded_mass_matrix
AffineConstraints< double > constraints
AffineConstraints< double > embedded_constraints
Vector< double > solution
Vector< double > rhs
Vector< double > lambda
Vector< double > embedded_rhs
Vector< double > embedded_value
std::vector< Vector< double > > basis_functions
std::vector< Vector< double > > reciprocal_basis_functions
Vector< double > reduced_rhs
Vector< double > reduced_value
Vector< double > reduced_lambda
TimerOutput monitor
unsigned int finite_element_degree = 1
unsigned int embedded_space_finite_element_degree = 1
unsigned int embedded_configuration_finite_element_degree = 1
ParsedTools::GridGenerator< spacedim > grid_generator
ParsedTools::GridRefinement grid_refinement
ParsedTools::GridGenerator< dim, spacedim > embedded_grid_generator
ParsedTools::MappingEulerian< dim, spacedim > embedded_mapping
ParsedTools::Constants constants
ParsedTools::Function< spacedim > embedded_value_function
ParsedTools::Function< spacedim > forcing_term
ParsedTools::Function< spacedim > exact_solution
ParsedTools::BoundaryConditions< spacedim > boundary_conditions
ParsedLAC::InverseOperator stiffness_inverse_operator
ParsedLAC::AMGPreconditioner stiffness_preconditioner
ParsedLAC::InverseOperator schur_inverse_operator
ParsedTools::DataOut< spacedim > data_out
ParsedTools::DataOut< dim, spacedim > embedded_data_out
ParsedConvergenceTable error_table
Additional Inherited Members
Static Public Member Functions inherited from ParameterAcceptor
static void initialize (const std::string &filename="", const std::string &output_filename="", const ParameterHandler::OutputStyle output_style_for_output_filename=ParameterHandler::Short, ParameterHandler &prm=ParameterAcceptor::prm, const ParameterHandler::OutputStyle output_style_for_filename=ParameterHandler::DefaultStyle)
static void initialize (std::istream &input_stream, ParameterHandler &prm=ParameterAcceptor::prm)
static void clear ()
static void parse_all_parameters (ParameterHandler &prm=ParameterAcceptor::prm)
static void declare_all_parameters (ParameterHandler &prm=ParameterAcceptor::prm)
static ::ExceptionBase & ExcInUse (int arg1, std::string arg2, std::string arg3)
static ::ExceptionBase & ExcNoSubscriber (std::string arg1, std::string arg2)
Static Public Member Functions inherited from Subscriptor
static ::ExceptionBase & ExcInUse (int arg1, std::string arg2, std::string arg3)
static ::ExceptionBase & ExcNoSubscriber (std::string arg1, std::string arg2)
Public Attributes inherited from ParameterAcceptor
boost::signals2::signal< void()> declare_parameters_call_back
boost::signals2::signal< void()> parse_parameters_call_back
Static Public Attributes inherited from ParameterAcceptor
static ParameterHandler prm
Protected Attributes inherited from ParameterAcceptor
const std::string section_name
std::vector< std::string > subsections
Detailed Description
template<int dim, int spacedim = dim>
class PDEs::Serial::ReducedLagrange< dim, spacedim >
Definition at line 52 of file reduced_lagrange.h.
Constructor & Destructor Documentation
ReducedLagrange()
template<int dim, int spacedim> PDEs::Serial::ReducedLagrange< dim, spacedim >::ReducedLagrange
Definition at line 49 of file reduced_lagrange.cc.
References ParameterAcceptor::add_parameter(), ParsedConvergenceTable::add_parameters(), PDEs::Serial::ReducedLagrange< dim, spacedim >::console_level, PDEs::Serial::ReducedLagrange< dim, spacedim >::coupling_quadrature_order, PDEs::Serial::ReducedLagrange< dim, spacedim >::delta_refinement, PDEs::Serial::ReducedLagrange< dim, spacedim >::embedded_configuration_finite_element_degree, PDEs::Serial::ReducedLagrange< dim, spacedim >::embedded_space_finite_element_degree, ParameterAcceptor::enter_my_subsection(), ParameterAcceptor::enter_subsection(), PDEs::Serial::ReducedLagrange< dim, spacedim >::error_table, PDEs::Serial::ReducedLagrange< dim, spacedim >::finite_element_degree, ParameterAcceptor::leave_my_subsection(), ParameterAcceptor::leave_subsection(), PDEs::Serial::ReducedLagrange< dim, spacedim >::n_basis, ParameterAcceptor::prm, and PDEs::Serial::ReducedLagrange< dim, spacedim >::use_direct_solver.
Member Function Documentation
run()
template<int dim, int spacedim> void PDEs::Serial::ReducedLagrange< dim, spacedim >::run
Definition at line 523 of file reduced_lagrange.cc.
References deallog, LogStream::depth_console(), Utilities::int_to_string(), LogStream::pop(), and LogStream::push().
Referenced by main().
generate_grids_and_fes()
template<int dim, int spacedim> void PDEs::Serial::ReducedLagrange< dim, spacedim >::generate_grids_and_fes private
Definition at line 99 of file reduced_lagrange.cc.
References ParsedTools::Components::get_lagrangian_finite_element().
adjust_embedded_grid()
template<int dim, int spacedim> void PDEs::Serial::ReducedLagrange< dim, spacedim >::adjust_embedded_grid (const bool apply_delta_refinement = true) private
Definition at line 135 of file reduced_lagrange.cc.
References center, deallog, diameter(), GridTools::maximal_cell_diameter(), and GridTools::minimal_cell_diameter().
update_basis_functions()
template<int dim, int spacedim> void PDEs::Serial::ReducedLagrange< dim, spacedim >::update_basis_functions private
Definition at line 232 of file reduced_lagrange.cc.
References deallog, SparseDirectUMFPACK::initialize(), VectorTools::interpolate(), and SparseDirectUMFPACK::vmult().
setup_dofs()
template<int dim, int spacedim> void PDEs::Serial::ReducedLagrange< dim, spacedim >::setup_dofs private
Definition at line 283 of file reduced_lagrange.cc.
References deallog, lambda, DoFTools::make_hanging_node_constraints(), and DoFTools::make_sparsity_pattern().
setup_coupling()
template<int dim, int spacedim> void PDEs::Serial::ReducedLagrange< dim, spacedim >::setup_coupling private
Definition at line 336 of file reduced_lagrange.cc.
References NonMatching::create_coupling_sparsity_pattern(), and ParsedTools::Components::get_cell_quadrature().
assemble_system()
template<int dim, int spacedim> void PDEs::Serial::ReducedLagrange< dim, spacedim >::assemble_system private
Definition at line 360 of file reduced_lagrange.cc.
References NonMatching::create_coupling_mass_matrix(), MatrixCreator::create_mass_matrix(), VectorTools::create_right_hand_side(), ParsedTools::Components::get_cell_quadrature(), and VectorTools::interpolate().
solve()
template<int dim, int spacedim> void PDEs::Serial::ReducedLagrange< dim, spacedim >::solve private
Definition at line 416 of file reduced_lagrange.cc.
References C(), deallog, identity_operator(), SparseDirectUMFPACK::initialize(), FullMatrix< double >::invert(), lambda, linear_operator(), dealii::projection_operator(), transpose_operator(), and FullMatrix< double >::vmult().
output_results()
template<int dim, int spacedim> void PDEs::Serial::ReducedLagrange< dim, spacedim >::output_results (const unsigned int cycle) private
Definition at line 490 of file reduced_lagrange.cc.
References Utilities::int_to_string(), lambda, and Utilities::needed_digits().
Member Data Documentation
component_names
template<int dim, int spacedim = dim> const std::string PDEs::Serial::ReducedLagrange< dim, spacedim >::component_names = "u" private
Definition at line 78 of file reduced_lagrange.h.
coupling_quadrature_order
template<int dim, int spacedim = dim> unsigned int PDEs::Serial::ReducedLagrange< dim, spacedim >::coupling_quadrature_order = 3 private
Definition at line 80 of file reduced_lagrange.h.
Referenced by PDEs::Serial::ReducedLagrange< dim, spacedim >::ReducedLagrange().
delta_refinement
template<int dim, int spacedim = dim> unsigned int PDEs::Serial::ReducedLagrange< dim, spacedim >::delta_refinement = 0 private
Definition at line 81 of file reduced_lagrange.h.
Referenced by PDEs::Serial::ReducedLagrange< dim, spacedim >::ReducedLagrange().
console_level
template<int dim, int spacedim = dim> unsigned int PDEs::Serial::ReducedLagrange< dim, spacedim >::console_level = 1 private
Definition at line 82 of file reduced_lagrange.h.
Referenced by PDEs::Serial::ReducedLagrange< dim, spacedim >::ReducedLagrange().
use_direct_solver
template<int dim, int spacedim = dim> bool PDEs::Serial::ReducedLagrange< dim, spacedim >::use_direct_solver = true private
Definition at line 83 of file reduced_lagrange.h.
Referenced by PDEs::Serial::ReducedLagrange< dim, spacedim >::ReducedLagrange().
n_basis
template<int dim, int spacedim = dim> unsigned int PDEs::Serial::ReducedLagrange< dim, spacedim >::n_basis = 1 private
Definition at line 84 of file reduced_lagrange.h.
Referenced by PDEs::Serial::ReducedLagrange< dim, spacedim >::ReducedLagrange().
space_grid
template<int dim, int spacedim = dim> Triangulation<spacedim> PDEs::Serial::ReducedLagrange< dim, spacedim >::space_grid private
Definition at line 86 of file reduced_lagrange.h.
space_fe
template<int dim, int spacedim = dim> std::unique_ptr<FiniteElement<spacedim> > PDEs::Serial::ReducedLagrange< dim, spacedim >::space_fe private
Definition at line 87 of file reduced_lagrange.h.
space_mapping
template<int dim, int spacedim = dim> std::unique_ptr<MappingFE<spacedim> > PDEs::Serial::ReducedLagrange< dim, spacedim >::space_mapping private
Definition at line 88 of file reduced_lagrange.h.
space_grid_tools_cache
template<int dim, int spacedim = dim> std::unique_ptr<GridTools::Cache<spacedim, spacedim> > PDEs::Serial::ReducedLagrange< dim, spacedim >::space_grid_tools_cache private
Definition at line 90 of file reduced_lagrange.h.
space_dh
template<int dim, int spacedim = dim> DoFHandler<spacedim> PDEs::Serial::ReducedLagrange< dim, spacedim >::space_dh private
Definition at line 91 of file reduced_lagrange.h.
embedded_grid
template<int dim, int spacedim = dim> Triangulation<dim, spacedim> PDEs::Serial::ReducedLagrange< dim, spacedim >::embedded_grid private
Definition at line 93 of file reduced_lagrange.h.
embedded_fe
template<int dim, int spacedim = dim> std::unique_ptr<FiniteElement<dim, spacedim> > PDEs::Serial::ReducedLagrange< dim, spacedim >::embedded_fe private
Definition at line 94 of file reduced_lagrange.h.
embedded_dh
template<int dim, int spacedim = dim> DoFHandler<dim, spacedim> PDEs::Serial::ReducedLagrange< dim, spacedim >::embedded_dh private
Definition at line 95 of file reduced_lagrange.h.
embedded_configuration_fe
template<int dim, int spacedim = dim> std::unique_ptr<FiniteElement<dim, spacedim> > PDEs::Serial::ReducedLagrange< dim, spacedim >::embedded_configuration_fe private
Definition at line 97 of file reduced_lagrange.h.
embedded_configuration_dh
template<int dim, int spacedim = dim> DoFHandler<dim, spacedim> PDEs::Serial::ReducedLagrange< dim, spacedim >::embedded_configuration_dh private
Definition at line 98 of file reduced_lagrange.h.
embedded_configuration
template<int dim, int spacedim = dim> Vector<double> PDEs::Serial::ReducedLagrange< dim, spacedim >::embedded_configuration private
Definition at line 99 of file reduced_lagrange.h.
stiffness_sparsity
template<int dim, int spacedim = dim> SparsityPattern PDEs::Serial::ReducedLagrange< dim, spacedim >::stiffness_sparsity private
Definition at line 101 of file reduced_lagrange.h.
stiffness_matrix
template<int dim, int spacedim = dim> SparseMatrix<double> PDEs::Serial::ReducedLagrange< dim, spacedim >::stiffness_matrix private
Definition at line 102 of file reduced_lagrange.h.
coupling_sparsity
template<int dim, int spacedim = dim> SparsityPattern PDEs::Serial::ReducedLagrange< dim, spacedim >::coupling_sparsity private
Definition at line 104 of file reduced_lagrange.h.
coupling_matrix
template<int dim, int spacedim = dim> SparseMatrix<double> PDEs::Serial::ReducedLagrange< dim, spacedim >::coupling_matrix private
Definition at line 105 of file reduced_lagrange.h.
embedded_sparsity
template<int dim, int spacedim = dim> SparsityPattern PDEs::Serial::ReducedLagrange< dim, spacedim >::embedded_sparsity private
Definition at line 107 of file reduced_lagrange.h.
embedded_mass_matrix
template<int dim, int spacedim = dim> SparseMatrix<double> PDEs::Serial::ReducedLagrange< dim, spacedim >::embedded_mass_matrix private
Definition at line 108 of file reduced_lagrange.h.
constraints
template<int dim, int spacedim = dim> AffineConstraints<double> PDEs::Serial::ReducedLagrange< dim, spacedim >::constraints private
Definition at line 110 of file reduced_lagrange.h.
embedded_constraints
template<int dim, int spacedim = dim> AffineConstraints<double> PDEs::Serial::ReducedLagrange< dim, spacedim >::embedded_constraints private
Definition at line 111 of file reduced_lagrange.h.
solution
template<int dim, int spacedim = dim> Vector<double> PDEs::Serial::ReducedLagrange< dim, spacedim >::solution private
Definition at line 113 of file reduced_lagrange.h.
rhs
template<int dim, int spacedim = dim> Vector<double> PDEs::Serial::ReducedLagrange< dim, spacedim >::rhs private
Definition at line 114 of file reduced_lagrange.h.
lambda
template<int dim, int spacedim = dim> Vector<double> PDEs::Serial::ReducedLagrange< dim, spacedim >::lambda private
Definition at line 116 of file reduced_lagrange.h.
embedded_rhs
template<int dim, int spacedim = dim> Vector<double> PDEs::Serial::ReducedLagrange< dim, spacedim >::embedded_rhs private
Definition at line 117 of file reduced_lagrange.h.
embedded_value
template<int dim, int spacedim = dim> Vector<double> PDEs::Serial::ReducedLagrange< dim, spacedim >::embedded_value private
Definition at line 118 of file reduced_lagrange.h.
basis_functions
template<int dim, int spacedim = dim> std::vector<Vector<double> > PDEs::Serial::ReducedLagrange< dim, spacedim >::basis_functions private
Definition at line 120 of file reduced_lagrange.h.
reciprocal_basis_functions
template<int dim, int spacedim = dim> std::vector<Vector<double> > PDEs::Serial::ReducedLagrange< dim, spacedim >::reciprocal_basis_functions private
Definition at line 121 of file reduced_lagrange.h.
reduced_rhs
template<int dim, int spacedim = dim> Vector<double> PDEs::Serial::ReducedLagrange< dim, spacedim >::reduced_rhs private
Definition at line 122 of file reduced_lagrange.h.
reduced_value
template<int dim, int spacedim = dim> Vector<double> PDEs::Serial::ReducedLagrange< dim, spacedim >::reduced_value private
Definition at line 123 of file reduced_lagrange.h.
reduced_lambda
template<int dim, int spacedim = dim> Vector<double> PDEs::Serial::ReducedLagrange< dim, spacedim >::reduced_lambda private
Definition at line 124 of file reduced_lagrange.h.
monitor
template<int dim, int spacedim = dim> TimerOutput PDEs::Serial::ReducedLagrange< dim, spacedim >::monitor private
Definition at line 126 of file reduced_lagrange.h.
finite_element_degree
template<int dim, int spacedim = dim> unsigned int PDEs::Serial::ReducedLagrange< dim, spacedim >::finite_element_degree = 1 private
Definition at line 129 of file reduced_lagrange.h.
Referenced by PDEs::Serial::ReducedLagrange< dim, spacedim >::ReducedLagrange().
embedded_space_finite_element_degree
template<int dim, int spacedim = dim> unsigned int PDEs::Serial::ReducedLagrange< dim, spacedim >::embedded_space_finite_element_degree = 1 private
Definition at line 130 of file reduced_lagrange.h.
Referenced by PDEs::Serial::ReducedLagrange< dim, spacedim >::ReducedLagrange().
embedded_configuration_finite_element_degree
template<int dim, int spacedim = dim> unsigned int PDEs::Serial::ReducedLagrange< dim, spacedim >::embedded_configuration_finite_element_degree = 1 private
Definition at line 131 of file reduced_lagrange.h.
Referenced by PDEs::Serial::ReducedLagrange< dim, spacedim >::ReducedLagrange().
grid_generator
template<int dim, int spacedim = dim> ParsedTools::GridGenerator<spacedim> PDEs::Serial::ReducedLagrange< dim, spacedim >::grid_generator private
Definition at line 134 of file reduced_lagrange.h.
grid_refinement
template<int dim, int spacedim = dim> ParsedTools::GridRefinement PDEs::Serial::ReducedLagrange< dim, spacedim >::grid_refinement private
Definition at line 135 of file reduced_lagrange.h.
embedded_grid_generator
template<int dim, int spacedim = dim> ParsedTools::GridGenerator<dim, spacedim> PDEs::Serial::ReducedLagrange< dim, spacedim >::embedded_grid_generator private
Definition at line 137 of file reduced_lagrange.h.
embedded_mapping
template<int dim, int spacedim = dim> ParsedTools::MappingEulerian<dim, spacedim> PDEs::Serial::ReducedLagrange< dim, spacedim >::embedded_mapping private
Definition at line 138 of file reduced_lagrange.h.
constants
template<int dim, int spacedim = dim> ParsedTools::Constants PDEs::Serial::ReducedLagrange< dim, spacedim >::constants private
Definition at line 140 of file reduced_lagrange.h.
embedded_value_function
template<int dim, int spacedim = dim> ParsedTools::Function<spacedim> PDEs::Serial::ReducedLagrange< dim, spacedim >::embedded_value_function private
Definition at line 141 of file reduced_lagrange.h.
forcing_term
template<int dim, int spacedim = dim> ParsedTools::Function<spacedim> PDEs::Serial::ReducedLagrange< dim, spacedim >::forcing_term private
Definition at line 142 of file reduced_lagrange.h.
exact_solution
template<int dim, int spacedim = dim> ParsedTools::Function<spacedim> PDEs::Serial::ReducedLagrange< dim, spacedim >::exact_solution private
Definition at line 143 of file reduced_lagrange.h.
boundary_conditions
template<int dim, int spacedim = dim> ParsedTools::BoundaryConditions<spacedim> PDEs::Serial::ReducedLagrange< dim, spacedim >::boundary_conditions private
Definition at line 144 of file reduced_lagrange.h.
stiffness_inverse_operator
template<int dim, int spacedim = dim> ParsedLAC::InverseOperator PDEs::Serial::ReducedLagrange< dim, spacedim >::stiffness_inverse_operator private
Definition at line 146 of file reduced_lagrange.h.
stiffness_preconditioner
template<int dim, int spacedim = dim> ParsedLAC::AMGPreconditioner PDEs::Serial::ReducedLagrange< dim, spacedim >::stiffness_preconditioner private
Definition at line 147 of file reduced_lagrange.h.
schur_inverse_operator
template<int dim, int spacedim = dim> ParsedLAC::InverseOperator PDEs::Serial::ReducedLagrange< dim, spacedim >::schur_inverse_operator private
Definition at line 149 of file reduced_lagrange.h.
data_out
template<int dim, int spacedim = dim> ParsedTools::DataOut<spacedim> PDEs::Serial::ReducedLagrange< dim, spacedim >::data_out mutable private
Definition at line 151 of file reduced_lagrange.h.
embedded_data_out
template<int dim, int spacedim = dim> ParsedTools::DataOut<dim, spacedim> PDEs::Serial::ReducedLagrange< dim, spacedim >::embedded_data_out mutable private
Definition at line 152 of file reduced_lagrange.h.
error_table
template<int dim, int spacedim = dim> ParsedConvergenceTable PDEs::Serial::ReducedLagrange< dim, spacedim >::error_table private
Definition at line 153 of file reduced_lagrange.h.
Referenced by PDEs::Serial::ReducedLagrange< dim, spacedim >::ReducedLagrange().
The documentation for this class was generated from the following files:
include/pdes/serial/reduced_lagrange.h
source/pdes/serial/reduced_lagrange.cc