Fluid structure interaction suite: PDEs::Stokes< dim, LacType > Class Template Reference
PDEs::Stokes< dim, LacType > Class Template Reference
Solve the Stokes problem, in parallel.
#include <stokes.h>
Public Types
using ScratchData = typename LinearProblem< dim, dim, LacType >::ScratchData
using CopyData = typename LinearProblem< dim, dim, LacType >::CopyData
using VectorType = typename LinearProblem< dim, dim, LacType >::VectorType
Public Types inherited from PDEs::LinearProblem< dim, dim, LacType >
using ARKode = typename SUNDIALS::ARKode< typename LacType::BlockVector >
SUNDIALS time integrator.
using Triangulation = typename std::conditional< dim==1, parallel::shared::Triangulation< dim, spacedim >, parallel::distributed::Triangulation< dim, spacedim > >::type
Make sure we can run also in 1d, where parallel distributed triangulations are not available, and we can only use parallel shared ones.
using CopyData = MeshWorker::CopyData< 1, 1, 1 >
Default CopyData object, used in the WorkStream class.
using ScratchData = MeshWorker::ScratchData< dim, spacedim >
Default ScratchData object, used in the workstream class.
using BlockVectorType = typename LacType::BlockVector
Block vector type.
using VectorType = typename BlockVectorType::BlockType
Vector type.
using BlockMatrixType = typename LacType::BlockSparseMatrix
Block matrix type.
Public Member Functions
Stokes ()
Constructor.
virtual ~Stokes ()=default
Destroy the Stokes object.
Public Member Functions inherited from PDEs::LinearProblem< dim, dim, LacType >
LinearProblem (const std::string &component_names="u", const std::string &problem_name="")
Constructor.
virtual ~LinearProblem ()=default
Virtual destructor.
virtual void run ()
Main entry point of the problem.
void run_steady_state ()
Solve a steady state problem.
void run_quasi_static ()
Solve a quasi static problem.
void run_transient ()
Solve a dynamic problem.
virtual void setup_transient (ARKode &arkode)
Setup the transient problem.
virtual void assemble_system_one_cell (const typename DoFHandler< dim, spacedim >::active_cell_iterator &cell, ScratchData &scratch, CopyData &copy)
Assemble the local system matrix on cell, using scratch for FEValues and other expensive scratch objects, and store the result in the copy object.
virtual void copy_one_cell (const CopyData &copy)
Distribute the data that has been assembled by assemble_system_on_cell() to the global matrix and rhs.
virtual void estimate (Vector< float > &error_per_cell) const
Perform a posteriori error estimation, and store the results in the error_per_cell vector.
void mark (const Vector< float > &error_per_cell)
According to the chosen strategy, mark some cells for refinement, possibily using the error_per_cell vector.
void refine ()
Refine the grid.
virtual void setup_system ()
Initial setup: distribute degrees of freedom, make all vectors and matrices of the right size, initialize functions and pointers.
virtual void custom_estimator (Vector< float > &error_per_cell) const
Overload this function to use a custom error estimator in the mesh refinement process.
virtual void assemble_system ()
Actually loop over cells, and assemble the global system.
virtual void output_results (const unsigned cycle) const
Output the solution and the grid in a format that can be read by Paraview or Visit.
virtual void print_system_info () const
print some information about the current processes/mpi/ranks/etc.
Public Member Functions inherited from ParameterAcceptor
ParameterAcceptor (const std::string &section_name="")
virtual ~ParameterAcceptor () override
virtual void declare_parameters (ParameterHandler &prm)
virtual void parse_parameters (ParameterHandler &prm)
std::string get_section_name () const
std::vector< std::string > get_section_path () const
void add_parameter (const std::string &entry, ParameterType &parameter, const std::string &documentation="", ParameterHandler &prm_=prm, const Patterns::PatternBase &pattern=*Patterns::Tools::Convert< ParameterType >::to_pattern())
void enter_subsection (const std::string &subsection)
void leave_subsection ()
void enter_my_subsection (ParameterHandler &prm)
void leave_my_subsection (ParameterHandler &prm)
void serialize (Archive &ar, const unsigned int version)
void subscribe (std::atomic< bool > *const validity, const std::string &identifier="") const
void unsubscribe (std::atomic< bool > *const validity, const std::string &identifier="") const
unsigned int n_subscriptions () const
void list_subscribers (StreamType &stream) const
void list_subscribers () const
void subscribe (std::atomic< bool > *const validity, const std::string &identifier="") const
void unsubscribe (std::atomic< bool > *const validity, const std::string &identifier="") const
unsigned int n_subscriptions () const
void list_subscribers (StreamType &stream) const
void list_subscribers () const
Public Member Functions inherited from Subscriptor
Subscriptor ()
Subscriptor (const Subscriptor &)
Subscriptor (Subscriptor &&) noexcept
virtual ~Subscriptor ()
Subscriptor & operator= (const Subscriptor &)
Subscriptor & operator= (Subscriptor &&) noexcept
void serialize (Archive &ar, const unsigned int version)
void subscribe (std::atomic< bool > *const validity, const std::string &identifier="") const
void unsubscribe (std::atomic< bool > *const validity, const std::string &identifier="") const
unsigned int n_subscriptions () const
void list_subscribers (StreamType &stream) const
void list_subscribers () const
void subscribe (std::atomic< bool > *const validity, const std::string &identifier="") const
void unsubscribe (std::atomic< bool > *const validity, const std::string &identifier="") const
unsigned int n_subscriptions () const
void list_subscribers (StreamType &stream) const
void list_subscribers () const
Protected Member Functions
virtual void assemble_system_one_cell (const typename DoFHandler< dim >::active_cell_iterator &cell, ScratchData &scratch, CopyData &copy) override
Explicitly assemble the Stokes problem on a single cell.
virtual void solve () override
Make sure we initialize the right type of linear solver.
Protected Attributes
ParsedTools::Constants constants
LacType::AMG schur_preconditioner
ParsedLAC::InverseOperator schur_solver
const FEValuesExtractors::Vector velocity
const FEValuesExtractors::Scalar pressure
Protected Attributes inherited from ParameterAcceptor
const std::string section_name
std::vector< std::string > subsections
Additional Inherited Members
Static Public Member Functions inherited from ParameterAcceptor
static void initialize (const std::string &filename="", const std::string &output_filename="", const ParameterHandler::OutputStyle output_style_for_output_filename=ParameterHandler::Short, ParameterHandler &prm=ParameterAcceptor::prm, const ParameterHandler::OutputStyle output_style_for_filename=ParameterHandler::DefaultStyle)
static void initialize (std::istream &input_stream, ParameterHandler &prm=ParameterAcceptor::prm)
static void clear ()
static void parse_all_parameters (ParameterHandler &prm=ParameterAcceptor::prm)
static void declare_all_parameters (ParameterHandler &prm=ParameterAcceptor::prm)
static ::ExceptionBase & ExcInUse (int arg1, std::string arg2, std::string arg3)
static ::ExceptionBase & ExcNoSubscriber (std::string arg1, std::string arg2)
Static Public Member Functions inherited from Subscriptor
static ::ExceptionBase & ExcInUse (int arg1, std::string arg2, std::string arg3)
static ::ExceptionBase & ExcNoSubscriber (std::string arg1, std::string arg2)
Public Attributes inherited from PDEs::LinearProblem< dim, dim, LacType >
boost::signals2::signal< void()> check_consistency_call_back
Check consistency of the problem.
boost::signals2::signal< void()> add_constraints_call_back
A signal that is called at the end of setup_system()
boost::signals2::signal< void()> setup_system_call_back
A signal that is called at the end of setup_system()
boost::signals2::signal< void()> output_results_call_back
A signal that is called at the end of output_results()
boost::signals2::signal< void()> assemble_system_call_back
A signal that is called at the end of assemble_system()
boost::signals2::signal< void(ParsedTools::DataOut< dim, spacedim > &)> add_data_vector
Connect to this signal to add data additional vectors to the output system.
boost::signals2::signal< void(const double &time, const double &time_step, const unsigned int &time_step_number)> advance_time_call_back
Connect to this signal to receive time information.
const std::string component_names
Comma seperated names of components.
const unsigned int n_components
Number of components.
const std::string problem_name
Name of the problem to solve.
const std::string section_name
Name of the section to use within the parameter file.
MPI_Comm mpi_communicator
Global mpi communicator.
const unsigned int mpi_rank
The mpi rank of this process.
const unsigned int mpi_size
The number of mpi processes.
int number_of_threads
Number of threads to use for multi-threaded assembly.
unsigned int verbosity_level
Verbosity level of deallog.
TimerOutput timer
Timing information.
EvolutionType evolution_type
Describe the type of time evolution of the problem.
ParsedTools::GridGenerator< dim, spacedim > grid_generator
A wrapper around GridIn, GridOut, and GridGenerator namespace.
ParsedTools::GridRefinement grid_refinement
Grid refinement and error estimation.
Triangulation triangulation
The problem triangulation.
ParsedTools::FiniteElement< dim, spacedim > finite_element
A wrapper around deal.II FiniteElement classes.
std::unique_ptr< Mapping< dim, spacedim > > mapping
The Mapping between reference and real elements.
Quadrature< dim > cell_quadrature
A quadrature used for cell integration.
Quadrature< dim - 1 > face_quadrature
A quadrature used for face integration.
DoFHandler< dim, spacedim > dof_handler
Handler of degrees of freedom.
AffineConstraints< double > constraints
Hanging nodes and essential boundary conditions.
std::vector< types::global_dof_index > dofs_per_block
Dofs per block.
std::vector< IndexSet > locally_owned_dofs
All degrees of freedom owned by this MPI process.
std::vector< IndexSet > locally_relevant_dofs
All degrees of freedom needed for output and error estimation.
LacType::BlockSparsityPattern sparsity
System sparsity pattern.
LacType::BlockSparseMatrix matrix
System matrix.
LacType::BlockSparseMatrix mass_matrix
System matrix.
LacType::BlockVector locally_relevant_solution
A read only copy of the solution vector used for output and error estimation.
LacType::BlockVector solution
Solution vector.
LacType::BlockVector rhs
The system right hand side.
Vector< float > error_per_cell
Storage for local error estimator.
ParsedLAC::InverseOperator inverse_operator
Inverse operator.
LacType::AMG preconditioner
Preconditioner.
ParsedLAC::InverseOperator mass_inverse_operator
Inverse operator for the mass matrix.
LacType::AMG mass_preconditioner
Preconditioner for the mass matrix.
ParsedTools::Function< spacedim > forcing_term
The actual function to use as a forcing term.
ParsedTools::Function< spacedim > exact_solution
The actual function to use as a exact solution when computing the errors.
ParsedTools::Function< spacedim > initial_value
Only used for transient problems.
ParsedTools::BoundaryConditions< spacedim > boundary_conditions
Boundary conditions used in this class.
ParsedTools::ConvergenceTable error_table
This is a wrapper around the ParsedConvergenceTable class, that allows you to specify what error to computes, and how to compute them.
ParsedTools::DataOut< dim, spacedim > data_out
Wrapper around the DataOut class.
double start_time
Initial time for transient and quasi stati simulations.
double end_time
Final time for transient and quasi-static simulations.
double desired_start_step_size
Initial step size for transient and quasi-static simulations.
unsigned int output_frequency
How often to output the solution.
ParsedTools::Proxy< typename SUNDIALS::ARKode< typename LacType::BlockVector >::AdditionalData > ark_ode_data
Configuration used to setup transient simulations.
boost::signals2::signal< void(ARKode &)> setup_arkode_call_back
Signal that is triggered after creating the arkode object.
Public Attributes inherited from ParameterAcceptor
boost::signals2::signal< void()> declare_parameters_call_back
boost::signals2::signal< void()> parse_parameters_call_back
Static Public Attributes inherited from PDEs::LinearProblem< dim, dim, LacType >
static constexpr bool lac_is_dealii
True if we are using deal.II Linear Algebra Classes.
static constexpr bool lac_is_petsc
True if we are using PETSc Linear Algebra Classes.
static constexpr bool lac_is_trilinos
True if we are using Trilinos Linear Algebra Classes.
Static Public Attributes inherited from ParameterAcceptor
static ParameterHandler prm
Detailed Description
template<int dim, class LacType>
class PDEs::Stokes< dim, LacType >
Solve the Stokes problem, in parallel.
Definition at line 32 of file stokes.h.
Member Typedef Documentation
ScratchData
template<int dim, class LacType > using PDEs::Stokes< dim, LacType >::ScratchData = typename LinearProblem<dim, dim, LacType>::ScratchData
Definition at line 46 of file stokes.h.
CopyData
template<int dim, class LacType > using PDEs::Stokes< dim, LacType >::CopyData = typename LinearProblem<dim, dim, LacType>::CopyData
Definition at line 48 of file stokes.h.
VectorType
template<int dim, class LacType > using PDEs::Stokes< dim, LacType >::VectorType = typename LinearProblem<dim, dim, LacType>::VectorType
Definition at line 50 of file stokes.h.
Constructor & Destructor Documentation
Stokes()
template<int dim, class LacType > PDEs::Stokes< dim, LacType >::Stokes
Constructor.
Initialize all parameters, including the base class, and make sure the class is ready to run.
Definition at line 29 of file stokes.cc.
~Stokes()
template<int dim, class LacType > virtual PDEs::Stokes< dim, LacType >::~Stokes () virtual default
Destroy the Stokes object.
Member Function Documentation
assemble_system_one_cell()
template<int dim, class LacType > void PDEs::Stokes< dim, LacType >::assemble_system_one_cell (const typename DoFHandler< dim >::active_cell_iterator & cell, ScratchData & scratch, CopyData & copy) override protected virtual
Explicitly assemble the Stokes problem on a single cell.
Definition at line 75 of file stokes.cc.
References cell_matrix(), copy(), DoFHandler< dim, spacedim >::reinit(), and scalar_product().
solve()
template<int dim, class LacType > void PDEs::Stokes< dim, LacType >::solve override protected virtual
Make sure we initialize the right type of linear solver.
Reimplemented from PDEs::LinearProblem< dim, dim, LacType >.
Definition at line 127 of file stokes.cc.
References b(), begin(), block_forward_substitution(), deallog, end(), DoFTools::extract_constant_modes(), inverse_operator(), and matrix.
Member Data Documentation
constants
template<int dim, class LacType > ParsedTools::Constants PDEs::Stokes< dim, LacType >::constants protected
Definition at line 68 of file stokes.h.
schur_preconditioner
template<int dim, class LacType > LacType::AMG PDEs::Stokes< dim, LacType >::schur_preconditioner protected
Definition at line 69 of file stokes.h.
schur_solver
template<int dim, class LacType > ParsedLAC::InverseOperator PDEs::Stokes< dim, LacType >::schur_solver protected
Definition at line 70 of file stokes.h.
velocity
template<int dim, class LacType > const FEValuesExtractors::Vector PDEs::Stokes< dim, LacType >::velocity protected
Definition at line 73 of file stokes.h.
pressure
template<int dim, class LacType > const FEValuesExtractors::Scalar PDEs::Stokes< dim, LacType >::pressure protected
Definition at line 74 of file stokes.h.
The documentation for this class was generated from the following files:
include/pdes/stokes.h
source/pdes/stokes.cc