Fluid structure interaction suite: dealii::Patterns::UnsignedInteger Class Reference
dealii::Patterns::UnsignedInteger Class Reference
#include <patterns_unsigned_int.h>
Public Member Functions
UnsignedInteger (const unsigned int lower_bound=min_int_value, const unsigned int upper_bound=max_int_value)
virtual bool match (const std::string &test_string) const override
virtual std::string description (const OutputStyle style=Machine) const override
virtual std::unique_ptr< PatternBase > clone () const override
Static Public Member Functions
static std::unique_ptr< UnsignedInteger > create (const std::string &description)
Static Public Attributes
static const unsigned int min_int_value
static const unsigned int max_int_value
Private Attributes
const unsigned int lower_bound
const unsigned int upper_bound
Static Private Attributes
static const char * description_init = "[UnsignedInteger"
Detailed Description
Definition at line 27 of file patterns_unsigned_int.h.
Constructor & Destructor Documentation
UnsignedInteger()
dealii::Patterns::UnsignedInteger::UnsignedInteger (const unsigned int lower_bound = min_int_value, const unsigned int upper_bound = max_int_value)
Definition at line 30 of file patterns_unsigned_int.cc.
References lower_bound().
Referenced by clone().
Member Function Documentation
match()
bool dealii::Patterns::UnsignedInteger::match (const std::string & test_string) const override virtual
Definition at line 38 of file patterns_unsigned_int.cc.
References lower_bound, and upper_bound.
description()
std::string dealii::Patterns::UnsignedInteger::description (const OutputStyle style = Machine) const override virtual
Definition at line 60 of file patterns_unsigned_int.cc.
References AssertThrow, description_init, ExcNotImplemented(), lower_bound, and upper_bound.
Referenced by create().
clone()
std::unique_ptr< PatternBase > dealii::Patterns::UnsignedInteger::clone () const override virtual
Definition at line 122 of file patterns_unsigned_int.cc.
References lower_bound, UnsignedInteger(), and upper_bound.
create()
std::unique_ptr< UnsignedInteger > dealii::Patterns::UnsignedInteger::create (const std::string & description) static
Definition at line 131 of file patterns_unsigned_int.cc.
References description(), description_init, lower_bound, and upper_bound.
Member Data Documentation
min_int_value
const unsigned int dealii::Patterns::UnsignedInteger::min_int_value static
Initial value:
=
      std::numeric_limits<unsigned int>::min()
Definition at line 30 of file patterns_unsigned_int.h.
max_int_value
const unsigned int dealii::Patterns::UnsignedInteger::max_int_value static
Initial value:
=
      std::numeric_limits<unsigned int>::max()
Definition at line 32 of file patterns_unsigned_int.h.
lower_bound
const unsigned int dealii::Patterns::UnsignedInteger::lower_bound private
Definition at line 50 of file patterns_unsigned_int.h.
Referenced by clone(), create(), description(), and match().
upper_bound
const unsigned int dealii::Patterns::UnsignedInteger::upper_bound private
Definition at line 52 of file patterns_unsigned_int.h.
Referenced by clone(), create(), description(), and match().
description_init
const char * dealii::Patterns::UnsignedInteger::description_init = "[UnsignedInteger" static private
Definition at line 54 of file patterns_unsigned_int.h.
Referenced by create(), and description().
The documentation for this class was generated from the following files:
include/parsed_tools/patterns_unsigned_int.h
source/patterns_unsigned_int.cc