Fluid structure interaction suite: ParsedTools::DataOut< dim, spacedim > Class Template Reference
ParsedTools::DataOut< dim, spacedim > Class Template Reference
#include <data_out.h>
Public Member Functions
DataOut (const std::string &section_name="", const std::string &base_name="solution", const std::string &output_format="vtu", const unsigned int &subdivisions=0, const bool &write_higher_order_cells=true, const MPI_Comm &comm=MPI_COMM_WORLD)
Construct a new DataOut object.
void attach_dof_handler (const DoFHandler< dim, spacedim > &dh, const std::string &suffix="")
Prepare to output data on the given file.
template<typename VECTOR >
void add_data_vector (const VECTOR &data_vector, const std::string &desc, const typename DataOut< dim, spacedim >::DataVectorType &type=DataOut< dim, spacedim >::type_automatic)
Add the given vector to the output file.
template<typename VECTOR >
void add_data_vector (const VECTOR &data_vector, const DataPostprocessor< spacedim > &postproc)
Wrapper for the corrisponding function in dealii.
void write_data_and_clear (const Mapping< dim, spacedim > &mapping=StaticMappingQ1< dim, spacedim >::mapping)
Actually write the file.
void clear_pvd_record ()
Resets the pvd_record.
Public Member Functions inherited from ParameterAcceptor
ParameterAcceptor (const std::string &section_name="")
virtual ~ParameterAcceptor () override
virtual void declare_parameters (ParameterHandler &prm)
virtual void parse_parameters (ParameterHandler &prm)
std::string get_section_name () const
std::vector< std::string > get_section_path () const
void add_parameter (const std::string &entry, ParameterType &parameter, const std::string &documentation="", ParameterHandler &prm_=prm, const Patterns::PatternBase &pattern=*Patterns::Tools::Convert< ParameterType >::to_pattern())
void enter_subsection (const std::string &subsection)
void leave_subsection ()
void enter_my_subsection (ParameterHandler &prm)
void leave_my_subsection (ParameterHandler &prm)
void serialize (Archive &ar, const unsigned int version)
void subscribe (std::atomic< bool > *const validity, const std::string &identifier="") const
void unsubscribe (std::atomic< bool > *const validity, const std::string &identifier="") const
unsigned int n_subscriptions () const
void list_subscribers (StreamType &stream) const
void list_subscribers () const
void subscribe (std::atomic< bool > *const validity, const std::string &identifier="") const
void unsubscribe (std::atomic< bool > *const validity, const std::string &identifier="") const
unsigned int n_subscriptions () const
void list_subscribers (StreamType &stream) const
void list_subscribers () const
Public Member Functions inherited from Subscriptor
Subscriptor ()
Subscriptor (const Subscriptor &)
Subscriptor (Subscriptor &&) noexcept
virtual ~Subscriptor ()
Subscriptor & operator= (const Subscriptor &)
Subscriptor & operator= (Subscriptor &&) noexcept
void serialize (Archive &ar, const unsigned int version)
void subscribe (std::atomic< bool > *const validity, const std::string &identifier="") const
void unsubscribe (std::atomic< bool > *const validity, const std::string &identifier="") const
unsigned int n_subscriptions () const
void list_subscribers (StreamType &stream) const
void list_subscribers () const
void subscribe (std::atomic< bool > *const validity, const std::string &identifier="") const
void unsubscribe (std::atomic< bool > *const validity, const std::string &identifier="") const
unsigned int n_subscriptions () const
void list_subscribers (StreamType &stream) const
void list_subscribers () const
Private Attributes
const std::string component_names
Initialization flag.
const MPI_Comm & comm
MPI communicator.
const unsigned int n_mpi_processes
Number of processes.
const unsigned int this_mpi_process
My mpi process.
std::string output_format
Output format.
unsigned int subdivisions
Number of subdivisions.
bool write_higher_order_cells
If available, output high order data.
std::string base_name
Base name for output files.
std::string current_directory
Folder where solutions are stored.
std::string current_filename
The name of last written filew.
std::string master_name
The name used for the master pvd file.
std::string current_name
Current output name.
bool output_partitioning
Output the partitioning of the domain.
bool output_material_ids
Output the material ids of the domain.
std::ofstream output_file
Output file.
std::unique_ptr< DataOut< dim, spacedim > > data_out
Outputs only the data that refers to this process.
DataOut< dim, spacedim >::CurvedCellRegion curved_cells_region = DataOut<dim, spacedim>::curved_inner_cells
std::vector< std::pair< double, std::string > > pvd_record
Record of all output files and times.
Additional Inherited Members
Static Public Member Functions inherited from ParameterAcceptor
static void initialize (const std::string &filename="", const std::string &output_filename="", const ParameterHandler::OutputStyle output_style_for_output_filename=ParameterHandler::Short, ParameterHandler &prm=ParameterAcceptor::prm, const ParameterHandler::OutputStyle output_style_for_filename=ParameterHandler::DefaultStyle)
static void initialize (std::istream &input_stream, ParameterHandler &prm=ParameterAcceptor::prm)
static void clear ()
static void parse_all_parameters (ParameterHandler &prm=ParameterAcceptor::prm)
static void declare_all_parameters (ParameterHandler &prm=ParameterAcceptor::prm)
static ::ExceptionBase & ExcInUse (int arg1, std::string arg2, std::string arg3)
static ::ExceptionBase & ExcNoSubscriber (std::string arg1, std::string arg2)
Static Public Member Functions inherited from Subscriptor
static ::ExceptionBase & ExcInUse (int arg1, std::string arg2, std::string arg3)
static ::ExceptionBase & ExcNoSubscriber (std::string arg1, std::string arg2)
Public Attributes inherited from ParameterAcceptor
boost::signals2::signal< void()> declare_parameters_call_back
boost::signals2::signal< void()> parse_parameters_call_back
Static Public Attributes inherited from ParameterAcceptor
static ParameterHandler prm
Protected Attributes inherited from ParameterAcceptor
const std::string section_name
std::vector< std::string > subsections
Detailed Description
template<int dim, int spacedim = dim>
class ParsedTools::DataOut< dim, spacedim >
Definition at line 39 of file data_out.h.
Constructor & Destructor Documentation
DataOut()
template<int dim, int spacedim> DataOut< dim, spacedim >::DataOut (const std::string & section_name = "", const std::string & base_name = "solution", const std::string & output_format = "vtu", const unsigned int & subdivisions = 0, const bool & write_higher_order_cells = true, const MPI_Comm & comm = MPI_COMM_WORLD)
Construct a new DataOut object.
Parameters
name
base_name
output_format
subdivisions
output_high_order
comm
Definition at line 72 of file data_out.cc.
Member Function Documentation
attach_dof_handler()
template<int dim, int spacedim> void DataOut< dim, spacedim >::attach_dof_handler (const DoFHandler< dim, spacedim > & dh, const std::string & suffix = "")
Prepare to output data on the given file.
This will initialize the data_out object and a file with a filename that is the combination of the base_name, the optional suffix, eventually a processor number and the output suffix.
Definition at line 119 of file data_out.cc.
Referenced by main().
add_data_vector() [1/2]
template<int dim, int spacedim> template<typename VECTOR > void DataOut< dim, spacedim >::add_data_vector (const VECTOR & data_vector, const std::string & desc, const typename DataOut< dim, spacedim >::DataVectorType & type = DataOut<dim, spacedim>::type_automatic)
Add the given vector to the output file.
Prior to calling this method, you have to call the attach_dof_handler() method. The string can be a comma separated list of components, or a single description. In this latter case, a progressive number per component is added in the end. In the former case, if a string is reapeated, its respective components are interepreted as components of a vector.
Definition at line 181 of file data_out.h.
Referenced by main().
add_data_vector() [2/2]
template<int dim, int spacedim> template<typename VECTOR > void DataOut< dim, spacedim >::add_data_vector (const VECTOR & data_vector, const DataPostprocessor< spacedim > & postproc)
Wrapper for the corrisponding function in dealii.
Definition at line 231 of file data_out.h.
write_data_and_clear()
template<int dim, int spacedim> void DataOut< dim, spacedim >::write_data_and_clear (const Mapping< dim, spacedim > & mapping = StaticMappingQ1<dim, spacedim>::mapping)
Actually write the file.
Once the data_out has been prepared, vectors have been added, the data can be written to a file. This is done in this method. At the end of this function call the process can be started again. used_files is an optional variable that takes a list of useful files (ex. "parameter.prm time.dat") and copies these files in the incremental_run_prefix of the costructor function.
Definition at line 194 of file data_out.cc.
Referenced by main().
clear_pvd_record()
template<int dim, int spacedim> void DataOut< dim, spacedim >::clear_pvd_record
Resets the pvd_record.
Definition at line 110 of file data_out.cc.
Member Data Documentation
component_names
template<int dim, int spacedim = dim> const std::string ParsedTools::DataOut< dim, spacedim >::component_names private
Initialization flag.
Definition at line 114 of file data_out.h.
comm
template<int dim, int spacedim = dim> const MPI_Comm& ParsedTools::DataOut< dim, spacedim >::comm private
MPI communicator.
Definition at line 117 of file data_out.h.
n_mpi_processes
template<int dim, int spacedim = dim> const unsigned int ParsedTools::DataOut< dim, spacedim >::n_mpi_processes private
Number of processes.
Definition at line 120 of file data_out.h.
this_mpi_process
template<int dim, int spacedim = dim> const unsigned int ParsedTools::DataOut< dim, spacedim >::this_mpi_process private
My mpi process.
Definition at line 123 of file data_out.h.
output_format
template<int dim, int spacedim = dim> std::string ParsedTools::DataOut< dim, spacedim >::output_format private
Output format.
Definition at line 126 of file data_out.h.
subdivisions
template<int dim, int spacedim = dim> unsigned int ParsedTools::DataOut< dim, spacedim >::subdivisions private
Number of subdivisions.
Definition at line 129 of file data_out.h.
write_higher_order_cells
template<int dim, int spacedim = dim> bool ParsedTools::DataOut< dim, spacedim >::write_higher_order_cells private
If available, output high order data.
Definition at line 132 of file data_out.h.
base_name
template<int dim, int spacedim = dim> std::string ParsedTools::DataOut< dim, spacedim >::base_name private
Base name for output files.
This base is used to generate all filenames.
Definition at line 136 of file data_out.h.
current_directory
template<int dim, int spacedim = dim> std::string ParsedTools::DataOut< dim, spacedim >::current_directory private
Folder where solutions are stored.
Definition at line 139 of file data_out.h.
current_filename
template<int dim, int spacedim = dim> std::string ParsedTools::DataOut< dim, spacedim >::current_filename private
The name of last written filew.
Definition at line 142 of file data_out.h.
master_name
template<int dim, int spacedim = dim> std::string ParsedTools::DataOut< dim, spacedim >::master_name private
The name used for the master pvd file.
Definition at line 145 of file data_out.h.
current_name
template<int dim, int spacedim = dim> std::string ParsedTools::DataOut< dim, spacedim >::current_name private
Current output name.
When preparing data_out, this name will contain the base for the current output. This allows the user to use a different output name in different part of the program.
Definition at line 150 of file data_out.h.
output_partitioning
template<int dim, int spacedim = dim> bool ParsedTools::DataOut< dim, spacedim >::output_partitioning private
Output the partitioning of the domain.
Definition at line 153 of file data_out.h.
output_material_ids
template<int dim, int spacedim = dim> bool ParsedTools::DataOut< dim, spacedim >::output_material_ids private
Output the material ids of the domain.
Definition at line 156 of file data_out.h.
output_file
template<int dim, int spacedim = dim> std::ofstream ParsedTools::DataOut< dim, spacedim >::output_file private
Output file.
Definition at line 159 of file data_out.h.
data_out
template<int dim, int spacedim = dim> std::unique_ptr<DataOut<dim, spacedim> > ParsedTools::DataOut< dim, spacedim >::data_out private
Outputs only the data that refers to this process.
Definition at line 162 of file data_out.h.
curved_cells_region
template<int dim, int spacedim = dim> DataOut<dim, spacedim>::CurvedCellRegion ParsedTools::DataOut< dim, spacedim >::curved_cells_region = DataOut<dim, spacedim>::curved_inner_cells private
Definition at line 165 of file data_out.h.
pvd_record
template<int dim, int spacedim = dim> std::vector<std::pair<double, std::string> > ParsedTools::DataOut< dim, spacedim >::pvd_record private
Record of all output files and times.
Definition at line 170 of file data_out.h.
The documentation for this class was generated from the following files:
include/parsed_tools/data_out.h
source/data_out.cc