Fluid structure interaction suite: ParsedGridGenerator< dim, spacedim > Class Template Reference
ParsedGridGenerator< dim, spacedim > Class Template Reference
#include <parsed_grid_generator.h>
Public Member Functions
ParsedGridGenerator (const std::string &prm_section_path="")
void generate (dealii::Triangulation< dim, spacedim > &tria) const
void write (const dealii::Triangulation< dim, spacedim > &tria, const std::string &filename="") const
Private Attributes
std::string grid_generator_function = "hyper_cube"
std::string grid_generator_arguments = "0: 1: false"
std::string output_file_name = ""
bool transform_to_simplex_grid = false
unsigned int initial_grid_refinement = 0
Detailed Description
template<int dim, int spacedim = dim>
class ParsedGridGenerator< dim, spacedim >
GridGenerator class
Definition at line 18 of file parsed_grid_generator.h.
Constructor & Destructor Documentation
ParsedGridGenerator()
template<int dim, int spacedim> ParsedGridGenerator< dim, spacedim >::ParsedGridGenerator (const std::string & prm_section_path = "")
Constructor. Initialize all parameters, and make sure the class is ready to run.
Definition at line 20 of file parsed_grid_generator.cc.
References ParsedGridGenerator< dim, spacedim >::grid_generator_arguments, ParsedGridGenerator< dim, spacedim >::grid_generator_function, ParsedGridGenerator< dim, spacedim >::initial_grid_refinement, ParsedGridGenerator< dim, spacedim >::output_file_name, and ParsedGridGenerator< dim, spacedim >::transform_to_simplex_grid.
Member Function Documentation
generate()
template<int dim, int spacedim> void ParsedGridGenerator< dim, spacedim >::generate (dealii::Triangulation< dim, spacedim > & tria) const
Fill a triangulation according to the parsed parameters.
Definition at line 34 of file parsed_grid_generator.cc.
References AssertThrow, GridGenerator::convert_hypercube_to_simplex_mesh(), Triangulation< dim, spacedim >::copy_triangulation(), ExcIO(), numbers::flat_manifold_id, GridGenerator::generate_from_name_and_arguments(), Triangulation< dim, spacedim >::get_manifold(), Triangulation< dim, spacedim >::get_manifold_ids(), GridIn< dim, spacedim >::read(), GridIn< dim, spacedim >::read_assimp(), GridIn< dim, spacedim >::read_msh(), and tria.
write()
template<int dim, int spacedim> void ParsedGridGenerator< dim, spacedim >::write (const dealii::Triangulation< dim, spacedim > & tria, const std::string & filename = "") const
Write the given Triangulation to the output file specified in Output file name, or in the optional file name.
If no Output file name is given and filename is the empty string, this function does nothing. If an output file name is provided (either in the input file, or as an argument to this function), then this function will call the appropriate GridOut method according to the extension of the file name.
Definition at line 155 of file parsed_grid_generator.cc.
References Assert, AssertThrow, ExcIO(), ExcNotImplemented(), GridOut::set_flags(), tria, GridOut::write_msh(), GridOut::write_ucd(), GridOut::write_vtk(), and GridOut::write_vtu().
Member Data Documentation
grid_generator_arguments
template<int dim, int spacedim = dim> std::string ParsedGridGenerator< dim, spacedim >::grid_generator_arguments = "0: 1: false" private
Definition at line 49 of file parsed_grid_generator.h.
Referenced by ParsedGridGenerator< dim, spacedim >::ParsedGridGenerator().
grid_generator_function
template<int dim, int spacedim = dim> std::string ParsedGridGenerator< dim, spacedim >::grid_generator_function = "hyper_cube" private
Definition at line 48 of file parsed_grid_generator.h.
Referenced by ParsedGridGenerator< dim, spacedim >::ParsedGridGenerator().
initial_grid_refinement
template<int dim, int spacedim = dim> unsigned int ParsedGridGenerator< dim, spacedim >::initial_grid_refinement = 0 private
Definition at line 52 of file parsed_grid_generator.h.
Referenced by ParsedGridGenerator< dim, spacedim >::ParsedGridGenerator().
output_file_name
template<int dim, int spacedim = dim> std::string ParsedGridGenerator< dim, spacedim >::output_file_name = "" private
Definition at line 50 of file parsed_grid_generator.h.
Referenced by ParsedGridGenerator< dim, spacedim >::ParsedGridGenerator().
transform_to_simplex_grid
template<int dim, int spacedim = dim> bool ParsedGridGenerator< dim, spacedim >::transform_to_simplex_grid = false private
Definition at line 51 of file parsed_grid_generator.h.
Referenced by ParsedGridGenerator< dim, spacedim >::ParsedGridGenerator().
The documentation for this class was generated from the following files:
/github/workspace/include/parsed_grid_generator.h
/github/workspace/source/parsed_grid_generator.cc