Fluid structure interaction suite: PDEs::Serial::LinearElasticity< dim, spacedim > Class Template Reference
PDEs::Serial::LinearElasticity< dim, spacedim > Class Template Reference
#include <linear_elasticity.h>
Public Member Functions
LinearElasticity ()
void run ()
Public Member Functions inherited from ParameterAcceptor
ParameterAcceptor (const std::string &section_name="")
virtual ~ParameterAcceptor () override
virtual void declare_parameters (ParameterHandler &prm)
virtual void parse_parameters (ParameterHandler &prm)
std::string get_section_name () const
std::vector< std::string > get_section_path () const
void add_parameter (const std::string &entry, ParameterType &parameter, const std::string &documentation="", ParameterHandler &prm_=prm, const Patterns::PatternBase &pattern=*Patterns::Tools::Convert< ParameterType >::to_pattern())
void enter_subsection (const std::string &subsection)
void leave_subsection ()
void enter_my_subsection (ParameterHandler &prm)
void leave_my_subsection (ParameterHandler &prm)
void serialize (Archive &ar, const unsigned int version)
void subscribe (std::atomic< bool > *const validity, const std::string &identifier="") const
void unsubscribe (std::atomic< bool > *const validity, const std::string &identifier="") const
unsigned int n_subscriptions () const
void list_subscribers (StreamType &stream) const
void list_subscribers () const
void subscribe (std::atomic< bool > *const validity, const std::string &identifier="") const
void unsubscribe (std::atomic< bool > *const validity, const std::string &identifier="") const
unsigned int n_subscriptions () const
void list_subscribers (StreamType &stream) const
void list_subscribers () const
Public Member Functions inherited from Subscriptor
Subscriptor ()
Subscriptor (const Subscriptor &)
Subscriptor (Subscriptor &&) noexcept
virtual ~Subscriptor ()
Subscriptor & operator= (const Subscriptor &)
Subscriptor & operator= (Subscriptor &&) noexcept
void serialize (Archive &ar, const unsigned int version)
void subscribe (std::atomic< bool > *const validity, const std::string &identifier="") const
void unsubscribe (std::atomic< bool > *const validity, const std::string &identifier="") const
unsigned int n_subscriptions () const
void list_subscribers (StreamType &stream) const
void list_subscribers () const
void subscribe (std::atomic< bool > *const validity, const std::string &identifier="") const
void unsubscribe (std::atomic< bool > *const validity, const std::string &identifier="") const
unsigned int n_subscriptions () const
void list_subscribers (StreamType &stream) const
void list_subscribers () const
Protected Member Functions
void setup_system ()
void assemble_system ()
void solve ()
void output_results (const unsigned cycle) const
Protected Attributes
const std::string component_names
How we identify the component names.
ParsedTools::GridGenerator< dim, spacedim > grid_generator
ParsedTools::GridRefinement grid_refinement
Triangulation< dim, spacedim > triangulation
ParsedTools::FiniteElement< dim, spacedim > finite_element
DoFHandler< dim, spacedim > dof_handler
std::unique_ptr< Mapping< dim, spacedim > > mapping
AffineConstraints< double > constraints
SparsityPattern sparsity_pattern
SparseMatrix< double > system_matrix
Vector< double > solution
Vector< double > system_rhs
ParsedLAC::InverseOperator inverse_operator
ParsedLAC::AMGPreconditioner preconditioner
ParsedTools::Constants constants
ParsedTools::Function< spacedim > forcing_term
ParsedTools::Function< spacedim > exact_solution
ParsedTools::BoundaryConditions< spacedim > boundary_conditions
ParsedConvergenceTable error_table
ParsedTools::DataOut< dim, spacedim > data_out
unsigned int console_level = 1
const FEValuesExtractors::Vector displacement
Protected Attributes inherited from ParameterAcceptor
const std::string section_name
std::vector< std::string > subsections
Additional Inherited Members
Static Public Member Functions inherited from ParameterAcceptor
static void initialize (const std::string &filename="", const std::string &output_filename="", const ParameterHandler::OutputStyle output_style_for_output_filename=ParameterHandler::Short, ParameterHandler &prm=ParameterAcceptor::prm, const ParameterHandler::OutputStyle output_style_for_filename=ParameterHandler::DefaultStyle)
static void initialize (std::istream &input_stream, ParameterHandler &prm=ParameterAcceptor::prm)
static void clear ()
static void parse_all_parameters (ParameterHandler &prm=ParameterAcceptor::prm)
static void declare_all_parameters (ParameterHandler &prm=ParameterAcceptor::prm)
static ::ExceptionBase & ExcInUse (int arg1, std::string arg2, std::string arg3)
static ::ExceptionBase & ExcNoSubscriber (std::string arg1, std::string arg2)
Static Public Member Functions inherited from Subscriptor
static ::ExceptionBase & ExcInUse (int arg1, std::string arg2, std::string arg3)
static ::ExceptionBase & ExcNoSubscriber (std::string arg1, std::string arg2)
Public Attributes inherited from ParameterAcceptor
boost::signals2::signal< void()> declare_parameters_call_back
boost::signals2::signal< void()> parse_parameters_call_back
Static Public Attributes inherited from ParameterAcceptor
static ParameterHandler prm
Detailed Description
template<int dim, int spacedim = dim>
class PDEs::Serial::LinearElasticity< dim, spacedim >
Definition at line 86 of file linear_elasticity.h.
Constructor & Destructor Documentation
LinearElasticity()
template<int dim, int spacedim> PDEs::Serial::LinearElasticity< dim, spacedim >::LinearElasticity
Definition at line 29 of file linear_elasticity.cc.
Member Function Documentation
run()
template<int dim, int spacedim> void PDEs::Serial::LinearElasticity< dim, spacedim >::run
Definition at line 237 of file linear_elasticity.cc.
References deallog, LogStream::depth_console(), Utilities::int_to_string(), LogStream::pop(), LogStream::push(), and triangulation.
Referenced by main().
setup_system()
template<int dim, int spacedim> void PDEs::Serial::LinearElasticity< dim, spacedim >::setup_system protected
Definition at line 74 of file linear_elasticity.cc.
References AssertThrow, deallog, ExcMessage(), get_default_linear_mapping(), DoFTools::make_hanging_node_constraints(), DoFTools::make_sparsity_pattern(), reference_cell(), and triangulation.
assemble_system()
template<int dim, int spacedim> void PDEs::Serial::LinearElasticity< dim, spacedim >::assemble_system protected
Definition at line 121 of file linear_elasticity.cc.
References cell_matrix(), deallog, FEValues< dim, spacedim >::dof_indices(), ReferenceCell::face_reference_cell(), first, ReferenceCell::get_gauss_type_quadrature(), FEValues< dim, spacedim >::JxW(), local_dof_indices, FEValues< dim, spacedim >::quadrature_point(), FEValues< dim, spacedim >::quadrature_point_indices(), FEValues< dim, spacedim >::reinit(), FEValues< dim, spacedim >::shape_value(), update_gradients, update_JxW_values, update_quadrature_points, and update_values.
solve()
template<int dim, int spacedim> void PDEs::Serial::LinearElasticity< dim, spacedim >::solve protected
Definition at line 206 of file linear_elasticity.cc.
References deallog, and inverse_operator().
output_results()
template<int dim, int spacedim> void PDEs::Serial::LinearElasticity< dim, spacedim >::output_results (const unsigned cycle) const protected
Definition at line 220 of file linear_elasticity.cc.
References deallog, Utilities::int_to_string(), and Utilities::needed_digits().
Member Data Documentation
component_names
template<int dim, int spacedim = dim> const std::string PDEs::Serial::LinearElasticity< dim, spacedim >::component_names protected
How we identify the component names.
Definition at line 110 of file linear_elasticity.h.
grid_generator
template<int dim, int spacedim = dim> ParsedTools::GridGenerator<dim, spacedim> PDEs::Serial::LinearElasticity< dim, spacedim >::grid_generator protected
Definition at line 113 of file linear_elasticity.h.
grid_refinement
template<int dim, int spacedim = dim> ParsedTools::GridRefinement PDEs::Serial::LinearElasticity< dim, spacedim >::grid_refinement protected
Definition at line 114 of file linear_elasticity.h.
triangulation
template<int dim, int spacedim = dim> Triangulation<dim, spacedim> PDEs::Serial::LinearElasticity< dim, spacedim >::triangulation protected
Definition at line 115 of file linear_elasticity.h.
finite_element
template<int dim, int spacedim = dim> ParsedTools::FiniteElement<dim, spacedim> PDEs::Serial::LinearElasticity< dim, spacedim >::finite_element protected
Definition at line 118 of file linear_elasticity.h.
dof_handler
template<int dim, int spacedim = dim> DoFHandler<dim, spacedim> PDEs::Serial::LinearElasticity< dim, spacedim >::dof_handler protected
Definition at line 119 of file linear_elasticity.h.
mapping
template<int dim, int spacedim = dim> std::unique_ptr<Mapping<dim, spacedim> > PDEs::Serial::LinearElasticity< dim, spacedim >::mapping protected
Definition at line 120 of file linear_elasticity.h.
constraints
template<int dim, int spacedim = dim> AffineConstraints<double> PDEs::Serial::LinearElasticity< dim, spacedim >::constraints protected
Definition at line 123 of file linear_elasticity.h.
sparsity_pattern
template<int dim, int spacedim = dim> SparsityPattern PDEs::Serial::LinearElasticity< dim, spacedim >::sparsity_pattern protected
Definition at line 124 of file linear_elasticity.h.
system_matrix
template<int dim, int spacedim = dim> SparseMatrix<double> PDEs::Serial::LinearElasticity< dim, spacedim >::system_matrix protected
Definition at line 125 of file linear_elasticity.h.
solution
template<int dim, int spacedim = dim> Vector<double> PDEs::Serial::LinearElasticity< dim, spacedim >::solution protected
Definition at line 126 of file linear_elasticity.h.
system_rhs
template<int dim, int spacedim = dim> Vector<double> PDEs::Serial::LinearElasticity< dim, spacedim >::system_rhs protected
Definition at line 127 of file linear_elasticity.h.
inverse_operator
template<int dim, int spacedim = dim> ParsedLAC::InverseOperator PDEs::Serial::LinearElasticity< dim, spacedim >::inverse_operator protected
Definition at line 128 of file linear_elasticity.h.
preconditioner
template<int dim, int spacedim = dim> ParsedLAC::AMGPreconditioner PDEs::Serial::LinearElasticity< dim, spacedim >::preconditioner protected
Definition at line 129 of file linear_elasticity.h.
constants
template<int dim, int spacedim = dim> ParsedTools::Constants PDEs::Serial::LinearElasticity< dim, spacedim >::constants protected
Definition at line 132 of file linear_elasticity.h.
forcing_term
template<int dim, int spacedim = dim> ParsedTools::Function<spacedim> PDEs::Serial::LinearElasticity< dim, spacedim >::forcing_term protected
Definition at line 133 of file linear_elasticity.h.
exact_solution
template<int dim, int spacedim = dim> ParsedTools::Function<spacedim> PDEs::Serial::LinearElasticity< dim, spacedim >::exact_solution protected
Definition at line 134 of file linear_elasticity.h.
boundary_conditions
template<int dim, int spacedim = dim> ParsedTools::BoundaryConditions<spacedim> PDEs::Serial::LinearElasticity< dim, spacedim >::boundary_conditions protected
Definition at line 135 of file linear_elasticity.h.
error_table
template<int dim, int spacedim = dim> ParsedConvergenceTable PDEs::Serial::LinearElasticity< dim, spacedim >::error_table protected
Definition at line 138 of file linear_elasticity.h.
data_out
template<int dim, int spacedim = dim> ParsedTools::DataOut<dim, spacedim> PDEs::Serial::LinearElasticity< dim, spacedim >::data_out mutable protected
Definition at line 141 of file linear_elasticity.h.
console_level
template<int dim, int spacedim = dim> unsigned int PDEs::Serial::LinearElasticity< dim, spacedim >::console_level = 1 protected
Definition at line 144 of file linear_elasticity.h.
displacement
template<int dim, int spacedim = dim> const FEValuesExtractors::Vector PDEs::Serial::LinearElasticity< dim, spacedim >::displacement protected
Definition at line 147 of file linear_elasticity.h.
The documentation for this class was generated from the following files:
include/pdes/serial/linear_elasticity.h
source/pdes/serial/linear_elasticity.cc