Fluid structure interaction suite: PDEs::Serial::Stokes< dim > Class Template Reference
PDEs::Serial::Stokes< dim > Class Template Reference
#include <stokes.h>
Public Member Functions
Stokes ()
void run ()
Public Member Functions inherited from ParameterAcceptor
ParameterAcceptor (const std::string &section_name="")
virtual ~ParameterAcceptor () override
virtual void declare_parameters (ParameterHandler &prm)
virtual void parse_parameters (ParameterHandler &prm)
std::string get_section_name () const
std::vector< std::string > get_section_path () const
void add_parameter (const std::string &entry, ParameterType &parameter, const std::string &documentation="", ParameterHandler &prm_=prm, const Patterns::PatternBase &pattern=*Patterns::Tools::Convert< ParameterType >::to_pattern())
void enter_subsection (const std::string &subsection)
void leave_subsection ()
void enter_my_subsection (ParameterHandler &prm)
void leave_my_subsection (ParameterHandler &prm)
void serialize (Archive &ar, const unsigned int version)
void subscribe (std::atomic< bool > *const validity, const std::string &identifier="") const
void unsubscribe (std::atomic< bool > *const validity, const std::string &identifier="") const
unsigned int n_subscriptions () const
void list_subscribers (StreamType &stream) const
void list_subscribers () const
void subscribe (std::atomic< bool > *const validity, const std::string &identifier="") const
void unsubscribe (std::atomic< bool > *const validity, const std::string &identifier="") const
unsigned int n_subscriptions () const
void list_subscribers (StreamType &stream) const
void list_subscribers () const
Public Member Functions inherited from Subscriptor
Subscriptor ()
Subscriptor (const Subscriptor &)
Subscriptor (Subscriptor &&) noexcept
virtual ~Subscriptor ()
Subscriptor & operator= (const Subscriptor &)
Subscriptor & operator= (Subscriptor &&) noexcept
void serialize (Archive &ar, const unsigned int version)
void subscribe (std::atomic< bool > *const validity, const std::string &identifier="") const
void unsubscribe (std::atomic< bool > *const validity, const std::string &identifier="") const
unsigned int n_subscriptions () const
void list_subscribers (StreamType &stream) const
void list_subscribers () const
void subscribe (std::atomic< bool > *const validity, const std::string &identifier="") const
void unsubscribe (std::atomic< bool > *const validity, const std::string &identifier="") const
unsigned int n_subscriptions () const
void list_subscribers (StreamType &stream) const
void list_subscribers () const
Protected Member Functions
void setup_system ()
void assemble_system ()
void solve ()
void output_results (const unsigned cycle) const
Protected Attributes
const std::string component_names
How we identify the component names.
ParsedTools::GridGenerator< dim > grid_generator
ParsedTools::GridRefinement grid_refinement
Triangulation< dim > triangulation
ParsedTools::FiniteElement< dim > finite_element
DoFHandler< dim > dof_handler
std::unique_ptr< Mapping< dim > > mapping
std::vector< types::global_dof_index > dofs_per_block
Dofs per block.
AffineConstraints< double > constraints
BlockSparsityPattern sparsity_pattern
BlockSparseMatrix< double > system_matrix
BlockVector< double > solution
BlockVector< double > system_rhs
ParsedLAC::InverseOperator inverse_operator
ParsedLAC::AMGPreconditioner velocity_preconditioner
ParsedLAC::AMGPreconditioner schur_preconditioner
ParsedTools::Constants constants
ParsedTools::Function< dim > forcing_term
ParsedTools::Function< dim > exact_solution
ParsedTools::BoundaryConditions< dim > boundary_conditions
ParsedConvergenceTable error_table
ParsedTools::DataOut< dim > data_out
unsigned int console_level = 1
const FEValuesExtractors::Vector velocity
const FEValuesExtractors::Scalar pressure
Protected Attributes inherited from ParameterAcceptor
const std::string section_name
std::vector< std::string > subsections
Additional Inherited Members
Static Public Member Functions inherited from ParameterAcceptor
static void initialize (const std::string &filename="", const std::string &output_filename="", const ParameterHandler::OutputStyle output_style_for_output_filename=ParameterHandler::Short, ParameterHandler &prm=ParameterAcceptor::prm, const ParameterHandler::OutputStyle output_style_for_filename=ParameterHandler::DefaultStyle)
static void initialize (std::istream &input_stream, ParameterHandler &prm=ParameterAcceptor::prm)
static void clear ()
static void parse_all_parameters (ParameterHandler &prm=ParameterAcceptor::prm)
static void declare_all_parameters (ParameterHandler &prm=ParameterAcceptor::prm)
static ::ExceptionBase & ExcInUse (int arg1, std::string arg2, std::string arg3)
static ::ExceptionBase & ExcNoSubscriber (std::string arg1, std::string arg2)
Static Public Member Functions inherited from Subscriptor
static ::ExceptionBase & ExcInUse (int arg1, std::string arg2, std::string arg3)
static ::ExceptionBase & ExcNoSubscriber (std::string arg1, std::string arg2)
Public Attributes inherited from ParameterAcceptor
boost::signals2::signal< void()> declare_parameters_call_back
boost::signals2::signal< void()> parse_parameters_call_back
Static Public Attributes inherited from ParameterAcceptor
static ParameterHandler prm
Detailed Description
template<int dim>
class PDEs::Serial::Stokes< dim >
Definition at line 76 of file stokes.h.
Constructor & Destructor Documentation
Stokes()
template<int dim> PDEs::Serial::Stokes< dim >::Stokes
Definition at line 31 of file stokes.cc.
Member Function Documentation
run()
template<int dim> void PDEs::Serial::Stokes< dim >::run
Definition at line 317 of file stokes.cc.
References deallog, LogStream::depth_console(), Utilities::int_to_string(), LogStream::pop(), LogStream::push(), and triangulation.
setup_system()
template<int dim> void PDEs::Serial::Stokes< dim >::setup_system protected
Definition at line 75 of file stokes.cc.
References AssertThrow, ParsedTools::Components::block_indices(), DoFRenumbering::component_wise(), DoFTools::count_dofs_per_fe_block(), deallog, ExcMessage(), get_default_linear_mapping(), DoFTools::make_hanging_node_constraints(), DoFTools::make_sparsity_pattern(), reference_cell(), and triangulation.
assemble_system()
template<int dim> void PDEs::Serial::Stokes< dim >::assemble_system protected
Definition at line 132 of file stokes.cc.
References cell_matrix(), deallog, FEValues< dim, spacedim >::dof_indices(), ReferenceCell::face_reference_cell(), first, ReferenceCell::get_gauss_type_quadrature(), FEValues< dim, spacedim >::JxW(), local_dof_indices, FEValues< dim, spacedim >::quadrature_point(), FEValues< dim, spacedim >::quadrature_point_indices(), FEValues< dim, spacedim >::reinit(), scalar_product(), FEValues< dim, spacedim >::shape_value(), update_gradients, update_JxW_values, update_quadrature_points, and update_values.
solve()
template<int dim> void PDEs::Serial::Stokes< dim >::solve protected
Definition at line 217 of file stokes.cc.
References block_back_substitution(), deallog, inverse_operator(), and linear_operator().
output_results()
template<int dim> void PDEs::Serial::Stokes< dim >::output_results (const unsigned cycle) const protected
Definition at line 300 of file stokes.cc.
References deallog, Utilities::int_to_string(), and Utilities::needed_digits().
Member Data Documentation
component_names
template<int dim> const std::string PDEs::Serial::Stokes< dim >::component_names protected
How we identify the component names.
Definition at line 100 of file stokes.h.
grid_generator
template<int dim> ParsedTools::GridGenerator<dim> PDEs::Serial::Stokes< dim >::grid_generator protected
Definition at line 103 of file stokes.h.
grid_refinement
template<int dim> ParsedTools::GridRefinement PDEs::Serial::Stokes< dim >::grid_refinement protected
Definition at line 104 of file stokes.h.
triangulation
template<int dim> Triangulation<dim> PDEs::Serial::Stokes< dim >::triangulation protected
Definition at line 105 of file stokes.h.
finite_element
template<int dim> ParsedTools::FiniteElement<dim> PDEs::Serial::Stokes< dim >::finite_element protected
Definition at line 108 of file stokes.h.
dof_handler
template<int dim> DoFHandler<dim> PDEs::Serial::Stokes< dim >::dof_handler protected
Definition at line 109 of file stokes.h.
mapping
template<int dim> std::unique_ptr<Mapping<dim> > PDEs::Serial::Stokes< dim >::mapping protected
Definition at line 110 of file stokes.h.
dofs_per_block
template<int dim> std::vector<types::global_dof_index> PDEs::Serial::Stokes< dim >::dofs_per_block protected
Dofs per block.
Definition at line 115 of file stokes.h.
constraints
template<int dim> AffineConstraints<double> PDEs::Serial::Stokes< dim >::constraints protected
Definition at line 118 of file stokes.h.
sparsity_pattern
template<int dim> BlockSparsityPattern PDEs::Serial::Stokes< dim >::sparsity_pattern protected
Definition at line 119 of file stokes.h.
system_matrix
template<int dim> BlockSparseMatrix<double> PDEs::Serial::Stokes< dim >::system_matrix protected
Definition at line 120 of file stokes.h.
solution
template<int dim> BlockVector<double> PDEs::Serial::Stokes< dim >::solution protected
Definition at line 121 of file stokes.h.
system_rhs
template<int dim> BlockVector<double> PDEs::Serial::Stokes< dim >::system_rhs protected
Definition at line 122 of file stokes.h.
inverse_operator
template<int dim> ParsedLAC::InverseOperator PDEs::Serial::Stokes< dim >::inverse_operator protected
Definition at line 123 of file stokes.h.
velocity_preconditioner
template<int dim> ParsedLAC::AMGPreconditioner PDEs::Serial::Stokes< dim >::velocity_preconditioner protected
Definition at line 124 of file stokes.h.
schur_preconditioner
template<int dim> ParsedLAC::AMGPreconditioner PDEs::Serial::Stokes< dim >::schur_preconditioner protected
Definition at line 125 of file stokes.h.
constants
template<int dim> ParsedTools::Constants PDEs::Serial::Stokes< dim >::constants protected
Definition at line 128 of file stokes.h.
forcing_term
template<int dim> ParsedTools::Function<dim> PDEs::Serial::Stokes< dim >::forcing_term protected
Definition at line 129 of file stokes.h.
exact_solution
template<int dim> ParsedTools::Function<dim> PDEs::Serial::Stokes< dim >::exact_solution protected
Definition at line 130 of file stokes.h.
boundary_conditions
template<int dim> ParsedTools::BoundaryConditions<dim> PDEs::Serial::Stokes< dim >::boundary_conditions protected
Definition at line 131 of file stokes.h.
error_table
template<int dim> ParsedConvergenceTable PDEs::Serial::Stokes< dim >::error_table protected
Definition at line 134 of file stokes.h.
data_out
template<int dim> ParsedTools::DataOut<dim> PDEs::Serial::Stokes< dim >::data_out mutable protected
Definition at line 137 of file stokes.h.
console_level
template<int dim> unsigned int PDEs::Serial::Stokes< dim >::console_level = 1 protected
Definition at line 140 of file stokes.h.
velocity
template<int dim> const FEValuesExtractors::Vector PDEs::Serial::Stokes< dim >::velocity protected
Definition at line 143 of file stokes.h.
pressure
template<int dim> const FEValuesExtractors::Scalar PDEs::Serial::Stokes< dim >::pressure protected
Definition at line 144 of file stokes.h.
The documentation for this class was generated from the following files:
include/pdes/serial/stokes.h
source/pdes/serial/stokes.cc