Fluid structure interaction suite: ParsedTools::BoundaryConditions< spacedim > Class Template Reference
ParsedTools::BoundaryConditions< spacedim > Class Template Reference
A wrapper for boundary conditions.
#include <boundary_conditions.h>
Public Member Functions
BoundaryConditions (const std::string &section_name="", const std::string &component_names="u", const std::vector< std::set< types::boundary_id >> &ids={{numbers::internal_face_boundary_id}}, const std::vector< std::string > &selected_components={"u"}, const std::vector< BoundaryConditionType > &bc_type={BoundaryConditionType::dirichlet}, const std::vector< std::string > &expressions={"0"})
Constructor.
void update_user_substitution_map (const Differentiation::SD::types::substitution_map &substitution_map)
Update the substitition map of every Functions::SymbolicFunction defined in this object.
void set_additional_function_arguments (const Differentiation::SD::types::substitution_map &arguments)
Call Functions::SymbolicFunction::set_additional_function_arguments() for every function defined in this object.
void set_time (const double &time)
Update time in each Functions::SymbolicFunction defined in this object.
template<typename Tria >
void check_consistency (const Tria &tria) const
Check that the grid is compatible with this boundary condition object, and that the boundary conditions are self consistent.
void check_consistency () const
Make sure the specified boundary conditions make sense.
template<int dim>
void apply_essential_boundary_conditions (const DoFHandler< dim, spacedim > &dof_handler, AffineConstraints< double > &constraints) const
Add essential boundary conditions computed with this object to the specified constraints.
template<int dim>
void apply_essential_boundary_conditions (const Mapping< dim, spacedim > &mapping, const DoFHandler< dim, spacedim > &dof_handler, AffineConstraints< double > &constraints) const
Add the boundary conditions computed with this object to the specified constraints for non standard mapping.
template<int dim, typename MatrixType , typename VectorType >
void apply_natural_boundary_conditions (const DoFHandler< dim, spacedim > &dof_handler, const AffineConstraints< double > &constraints, MatrixType &matrix, VectorType &rhs) const
Add natural boundary conditions computed with this object to the specified constraints, matrix, and rhs.
template<int dim, typename MatrixType , typename VectorType >
void apply_natural_boundary_conditions (const Mapping< dim, spacedim > &mapping, const DoFHandler< dim, spacedim > &dof_handler, const AffineConstraints< double > &constraints, MatrixType &matrix, VectorType &rhs) const
Same as above for non standard mapping.
Public Member Functions inherited from ParameterAcceptor
ParameterAcceptor (const std::string &section_name="")
virtual ~ParameterAcceptor () override
virtual void declare_parameters (ParameterHandler &prm)
virtual void parse_parameters (ParameterHandler &prm)
std::string get_section_name () const
std::vector< std::string > get_section_path () const
void add_parameter (const std::string &entry, ParameterType &parameter, const std::string &documentation="", ParameterHandler &prm_=prm, const Patterns::PatternBase &pattern=*Patterns::Tools::Convert< ParameterType >::to_pattern())
void enter_subsection (const std::string &subsection)
void leave_subsection ()
void enter_my_subsection (ParameterHandler &prm)
void leave_my_subsection (ParameterHandler &prm)
void serialize (Archive &ar, const unsigned int version)
void subscribe (std::atomic< bool > *const validity, const std::string &identifier="") const
void unsubscribe (std::atomic< bool > *const validity, const std::string &identifier="") const
unsigned int n_subscriptions () const
void list_subscribers (StreamType &stream) const
void list_subscribers () const
void subscribe (std::atomic< bool > *const validity, const std::string &identifier="") const
void unsubscribe (std::atomic< bool > *const validity, const std::string &identifier="") const
unsigned int n_subscriptions () const
void list_subscribers (StreamType &stream) const
void list_subscribers () const
Public Member Functions inherited from Subscriptor
Subscriptor ()
Subscriptor (const Subscriptor &)
Subscriptor (Subscriptor &&) noexcept
virtual ~Subscriptor ()
Subscriptor & operator= (const Subscriptor &)
Subscriptor & operator= (Subscriptor &&) noexcept
void serialize (Archive &ar, const unsigned int version)
void subscribe (std::atomic< bool > *const validity, const std::string &identifier="") const
void unsubscribe (std::atomic< bool > *const validity, const std::string &identifier="") const
unsigned int n_subscriptions () const
void list_subscribers (StreamType &stream) const
void list_subscribers () const
void subscribe (std::atomic< bool > *const validity, const std::string &identifier="") const
void unsubscribe (std::atomic< bool > *const validity, const std::string &identifier="") const
unsigned int n_subscriptions () const
void list_subscribers (StreamType &stream) const
void list_subscribers () const
Private Attributes
const std::string component_names
Component names of the boundary conditions.
const unsigned int n_components
Number of components of the problem.
unsigned int n_boundary_conditions
Number of boundary conditions.
std::vector< std::set< types::boundary_id > > ids
Ids on which this object applies boundary conditions.
std::vector< std::string > selected_components
Component on which to apply the boundary condition.
std::vector< BoundaryConditionType > bc_type
Type of boundary conditions.
std::vector< std::string > expressions
Expressions for the boundary conditions.
std::vector< std::unique_ptr< Functions::SymbolicFunction< spacedim > > > functions
The actual functions.
std::vector< ComponentMask > masks
Component on which to apply the boundary condition.
std::vector< Components::Type > types
Component types.
GridInfo grid_info
Information about the grid this BC applies to.
Additional Inherited Members
Static Public Member Functions inherited from ParameterAcceptor
static void initialize (const std::string &filename="", const std::string &output_filename="", const ParameterHandler::OutputStyle output_style_for_output_filename=ParameterHandler::Short, ParameterHandler &prm=ParameterAcceptor::prm, const ParameterHandler::OutputStyle output_style_for_filename=ParameterHandler::DefaultStyle)
static void initialize (std::istream &input_stream, ParameterHandler &prm=ParameterAcceptor::prm)
static void clear ()
static void parse_all_parameters (ParameterHandler &prm=ParameterAcceptor::prm)
static void declare_all_parameters (ParameterHandler &prm=ParameterAcceptor::prm)
static ::ExceptionBase & ExcInUse (int arg1, std::string arg2, std::string arg3)
static ::ExceptionBase & ExcNoSubscriber (std::string arg1, std::string arg2)
Static Public Member Functions inherited from Subscriptor
static ::ExceptionBase & ExcInUse (int arg1, std::string arg2, std::string arg3)
static ::ExceptionBase & ExcNoSubscriber (std::string arg1, std::string arg2)
Public Attributes inherited from ParameterAcceptor
boost::signals2::signal< void()> declare_parameters_call_back
boost::signals2::signal< void()> parse_parameters_call_back
Static Public Attributes inherited from ParameterAcceptor
static ParameterHandler prm
Protected Attributes inherited from ParameterAcceptor
const std::string section_name
std::vector< std::string > subsections
Detailed Description
template<int spacedim>
class ParsedTools::BoundaryConditions< spacedim >
A wrapper for boundary conditions.
This class can be used to store different types of boundary conditions, applied to different ids of the domain boundary.
Definition at line 61 of file boundary_conditions.h.
Constructor & Destructor Documentation
BoundaryConditions()
template<int spacedim> ParsedTools::BoundaryConditions< spacedim >::BoundaryConditions (const std::string & section_name = "", const std::string & component_names = "u", const std::vector< std::set< types::boundary_id >> & ids = {{numbers::internal_face_boundary_id}}, const std::vector< std::string > & selected_components = {"u"}, const std::vector< BoundaryConditionType > & bc_type = {BoundaryConditionType::dirichlet}, const std::vector< std::string > & expressions = {"0"})
Constructor.
Definition at line 30 of file boundary_conditions.cc.
Member Function Documentation
update_user_substitution_map()
template<int spacedim> void ParsedTools::BoundaryConditions< spacedim >::update_user_substitution_map (const Differentiation::SD::types::substitution_map & substitution_map)
Update the substitition map of every Functions::SymbolicFunction defined in this object.
See the documentation of Functions::SymbolicFunction::update_user_substitution_map().
Definition at line 197 of file boundary_conditions.cc.
Referenced by ParsedTools::BoundaryConditions< dim >::update_user_substitution_map().
set_additional_function_arguments()
template<int spacedim> void ParsedTools::BoundaryConditions< spacedim >::set_additional_function_arguments (const Differentiation::SD::types::substitution_map & arguments)
Call Functions::SymbolicFunction::set_additional_function_arguments() for every function defined in this object.
See the documentation of Functions::SymbolicFunction::set_additional_function_arguments().
Definition at line 209 of file boundary_conditions.cc.
Referenced by ParsedTools::BoundaryConditions< dim >::set_additional_function_arguments().
set_time()
template<int spacedim> void ParsedTools::BoundaryConditions< spacedim >::set_time (const double & time)
Update time in each Functions::SymbolicFunction defined in this object.
Definition at line 220 of file boundary_conditions.cc.
Referenced by ParsedTools::BoundaryConditions< dim >::set_time().
check_consistency() [1/2]
template<int spacedim> template<typename Tria > void ParsedTools::BoundaryConditions< spacedim >::check_consistency (const Tria & tria) const inline
Check that the grid is compatible with this boundary condition object, and that the boundary conditions are self consistent.
Definition at line 114 of file boundary_conditions.h.
check_consistency() [2/2]
template<int spacedim> void ParsedTools::BoundaryConditions< spacedim >::check_consistency
Make sure the specified boundary conditions make sense.
Do this, independently of the Triangulation this object is associated with.
Definition at line 112 of file boundary_conditions.cc.
Referenced by ParsedTools::BoundaryConditions< dim >::check_consistency().
apply_essential_boundary_conditions() [1/2]
template<int spacedim> template<int dim> void ParsedTools::BoundaryConditions< spacedim >::apply_essential_boundary_conditions (const DoFHandler< dim, spacedim > & dof_handler, AffineConstraints< double > & constraints) const
Add essential boundary conditions computed with this object to the specified constraints.
apply_essential_boundary_conditions() [2/2]
template<int spacedim> template<int dim> void ParsedTools::BoundaryConditions< spacedim >::apply_essential_boundary_conditions (const Mapping< dim, spacedim > & mapping, const DoFHandler< dim, spacedim > & dof_handler, AffineConstraints< double > & constraints) const
Add the boundary conditions computed with this object to the specified constraints for non standard mapping.
apply_natural_boundary_conditions() [1/2]
template<int spacedim> template<int dim, typename MatrixType , typename VectorType > void ParsedTools::BoundaryConditions< spacedim >::apply_natural_boundary_conditions (const DoFHandler< dim, spacedim > & dof_handler, const AffineConstraints< double > & constraints, MatrixType & matrix, VectorType & rhs) const
Add natural boundary conditions computed with this object to the specified constraints, matrix, and rhs.
Notice that constraintes must be still open before calling this function, and will be used to assemble the matrix and rhs parts of the boundary conditions.
Call this function after you have added all constraints to your constraints object. After this call, the constraints will be closed.
apply_natural_boundary_conditions() [2/2]
template<int spacedim> template<int dim, typename MatrixType , typename VectorType > void ParsedTools::BoundaryConditions< spacedim >::apply_natural_boundary_conditions (const Mapping< dim, spacedim > & mapping, const DoFHandler< dim, spacedim > & dof_handler, const AffineConstraints< double > & constraints, MatrixType & matrix, VectorType & rhs) const
Same as above for non standard mapping.
Notice that constraintes must be still open before calling this function, and will be used to assemble the matrix and rhs parts of the boundary conditions.
Call this function after you have added all constraints to your constraints object. After this call, the constraints will be closed.
Member Data Documentation
component_names
template<int spacedim> const std::string ParsedTools::BoundaryConditions< spacedim >::component_names private
Component names of the boundary conditions.
Definition at line 190 of file boundary_conditions.h.
n_components
template<int spacedim> const unsigned int ParsedTools::BoundaryConditions< spacedim >::n_components private
Number of components of the problem.
Definition at line 195 of file boundary_conditions.h.
n_boundary_conditions
template<int spacedim> unsigned int ParsedTools::BoundaryConditions< spacedim >::n_boundary_conditions mutable private
Number of boundary conditions.
Definition at line 200 of file boundary_conditions.h.
ids
template<int spacedim> std::vector<std::set<types::boundary_id> > ParsedTools::BoundaryConditions< spacedim >::ids private
Ids on which this object applies boundary conditions.
Definition at line 205 of file boundary_conditions.h.
selected_components
template<int spacedim> std::vector<std::string> ParsedTools::BoundaryConditions< spacedim >::selected_components private
Component on which to apply the boundary condition.
Definition at line 210 of file boundary_conditions.h.
bc_type
template<int spacedim> std::vector<BoundaryConditionType> ParsedTools::BoundaryConditions< spacedim >::bc_type private
Type of boundary conditions.
Definition at line 215 of file boundary_conditions.h.
expressions
template<int spacedim> std::vector<std::string> ParsedTools::BoundaryConditions< spacedim >::expressions private
Expressions for the boundary conditions.
Definition at line 220 of file boundary_conditions.h.
functions
template<int spacedim> std::vector<std::unique_ptr<Functions::SymbolicFunction<spacedim> > > ParsedTools::BoundaryConditions< spacedim >::functions private
The actual functions.
Definition at line 226 of file boundary_conditions.h.
masks
template<int spacedim> std::vector<ComponentMask> ParsedTools::BoundaryConditions< spacedim >::masks private
Component on which to apply the boundary condition.
Definition at line 231 of file boundary_conditions.h.
types
template<int spacedim> std::vector<Components::Type> ParsedTools::BoundaryConditions< spacedim >::types private
Component types.
Definition at line 236 of file boundary_conditions.h.
grid_info
template<int spacedim> GridInfo ParsedTools::BoundaryConditions< spacedim >::grid_info mutable private
Information about the grid this BC applies to.
Definition at line 242 of file boundary_conditions.h.
Referenced by ParsedTools::BoundaryConditions< dim >::check_consistency().
The documentation for this class was generated from the following files:
include/parsed_tools/boundary_conditions.h
source/boundary_conditions.cc