Fluid structure interaction suite: Tools::ParsedFunction< dim > Class Template Reference
Tools::ParsedFunction< dim > Class Template Reference
A wrapper for the FunctionParser class.
#include <parsed_function.h>
Public Member Functions
ParsedFunction (const std::string &section_name="", const std::string &expression="", const std::string &function_description="Function expression", const std::map< std::string, double > &constants={}, const std::string &variable_names=FunctionParser< dim >::default_variable_names()+",t", const double h=1e-8)
Build a ParameterAcceptor based ParsedFunction.
Public Member Functions inherited from ParameterAcceptor
ParameterAcceptor (const std::string &section_name="")
virtual ~ParameterAcceptor () override
virtual void declare_parameters (ParameterHandler &prm)
virtual void parse_parameters (ParameterHandler &prm)
std::string get_section_name () const
std::vector< std::string > get_section_path () const
void add_parameter (const std::string &entry, ParameterType &parameter, const std::string &documentation="", ParameterHandler &prm_=prm, const Patterns::PatternBase &pattern=*Patterns::Tools::Convert< ParameterType >::to_pattern())
void enter_subsection (const std::string &subsection)
void leave_subsection ()
void enter_my_subsection (ParameterHandler &prm)
void leave_my_subsection (ParameterHandler &prm)
void serialize (Archive &ar, const unsigned int version)
void subscribe (std::atomic< bool > *const validity, const std::string &identifier="") const
void unsubscribe (std::atomic< bool > *const validity, const std::string &identifier="") const
unsigned int n_subscriptions () const
void list_subscribers (StreamType &stream) const
void list_subscribers () const
void subscribe (std::atomic< bool > *const validity, const std::string &identifier="") const
void unsubscribe (std::atomic< bool > *const validity, const std::string &identifier="") const
unsigned int n_subscriptions () const
void list_subscribers (StreamType &stream) const
void list_subscribers () const
Public Member Functions inherited from Subscriptor
Subscriptor ()
Subscriptor (const Subscriptor &)
Subscriptor (Subscriptor &&) noexcept
virtual ~Subscriptor ()
Subscriptor & operator= (const Subscriptor &)
Subscriptor & operator= (Subscriptor &&) noexcept
void serialize (Archive &ar, const unsigned int version)
void subscribe (std::atomic< bool > *const validity, const std::string &identifier="") const
void unsubscribe (std::atomic< bool > *const validity, const std::string &identifier="") const
unsigned int n_subscriptions () const
void list_subscribers (StreamType &stream) const
void list_subscribers () const
void subscribe (std::atomic< bool > *const validity, const std::string &identifier="") const
void unsubscribe (std::atomic< bool > *const validity, const std::string &identifier="") const
unsigned int n_subscriptions () const
void list_subscribers (StreamType &stream) const
void list_subscribers () const
Public Member Functions inherited from FunctionParser< dim >
FunctionParser (const unsigned int n_components=1, const double initial_time=0.0, const double h=1e-8)
FunctionParser (const std::string &expression, const std::string &constants="", const std::string &variable_names=default_variable_names()+",t", const double h=1e-8)
FunctionParser (const FunctionParser &)=delete
FunctionParser (FunctionParser &&)=delete
virtual ~FunctionParser () override
FunctionParser & operator= (const FunctionParser &)=delete
FunctionParser & operator= (FunctionParser &&)=delete
void initialize (const std::string &vars, const std::vector< std::string > &expressions, const ConstMap &constants, const bool time_dependent=false)
void initialize (const std::string &vars, const std::string &expression, const ConstMap &constants, const bool time_dependent=false)
virtual double value (const Point< dim > &p, const unsigned int component=0) const override
virtual void vector_value (const Point< dim > &p, Vector< double > &values) const override
const std::vector< std::string > & get_expressions () const
void set_formula (const DifferenceFormula formula=Euler)
void set_h (const double h)
virtual Tensor< 1, dim > gradient (const Point< dim > &p, const unsigned int component=0) const override
virtual void vector_gradient (const Point< dim > &p, std::vector< Tensor< 1, dim >> &gradients) const override
virtual void vector_gradient (const Point< dim > &p, std::vector< Tensor< 1, dim, double >> &gradients) const
virtual void gradient_list (const std::vector< Point< dim >> &points, std::vector< Tensor< 1, dim >> &gradients, const unsigned int component=0) const override
virtual void gradient_list (const std::vector< Point< dim >> &points, std::vector< Tensor< 1, dim, double >> &gradients, const unsigned int component=0) const
virtual void vector_gradient_list (const std::vector< Point< dim >> &points, std::vector< std::vector< Tensor< 1, dim >>> &gradients) const override
virtual void vector_gradient_list (const std::vector< Point< dim >> &points, std::vector< std::vector< Tensor< 1, dim, double >>> &gradients) const
virtual void value_list (const std::vector< Point< dim >> &points, std::vector< double > &values, const unsigned int component=0) const
virtual void vector_value_list (const std::vector< Point< dim >> &points, std::vector< Vector< double >> &values) const
virtual void vector_values (const std::vector< Point< dim >> &points, std::vector< std::vector< double >> &values) const
virtual void vector_gradients (const std::vector< Point< dim >> &points, std::vector< std::vector< Tensor< 1, dim, double >>> &gradients) const
virtual double laplacian (const Point< dim > &p, const unsigned int component=0) const
virtual void vector_laplacian (const Point< dim > &p, Vector< double > &values) const
virtual void laplacian_list (const std::vector< Point< dim >> &points, std::vector< double > &values, const unsigned int component=0) const
virtual void vector_laplacian_list (const std::vector< Point< dim >> &points, std::vector< Vector< double >> &values) const
virtual SymmetricTensor< 2, dim, double > hessian (const Point< dim > &p, const unsigned int component=0) const
virtual void vector_hessian (const Point< dim > &p, std::vector< SymmetricTensor< 2, dim, double >> &values) const
virtual void hessian_list (const std::vector< Point< dim >> &points, std::vector< SymmetricTensor< 2, dim, double >> &values, const unsigned int component=0) const
virtual void vector_hessian_list (const std::vector< Point< dim >> &points, std::vector< std::vector< SymmetricTensor< 2, dim, double >>> &values) const
virtual std::size_t memory_consumption () const
Number get_time () const
virtual void set_time (const Number new_time)
virtual void advance_time (const Number delta_t)
void serialize (Archive &ar, const unsigned int version)
void subscribe (std::atomic< bool > *const validity, const std::string &identifier="") const
void unsubscribe (std::atomic< bool > *const validity, const std::string &identifier="") const
unsigned int n_subscriptions () const
void list_subscribers (StreamType &stream) const
void list_subscribers () const
void subscribe (std::atomic< bool > *const validity, const std::string &identifier="") const
void unsubscribe (std::atomic< bool > *const validity, const std::string &identifier="") const
unsigned int n_subscriptions () const
void list_subscribers (StreamType &stream) const
void list_subscribers () const
Public Member Functions inherited from AutoDerivativeFunction< dim >
AutoDerivativeFunction (const double h, const unsigned int n_components=1, const double initial_time=0.0)
virtual ~AutoDerivativeFunction () override=default
void set_formula (const DifferenceFormula formula=Euler)
void set_h (const double h)
Number get_time () const
void serialize (Archive &ar, const unsigned int version)
void subscribe (std::atomic< bool > *const validity, const std::string &identifier="") const
void unsubscribe (std::atomic< bool > *const validity, const std::string &identifier="") const
unsigned int n_subscriptions () const
void list_subscribers (StreamType &stream) const
void list_subscribers () const
void subscribe (std::atomic< bool > *const validity, const std::string &identifier="") const
void unsubscribe (std::atomic< bool > *const validity, const std::string &identifier="") const
unsigned int n_subscriptions () const
void list_subscribers (StreamType &stream) const
void list_subscribers () const
Public Member Functions inherited from Function< dim >
Function (const unsigned int n_components=1, const time_type initial_time=0.0)
Function (const Function &f)=default
virtual ~Function () override=0
Function & operator= (const Function &f)
Number get_time () const
void serialize (Archive &ar, const unsigned int version)
void subscribe (std::atomic< bool > *const validity, const std::string &identifier="") const
void unsubscribe (std::atomic< bool > *const validity, const std::string &identifier="") const
unsigned int n_subscriptions () const
void list_subscribers (StreamType &stream) const
void list_subscribers () const
void subscribe (std::atomic< bool > *const validity, const std::string &identifier="") const
void unsubscribe (std::atomic< bool > *const validity, const std::string &identifier="") const
unsigned int n_subscriptions () const
void list_subscribers (StreamType &stream) const
void list_subscribers () const
Public Member Functions inherited from FunctionTime< Number >
FunctionTime (const Number initial_time=Number(0.0))
virtual ~FunctionTime ()=default
Number get_time () const
Private Attributes
std::string expression
The actual FunctionParser expression.
const std::map< std::string, double > local_constants
A local copy of the object passed at constructor, used as a reference for the actual constants when the constructor is called with a rvalue_reference.
const std::map< std::string, double > & constants
Constants that can be used in the expression.
const std::string variable_names
Keep variable names around to re-initialize the FunctionParser class.
Additional Inherited Members
Public Types inherited from FunctionParser< dim >
enum DifferenceFormula
typedef std::map< std::string, double > ConstMap
typedef typename FunctionTime< typename numbers::NumberTraits< double >::real_type >::time_type time_type
Public Types inherited from AutoDerivativeFunction< dim >
enum DifferenceFormula
typedef typename FunctionTime< typename numbers::NumberTraits< double >::real_type >::time_type time_type
Public Types inherited from Function< dim >
typedef typename FunctionTime< typename numbers::NumberTraits< double >::real_type >::time_type time_type
Public Types inherited from FunctionTime< Number >
typedef Number time_type
Static Public Member Functions inherited from ParameterAcceptor
static void initialize (const std::string &filename="", const std::string &output_filename="", const ParameterHandler::OutputStyle output_style_for_output_filename=ParameterHandler::Short, ParameterHandler &prm=ParameterAcceptor::prm, const ParameterHandler::OutputStyle output_style_for_filename=ParameterHandler::DefaultStyle)
static void initialize (std::istream &input_stream, ParameterHandler &prm=ParameterAcceptor::prm)
static void clear ()
static void parse_all_parameters (ParameterHandler &prm=ParameterAcceptor::prm)
static void declare_all_parameters (ParameterHandler &prm=ParameterAcceptor::prm)
static ::ExceptionBase & ExcInUse (int arg1, std::string arg2, std::string arg3)
static ::ExceptionBase & ExcNoSubscriber (std::string arg1, std::string arg2)
Static Public Member Functions inherited from Subscriptor
static ::ExceptionBase & ExcInUse (int arg1, std::string arg2, std::string arg3)
static ::ExceptionBase & ExcNoSubscriber (std::string arg1, std::string arg2)
Static Public Member Functions inherited from FunctionParser< dim >
static std::string default_variable_names ()
static ::ExceptionBase & ExcParseError (int arg1, std::string arg2)
static ::ExceptionBase & ExcInvalidExpressionSize (int arg1, int arg2)
static DifferenceFormula get_formula_of_order (const unsigned int ord)
static ::ExceptionBase & ExcInUse (int arg1, std::string arg2, std::string arg3)
static ::ExceptionBase & ExcNoSubscriber (std::string arg1, std::string arg2)
Static Public Member Functions inherited from AutoDerivativeFunction< dim >
static DifferenceFormula get_formula_of_order (const unsigned int ord)
static ::ExceptionBase & ExcInUse (int arg1, std::string arg2, std::string arg3)
static ::ExceptionBase & ExcNoSubscriber (std::string arg1, std::string arg2)
Static Public Member Functions inherited from Function< dim >
static ::ExceptionBase & ExcInUse (int arg1, std::string arg2, std::string arg3)
static ::ExceptionBase & ExcNoSubscriber (std::string arg1, std::string arg2)
Public Attributes inherited from ParameterAcceptor
boost::signals2::signal< void()> declare_parameters_call_back
boost::signals2::signal< void()> parse_parameters_call_back
Public Attributes inherited from FunctionParser< dim >
Euler
UpwindEuler
FourthOrder
const unsigned int n_components
Public Attributes inherited from AutoDerivativeFunction< dim >
Euler
UpwindEuler
FourthOrder
const unsigned int n_components
Public Attributes inherited from Function< dim >
const unsigned int n_components
Static Public Attributes inherited from ParameterAcceptor
static ParameterHandler prm
Static Public Attributes inherited from FunctionParser< dim >
static const unsigned int dimension
Static Public Attributes inherited from AutoDerivativeFunction< dim >
static const unsigned int dimension
Static Public Attributes inherited from Function< dim >
static const unsigned int dimension
Protected Attributes inherited from ParameterAcceptor
const std::string section_name
std::vector< std::string > subsections
Detailed Description
template<int dim>
class Tools::ParsedFunction< dim >
A wrapper for the FunctionParser class.
Definition at line 13 of file parsed_function.h.
Constructor & Destructor Documentation
ParsedFunction()
template<int dim> Tools::ParsedFunction< dim >::ParsedFunction (const std::string & section_name = "", const std::string & expression = "", const std::string & function_description = "Function expression", const std::map< std::string, double > & constants = {}, const std::string & variable_names = FunctionParser<dim>::default_variable_names() + ",t", const double h = 1e-8)
Build a ParameterAcceptor based ParsedFunction.
Notice that the constants parameter must persist as long as this class is alive, since the we store a reference to it.
An example usage of this class is the following:
Tools::ParsedFunction my_fun
The above snippet of code will delcare the ParameterAcceptor::prm ParameterHandler with the following entries:
Definition at line 9 of file parsed_function.cc.
References ParameterHandler::add_action(), ParameterAcceptor::add_parameter(), constant, Tools::ParsedFunction< dim >::constants, ParameterAcceptor::enter_my_subsection(), FunctionParser< dim >::initialize(), ParameterAcceptor::leave_my_subsection(), ParameterAcceptor::prm, ParameterAcceptor::sep, Utilities::split_string_list(), to_string(), value, and Tools::ParsedFunction< dim >::variable_names.
Member Data Documentation
constants
template<int dim> const std::map<std::string, double>& Tools::ParsedFunction< dim >::constants private
Constants that can be used in the expression.
Definition at line 61 of file parsed_function.h.
Referenced by Tools::ParsedFunction< dim >::ParsedFunction().
expression
template<int dim> std::string Tools::ParsedFunction< dim >::expression private
The actual FunctionParser expression.
Definition at line 49 of file parsed_function.h.
local_constants
template<int dim> const std::map<std::string, double> Tools::ParsedFunction< dim >::local_constants private
A local copy of the object passed at constructor, used as a reference for the actual constants when the constructor is called with a rvalue_reference.
Definition at line 56 of file parsed_function.h.
variable_names
template<int dim> const std::string Tools::ParsedFunction< dim >::variable_names private
Keep variable names around to re-initialize the FunctionParser class.
Definition at line 66 of file parsed_function.h.
Referenced by Tools::ParsedFunction< dim >::ParsedFunction().
The documentation for this class was generated from the following files:
include/tools/parsed_function.h
source/parsed_function.cc