Fluid structure interaction suite: magic_enum::detail::static_string< N > Class Template Reference
magic_enum::detail::static_string< N > Class Template Reference
#include <magic_enum.hpp>
Public Member Functions
constexpr static_string (string_view str) noexcept
constexpr const char * data () const noexcept
constexpr std::size_t size () const noexcept
constexpr operator string_view () const noexcept
Private Member Functions
template<std::size_t... I>
constexpr static_string (string_view str, std::index_sequence< I... >) noexcept
Private Attributes
char chars_ [N+1]
Detailed Description
template<std::size_t N>
class magic_enum::detail::static_string< N >
Definition at line 164 of file magic_enum.hpp.
Constructor & Destructor Documentation
static_string() [1/2]
template<std::size_t N> constexpr magic_enum::detail::static_string< N >::static_string (string_view str) inline explicit constexpr noexcept
Definition at line 166 of file magic_enum.hpp.
static_string() [2/2]
template<std::size_t N> template<std::size_t... I> constexpr magic_enum::detail::static_string< N >::static_string (string_view str, std::index_sequence< I... >) inline constexpr private noexcept
Definition at line 178 of file magic_enum.hpp.
Member Function Documentation
data()
template<std::size_t N> constexpr const char* magic_enum::detail::static_string< N >::data () const inline constexpr noexcept
Definition at line 170 of file magic_enum.hpp.
References magic_enum::detail::static_string< N >::chars_.
Referenced by magic_enum::detail::static_string< N >::operator string_view().
operator string_view()
template<std::size_t N> constexpr magic_enum::detail::static_string< N >::operator string_view () const inline constexpr noexcept
Definition at line 174 of file magic_enum.hpp.
References magic_enum::detail::static_string< N >::data(), and magic_enum::detail::static_string< N >::size().
size()
template<std::size_t N> constexpr std::size_t magic_enum::detail::static_string< N >::size () const inline constexpr noexcept
Definition at line 172 of file magic_enum.hpp.
Referenced by magic_enum::detail::n(), and magic_enum::detail::static_string< N >::operator string_view().
Member Data Documentation
chars_
template<std::size_t N> char magic_enum::detail::static_string< N >::chars_[N+1] private
Definition at line 180 of file magic_enum.hpp.
Referenced by magic_enum::detail::static_string< N >::data().
The documentation for this class was generated from the following file:
include/tools/magic_enum.hpp