Fluid structure interaction suite: Tools::ParsedGridRefinement Class Reference
Tools::ParsedGridRefinement Class Reference
A wrapper for refinement strategies.
#include <parsed_grid_refinement.h>
Public Member Functions
ParsedGridRefinement (const std::string &section_name="", const std::string &strategy="fixed_fraction", const double &top_parameter=.3, const double &bottom_parameter=.1, const unsigned int &max_cells=0, const int &min_level=0, const int &max_level=0)
Constructor.
template<int dim, class Vector , int spacedim>
void mark_cells (const Vector &criteria, Triangulation< dim, spacedim > &tria) const
Mark cells a the triangulation for refinement or coarsening, according to the given strategy applied to the supplied vector representing local error criteria.
template<int dim, class VectorType , int spacedim>
void mark_cells (const VectorType &criteria, parallel::distributed::Triangulation< dim, spacedim > &tria) const
Mark cells of a distribtued triangulation for refinement or coarsening, according to the given strategy applied to the supplied vector representing local error criteria.
template<int dim, class Vector , int spacedim>
void mark_cells (const Vector &criteria, parallel::distributed::Triangulation< dim, spacedim > &tria) const
Public Member Functions inherited from ParameterAcceptor
ParameterAcceptor (const std::string &section_name="")
virtual ~ParameterAcceptor () override
virtual void declare_parameters (ParameterHandler &prm)
virtual void parse_parameters (ParameterHandler &prm)
std::string get_section_name () const
std::vector< std::string > get_section_path () const
void add_parameter (const std::string &entry, ParameterType &parameter, const std::string &documentation="", ParameterHandler &prm_=prm, const Patterns::PatternBase &pattern=*Patterns::Tools::Convert< ParameterType >::to_pattern())
void enter_subsection (const std::string &subsection)
void leave_subsection ()
void enter_my_subsection (ParameterHandler &prm)
void leave_my_subsection (ParameterHandler &prm)
void serialize (Archive &ar, const unsigned int version)
void subscribe (std::atomic< bool > *const validity, const std::string &identifier="") const
void unsubscribe (std::atomic< bool > *const validity, const std::string &identifier="") const
unsigned int n_subscriptions () const
void list_subscribers (StreamType &stream) const
void list_subscribers () const
void subscribe (std::atomic< bool > *const validity, const std::string &identifier="") const
void unsubscribe (std::atomic< bool > *const validity, const std::string &identifier="") const
unsigned int n_subscriptions () const
void list_subscribers (StreamType &stream) const
void list_subscribers () const
Public Member Functions inherited from Subscriptor
Subscriptor ()
Subscriptor (const Subscriptor &)
Subscriptor (Subscriptor &&) noexcept
virtual ~Subscriptor ()
Subscriptor & operator= (const Subscriptor &)
Subscriptor & operator= (Subscriptor &&) noexcept
void serialize (Archive &ar, const unsigned int version)
void subscribe (std::atomic< bool > *const validity, const std::string &identifier="") const
void unsubscribe (std::atomic< bool > *const validity, const std::string &identifier="") const
unsigned int n_subscriptions () const
void list_subscribers (StreamType &stream) const
void list_subscribers () const
void subscribe (std::atomic< bool > *const validity, const std::string &identifier="") const
void unsubscribe (std::atomic< bool > *const validity, const std::string &identifier="") const
unsigned int n_subscriptions () const
void list_subscribers (StreamType &stream) const
void list_subscribers () const
Private Member Functions
template<int dim, int spacedim>
void limit_levels (Triangulation< dim, spacedim > &tria) const
Make sure that the refinement level is kept between min_level and max_level.
Private Attributes
std::string strategy
Default expression of this function.
double top_parameter
double bottom_parameter
unsigned int max_cells
int min_level
int max_level
Additional Inherited Members
Static Public Member Functions inherited from ParameterAcceptor
static void initialize (const std::string &filename="", const std::string &output_filename="", const ParameterHandler::OutputStyle output_style_for_output_filename=ParameterHandler::Short, ParameterHandler &prm=ParameterAcceptor::prm, const ParameterHandler::OutputStyle output_style_for_filename=ParameterHandler::DefaultStyle)
static void initialize (std::istream &input_stream, ParameterHandler &prm=ParameterAcceptor::prm)
static void clear ()
static void parse_all_parameters (ParameterHandler &prm=ParameterAcceptor::prm)
static void declare_all_parameters (ParameterHandler &prm=ParameterAcceptor::prm)
static ::ExceptionBase & ExcInUse (int arg1, std::string arg2, std::string arg3)
static ::ExceptionBase & ExcNoSubscriber (std::string arg1, std::string arg2)
Static Public Member Functions inherited from Subscriptor
static ::ExceptionBase & ExcInUse (int arg1, std::string arg2, std::string arg3)
static ::ExceptionBase & ExcNoSubscriber (std::string arg1, std::string arg2)
Public Attributes inherited from ParameterAcceptor
boost::signals2::signal< void()> declare_parameters_call_back
boost::signals2::signal< void()> parse_parameters_call_back
Static Public Attributes inherited from ParameterAcceptor
static ParameterHandler prm
Protected Attributes inherited from ParameterAcceptor
const std::string section_name
std::vector< std::string > subsections
Detailed Description
A wrapper for refinement strategies.
This class implements a parametrized version of the MARK step in AFEM methods. In particular, it allows you to select between
GridRefinement::refine_and_coarsen_fixed_fraction()
GridRefinement::refine_and_coarsen_fixed_number()
Triangulation::refine_global()
and adds also some control parameters to guarantee that the number of cells is maintained under a maximum, and that the refinement level is kept between min_level and max_level.
Definition at line 33 of file parsed_grid_refinement.h.
Constructor & Destructor Documentation
ParsedGridRefinement()
Tools::ParsedGridRefinement::ParsedGridRefinement (const std::string & section_name = "", const std::string & strategy = "fixed_fraction", const double & top_parameter = .3, const double & bottom_parameter = .1, const unsigned int & max_cells = 0, const int & min_level = 0, const int & max_level = 0)
Constructor.
Definition at line 7 of file parsed_grid_refinement.cc.
References ParameterAcceptor::add_parameter(), and ParameterAcceptor::prm.
Member Function Documentation
limit_levels()
template<int dim, int spacedim> void Tools::ParsedGridRefinement::limit_levels (Triangulation< dim, spacedim > & tria) const private
Make sure that the refinement level is kept between min_level and max_level.
Definition at line 175 of file parsed_grid_refinement.h.
References max_level, min_level, and tria.
Referenced by mark_cells().
mark_cells() [1/3]
template<int dim, class Vector , int spacedim> void Tools::ParsedGridRefinement::mark_cells (const Vector & criteria, parallel::distributed::Triangulation< dim, spacedim > & tria) const
Definition at line 110 of file parsed_grid_refinement.h.
References Assert, bottom_parameter, ExcInternalError(), limit_levels(), max_cells, parallel::distributed::GridRefinement::refine_and_coarsen_fixed_fraction(), parallel::distributed::GridRefinement::refine_and_coarsen_fixed_number(), strategy, top_parameter, and tria.
mark_cells() [2/3]
template<int dim, class Vector , int spacedim> void Tools::ParsedGridRefinement::mark_cells (const Vector & criteria, Triangulation< dim, spacedim > & tria) const
Mark cells a the triangulation for refinement or coarsening, according to the given strategy applied to the supplied vector representing local error criteria.
Cells are only marked for refinement or coarsening. No refinement is actually performed. You need to call Triangulation::execute_coarsening_and_refinement() yourself.
Definition at line 142 of file parsed_grid_refinement.h.
References Assert, bottom_parameter, ExcInternalError(), limit_levels(), max_cells, GridRefinement::refine_and_coarsen_fixed_fraction(), GridRefinement::refine_and_coarsen_fixed_number(), strategy, top_parameter, and tria.
mark_cells() [3/3]
template<int dim, class VectorType , int spacedim> void Tools::ParsedGridRefinement::mark_cells (const VectorType & criteria, parallel::distributed::Triangulation< dim, spacedim > & tria) const
Mark cells of a distribtued triangulation for refinement or coarsening, according to the given strategy applied to the supplied vector representing local error criteria.
If the criterion which is specified in the parameter file is not available, an exception is thrown.
Cells are only marked for refinement or coarsening. No refinement is actually performed. You need to call Triangulation::execute_coarsening_and_refinement() yourself.
Member Data Documentation
bottom_parameter
double Tools::ParsedGridRefinement::bottom_parameter private
Definition at line 96 of file parsed_grid_refinement.h.
Referenced by mark_cells().
max_cells
unsigned int Tools::ParsedGridRefinement::max_cells private
Definition at line 97 of file parsed_grid_refinement.h.
Referenced by mark_cells().
max_level
int Tools::ParsedGridRefinement::max_level private
Definition at line 99 of file parsed_grid_refinement.h.
Referenced by limit_levels().
min_level
int Tools::ParsedGridRefinement::min_level private
Definition at line 98 of file parsed_grid_refinement.h.
Referenced by limit_levels().
strategy
std::string Tools::ParsedGridRefinement::strategy private
Default expression of this function.
"
Definition at line 94 of file parsed_grid_refinement.h.
Referenced by mark_cells().
top_parameter
double Tools::ParsedGridRefinement::top_parameter private
Definition at line 95 of file parsed_grid_refinement.h.
Referenced by mark_cells().
The documentation for this class was generated from the following files:
include/tools/parsed_grid_refinement.h
source/parsed_grid_refinement.cc