Fluid structure interaction suite: PDEs::Serial::DistributedLagrange< dim, spacedim > Class Template Reference
PDEs::Serial::DistributedLagrange< dim, spacedim > Class Template Reference
#include <distributed_lagrange.h>
Public Member Functions
DistributedLagrange ()
void run ()
Public Member Functions inherited from ParameterAcceptor
ParameterAcceptor (const std::string &section_name="")
virtual ~ParameterAcceptor () override
virtual void declare_parameters (ParameterHandler &prm)
virtual void parse_parameters (ParameterHandler &prm)
std::string get_section_name () const
std::vector< std::string > get_section_path () const
void add_parameter (const std::string &entry, ParameterType &parameter, const std::string &documentation="", ParameterHandler &prm_=prm, const Patterns::PatternBase &pattern=*Patterns::Tools::Convert< ParameterType >::to_pattern())
void enter_subsection (const std::string &subsection)
void leave_subsection ()
void enter_my_subsection (ParameterHandler &prm)
void leave_my_subsection (ParameterHandler &prm)
void serialize (Archive &ar, const unsigned int version)
void subscribe (std::atomic< bool > *const validity, const std::string &identifier="") const
void unsubscribe (std::atomic< bool > *const validity, const std::string &identifier="") const
unsigned int n_subscriptions () const
void list_subscribers (StreamType &stream) const
void list_subscribers () const
void subscribe (std::atomic< bool > *const validity, const std::string &identifier="") const
void unsubscribe (std::atomic< bool > *const validity, const std::string &identifier="") const
unsigned int n_subscriptions () const
void list_subscribers (StreamType &stream) const
void list_subscribers () const
Public Member Functions inherited from Subscriptor
Subscriptor ()
Subscriptor (const Subscriptor &)
Subscriptor (Subscriptor &&) noexcept
virtual ~Subscriptor ()
Subscriptor & operator= (const Subscriptor &)
Subscriptor & operator= (Subscriptor &&) noexcept
void serialize (Archive &ar, const unsigned int version)
void subscribe (std::atomic< bool > *const validity, const std::string &identifier="") const
void unsubscribe (std::atomic< bool > *const validity, const std::string &identifier="") const
unsigned int n_subscriptions () const
void list_subscribers (StreamType &stream) const
void list_subscribers () const
void subscribe (std::atomic< bool > *const validity, const std::string &identifier="") const
void unsubscribe (std::atomic< bool > *const validity, const std::string &identifier="") const
unsigned int n_subscriptions () const
void list_subscribers (StreamType &stream) const
void list_subscribers () const
Private Member Functions
void generate_grids_and_fes ()
void adjust_embedded_grid ()
void setup_dofs ()
void setup_coupling ()
void assemble_system ()
void solve ()
void output_results ()
Private Attributes
const std::string component_names = "u"
unsigned int coupling_quadrature_order = 3
unsigned int delta_refinement = 3
unsigned int console_level = 1
Triangulation< spacedim > space_grid
std::unique_ptr< FiniteElement< spacedim > > space_fe
std::unique_ptr< MappingFE< spacedim > > space_mapping
std::unique_ptr< GridTools::Cache< spacedim, spacedim > > space_grid_tools_cache
DoFHandler< spacedim > space_dh
Triangulation< dim, spacedim > embedded_grid
std::unique_ptr< FiniteElement< dim, spacedim > > embedded_fe
DoFHandler< dim, spacedim > embedded_dh
std::unique_ptr< FiniteElement< dim, spacedim > > embedded_configuration_fe
DoFHandler< dim, spacedim > embedded_configuration_dh
Vector< double > embedded_configuration
SparsityPattern stiffness_sparsity
SparsityPattern coupling_sparsity
SparseMatrix< double > stiffness_matrix
SparseMatrix< double > coupling_matrix
AffineConstraints< double > constraints
AffineConstraints< double > embedded_constraints
Vector< double > solution
Vector< double > rhs
Vector< double > lambda
Vector< double > embedded_rhs
Vector< double > embedded_value
TimerOutput monitor
unsigned int finite_element_degree = 1
unsigned int embedded_space_finite_element_degree = 1
unsigned int embedded_configuration_finite_element_degree = 1
ParsedTools::GridGenerator< spacedim > grid_generator
ParsedTools::GridRefinement grid_refinement
ParsedTools::GridGenerator< dim, spacedim > embedded_grid_generator
ParsedTools::MappingEulerian< dim, spacedim > embedded_mapping
ParsedTools::Constants constants
ParsedTools::Function< spacedim > embedded_value_function
ParsedTools::Function< spacedim > forcing_term
ParsedTools::Function< spacedim > exact_solution
ParsedTools::BoundaryConditions< spacedim > boundary_conditions
ParsedLAC::InverseOperator stiffness_inverse_operator
ParsedLAC::AMGPreconditioner stiffness_preconditioner
ParsedLAC::InverseOperator schur_inverse_operator
ParsedLAC::AMGPreconditioner schur_preconditioner
ParsedTools::DataOut< spacedim > data_out
ParsedTools::DataOut< dim, spacedim > embedded_data_out
Additional Inherited Members
Static Public Member Functions inherited from ParameterAcceptor
static void initialize (const std::string &filename="", const std::string &output_filename="", const ParameterHandler::OutputStyle output_style_for_output_filename=ParameterHandler::Short, ParameterHandler &prm=ParameterAcceptor::prm, const ParameterHandler::OutputStyle output_style_for_filename=ParameterHandler::DefaultStyle)
static void initialize (std::istream &input_stream, ParameterHandler &prm=ParameterAcceptor::prm)
static void clear ()
static void parse_all_parameters (ParameterHandler &prm=ParameterAcceptor::prm)
static void declare_all_parameters (ParameterHandler &prm=ParameterAcceptor::prm)
static ::ExceptionBase & ExcInUse (int arg1, std::string arg2, std::string arg3)
static ::ExceptionBase & ExcNoSubscriber (std::string arg1, std::string arg2)
Static Public Member Functions inherited from Subscriptor
static ::ExceptionBase & ExcInUse (int arg1, std::string arg2, std::string arg3)
static ::ExceptionBase & ExcNoSubscriber (std::string arg1, std::string arg2)
Public Attributes inherited from ParameterAcceptor
boost::signals2::signal< void()> declare_parameters_call_back
boost::signals2::signal< void()> parse_parameters_call_back
Static Public Attributes inherited from ParameterAcceptor
static ParameterHandler prm
Protected Attributes inherited from ParameterAcceptor
const std::string section_name
std::vector< std::string > subsections
Detailed Description
template<int dim, int spacedim = dim>
class PDEs::Serial::DistributedLagrange< dim, spacedim >
Definition at line 36 of file distributed_lagrange.h.
Constructor & Destructor Documentation
DistributedLagrange()
template<int dim, int spacedim> PDEs::Serial::DistributedLagrange< dim, spacedim >::DistributedLagrange
Definition at line 30 of file distributed_lagrange.cc.
References ParameterAcceptor::add_parameter(), PDEs::Serial::DistributedLagrange< dim, spacedim >::console_level, PDEs::Serial::DistributedLagrange< dim, spacedim >::coupling_quadrature_order, PDEs::Serial::DistributedLagrange< dim, spacedim >::embedded_configuration_finite_element_degree, PDEs::Serial::DistributedLagrange< dim, spacedim >::embedded_space_finite_element_degree, and PDEs::Serial::DistributedLagrange< dim, spacedim >::finite_element_degree.
Member Function Documentation
adjust_embedded_grid()
template<int dim, int spacedim> void PDEs::Serial::DistributedLagrange< dim, spacedim >::adjust_embedded_grid private
Definition at line 119 of file distributed_lagrange.cc.
References center, deallog, diameter(), GridTools::maximal_cell_diameter(), and GridTools::minimal_cell_diameter().
assemble_system()
template<int dim, int spacedim> void PDEs::Serial::DistributedLagrange< dim, spacedim >::assemble_system private
Definition at line 232 of file distributed_lagrange.cc.
References NonMatching::create_coupling_mass_matrix(), VectorTools::create_right_hand_side(), ParsedTools::Components::get_cell_quadrature(), and VectorTools::interpolate().
generate_grids_and_fes()
template<int dim, int spacedim> void PDEs::Serial::DistributedLagrange< dim, spacedim >::generate_grids_and_fes private
Definition at line 62 of file distributed_lagrange.cc.
References GridTools::compute_point_locations(), ParsedTools::Components::get_lagrangian_finite_element(), and DoFTools::map_dofs_to_support_points().
output_results()
template<int dim, int spacedim> void PDEs::Serial::DistributedLagrange< dim, spacedim >::output_results private
Definition at line 292 of file distributed_lagrange.cc.
References lambda.
run()
template<int dim, int spacedim> void PDEs::Serial::DistributedLagrange< dim, spacedim >::run
Definition at line 309 of file distributed_lagrange.cc.
References deallog, and LogStream::depth_console().
Referenced by main().
setup_coupling()
template<int dim, int spacedim> void PDEs::Serial::DistributedLagrange< dim, spacedim >::setup_coupling private
Definition at line 210 of file distributed_lagrange.cc.
References NonMatching::create_coupling_sparsity_pattern().
setup_dofs()
template<int dim, int spacedim> void PDEs::Serial::DistributedLagrange< dim, spacedim >::setup_dofs private
Definition at line 180 of file distributed_lagrange.cc.
References deallog, lambda, DoFTools::make_hanging_node_constraints(), and DoFTools::make_sparsity_pattern().
solve()
template<int dim, int spacedim> void PDEs::Serial::DistributedLagrange< dim, spacedim >::solve private
Definition at line 271 of file distributed_lagrange.cc.
References C(), identity_operator(), lambda, linear_operator(), and transpose_operator().
Member Data Documentation
boundary_conditions
template<int dim, int spacedim = dim> ParsedTools::BoundaryConditions<spacedim> PDEs::Serial::DistributedLagrange< dim, spacedim >::boundary_conditions private
Definition at line 111 of file distributed_lagrange.h.
component_names
template<int dim, int spacedim = dim> const std::string PDEs::Serial::DistributedLagrange< dim, spacedim >::component_names = "u" private
Definition at line 60 of file distributed_lagrange.h.
console_level
template<int dim, int spacedim = dim> unsigned int PDEs::Serial::DistributedLagrange< dim, spacedim >::console_level = 1 private
Definition at line 64 of file distributed_lagrange.h.
Referenced by PDEs::Serial::DistributedLagrange< dim, spacedim >::DistributedLagrange().
constants
template<int dim, int spacedim = dim> ParsedTools::Constants PDEs::Serial::DistributedLagrange< dim, spacedim >::constants private
Definition at line 107 of file distributed_lagrange.h.
constraints
template<int dim, int spacedim = dim> AffineConstraints<double> PDEs::Serial::DistributedLagrange< dim, spacedim >::constraints private
Definition at line 85 of file distributed_lagrange.h.
coupling_matrix
template<int dim, int spacedim = dim> SparseMatrix<double> PDEs::Serial::DistributedLagrange< dim, spacedim >::coupling_matrix private
Definition at line 84 of file distributed_lagrange.h.
coupling_quadrature_order
template<int dim, int spacedim = dim> unsigned int PDEs::Serial::DistributedLagrange< dim, spacedim >::coupling_quadrature_order = 3 private
Definition at line 62 of file distributed_lagrange.h.
Referenced by PDEs::Serial::DistributedLagrange< dim, spacedim >::DistributedLagrange().
coupling_sparsity
template<int dim, int spacedim = dim> SparsityPattern PDEs::Serial::DistributedLagrange< dim, spacedim >::coupling_sparsity private
Definition at line 82 of file distributed_lagrange.h.
data_out
template<int dim, int spacedim = dim> ParsedTools::DataOut<spacedim> PDEs::Serial::DistributedLagrange< dim, spacedim >::data_out mutable private
Definition at line 119 of file distributed_lagrange.h.
delta_refinement
template<int dim, int spacedim = dim> unsigned int PDEs::Serial::DistributedLagrange< dim, spacedim >::delta_refinement = 3 private
Definition at line 63 of file distributed_lagrange.h.
embedded_configuration
template<int dim, int spacedim = dim> Vector<double> PDEs::Serial::DistributedLagrange< dim, spacedim >::embedded_configuration private
Definition at line 79 of file distributed_lagrange.h.
embedded_configuration_dh
template<int dim, int spacedim = dim> DoFHandler<dim, spacedim> PDEs::Serial::DistributedLagrange< dim, spacedim >::embedded_configuration_dh private
Definition at line 78 of file distributed_lagrange.h.
embedded_configuration_fe
template<int dim, int spacedim = dim> std::unique_ptr<FiniteElement<dim, spacedim> > PDEs::Serial::DistributedLagrange< dim, spacedim >::embedded_configuration_fe private
Definition at line 77 of file distributed_lagrange.h.
embedded_configuration_finite_element_degree
template<int dim, int spacedim = dim> unsigned int PDEs::Serial::DistributedLagrange< dim, spacedim >::embedded_configuration_finite_element_degree = 1 private
Definition at line 98 of file distributed_lagrange.h.
Referenced by PDEs::Serial::DistributedLagrange< dim, spacedim >::DistributedLagrange().
embedded_constraints
template<int dim, int spacedim = dim> AffineConstraints<double> PDEs::Serial::DistributedLagrange< dim, spacedim >::embedded_constraints private
Definition at line 86 of file distributed_lagrange.h.
embedded_data_out
template<int dim, int spacedim = dim> ParsedTools::DataOut<dim, spacedim> PDEs::Serial::DistributedLagrange< dim, spacedim >::embedded_data_out mutable private
Definition at line 120 of file distributed_lagrange.h.
embedded_dh
template<int dim, int spacedim = dim> DoFHandler<dim, spacedim> PDEs::Serial::DistributedLagrange< dim, spacedim >::embedded_dh private
Definition at line 75 of file distributed_lagrange.h.
embedded_fe
template<int dim, int spacedim = dim> std::unique_ptr<FiniteElement<dim, spacedim> > PDEs::Serial::DistributedLagrange< dim, spacedim >::embedded_fe private
Definition at line 74 of file distributed_lagrange.h.
embedded_grid
template<int dim, int spacedim = dim> Triangulation<dim, spacedim> PDEs::Serial::DistributedLagrange< dim, spacedim >::embedded_grid private
Definition at line 73 of file distributed_lagrange.h.
embedded_grid_generator
template<int dim, int spacedim = dim> ParsedTools::GridGenerator<dim, spacedim> PDEs::Serial::DistributedLagrange< dim, spacedim >::embedded_grid_generator private
Definition at line 104 of file distributed_lagrange.h.
embedded_mapping
template<int dim, int spacedim = dim> ParsedTools::MappingEulerian<dim, spacedim> PDEs::Serial::DistributedLagrange< dim, spacedim >::embedded_mapping private
Definition at line 105 of file distributed_lagrange.h.
embedded_rhs
template<int dim, int spacedim = dim> Vector<double> PDEs::Serial::DistributedLagrange< dim, spacedim >::embedded_rhs private
Definition at line 90 of file distributed_lagrange.h.
embedded_space_finite_element_degree
template<int dim, int spacedim = dim> unsigned int PDEs::Serial::DistributedLagrange< dim, spacedim >::embedded_space_finite_element_degree = 1 private
Definition at line 97 of file distributed_lagrange.h.
Referenced by PDEs::Serial::DistributedLagrange< dim, spacedim >::DistributedLagrange().
embedded_value
template<int dim, int spacedim = dim> Vector<double> PDEs::Serial::DistributedLagrange< dim, spacedim >::embedded_value private
Definition at line 91 of file distributed_lagrange.h.
embedded_value_function
template<int dim, int spacedim = dim> ParsedTools::Function<spacedim> PDEs::Serial::DistributedLagrange< dim, spacedim >::embedded_value_function private
Definition at line 108 of file distributed_lagrange.h.
exact_solution
template<int dim, int spacedim = dim> ParsedTools::Function<spacedim> PDEs::Serial::DistributedLagrange< dim, spacedim >::exact_solution private
Definition at line 110 of file distributed_lagrange.h.
finite_element_degree
template<int dim, int spacedim = dim> unsigned int PDEs::Serial::DistributedLagrange< dim, spacedim >::finite_element_degree = 1 private
Definition at line 96 of file distributed_lagrange.h.
Referenced by PDEs::Serial::DistributedLagrange< dim, spacedim >::DistributedLagrange().
forcing_term
template<int dim, int spacedim = dim> ParsedTools::Function<spacedim> PDEs::Serial::DistributedLagrange< dim, spacedim >::forcing_term private
Definition at line 109 of file distributed_lagrange.h.
grid_generator
template<int dim, int spacedim = dim> ParsedTools::GridGenerator<spacedim> PDEs::Serial::DistributedLagrange< dim, spacedim >::grid_generator private
Definition at line 101 of file distributed_lagrange.h.
grid_refinement
template<int dim, int spacedim = dim> ParsedTools::GridRefinement PDEs::Serial::DistributedLagrange< dim, spacedim >::grid_refinement private
Definition at line 102 of file distributed_lagrange.h.
lambda
template<int dim, int spacedim = dim> Vector<double> PDEs::Serial::DistributedLagrange< dim, spacedim >::lambda private
Definition at line 89 of file distributed_lagrange.h.
monitor
template<int dim, int spacedim = dim> TimerOutput PDEs::Serial::DistributedLagrange< dim, spacedim >::monitor private
Definition at line 93 of file distributed_lagrange.h.
rhs
template<int dim, int spacedim = dim> Vector<double> PDEs::Serial::DistributedLagrange< dim, spacedim >::rhs private
Definition at line 88 of file distributed_lagrange.h.
schur_inverse_operator
template<int dim, int spacedim = dim> ParsedLAC::InverseOperator PDEs::Serial::DistributedLagrange< dim, spacedim >::schur_inverse_operator private
Definition at line 116 of file distributed_lagrange.h.
schur_preconditioner
template<int dim, int spacedim = dim> ParsedLAC::AMGPreconditioner PDEs::Serial::DistributedLagrange< dim, spacedim >::schur_preconditioner private
Definition at line 117 of file distributed_lagrange.h.
solution
template<int dim, int spacedim = dim> Vector<double> PDEs::Serial::DistributedLagrange< dim, spacedim >::solution private
Definition at line 87 of file distributed_lagrange.h.
space_dh
template<int dim, int spacedim = dim> DoFHandler<spacedim> PDEs::Serial::DistributedLagrange< dim, spacedim >::space_dh private
Definition at line 71 of file distributed_lagrange.h.
space_fe
template<int dim, int spacedim = dim> std::unique_ptr<FiniteElement<spacedim> > PDEs::Serial::DistributedLagrange< dim, spacedim >::space_fe private
Definition at line 67 of file distributed_lagrange.h.
space_grid
template<int dim, int spacedim = dim> Triangulation<spacedim> PDEs::Serial::DistributedLagrange< dim, spacedim >::space_grid private
Definition at line 66 of file distributed_lagrange.h.
space_grid_tools_cache
template<int dim, int spacedim = dim> std::unique_ptr<GridTools::Cache<spacedim, spacedim> > PDEs::Serial::DistributedLagrange< dim, spacedim >::space_grid_tools_cache private
Definition at line 70 of file distributed_lagrange.h.
space_mapping
template<int dim, int spacedim = dim> std::unique_ptr<MappingFE<spacedim> > PDEs::Serial::DistributedLagrange< dim, spacedim >::space_mapping private
Definition at line 68 of file distributed_lagrange.h.
stiffness_inverse_operator
template<int dim, int spacedim = dim> ParsedLAC::InverseOperator PDEs::Serial::DistributedLagrange< dim, spacedim >::stiffness_inverse_operator private
Definition at line 113 of file distributed_lagrange.h.
stiffness_matrix
template<int dim, int spacedim = dim> SparseMatrix<double> PDEs::Serial::DistributedLagrange< dim, spacedim >::stiffness_matrix private
Definition at line 83 of file distributed_lagrange.h.
stiffness_preconditioner
template<int dim, int spacedim = dim> ParsedLAC::AMGPreconditioner PDEs::Serial::DistributedLagrange< dim, spacedim >::stiffness_preconditioner private
Definition at line 114 of file distributed_lagrange.h.
stiffness_sparsity
template<int dim, int spacedim = dim> SparsityPattern PDEs::Serial::DistributedLagrange< dim, spacedim >::stiffness_sparsity private
Definition at line 81 of file distributed_lagrange.h.
The documentation for this class was generated from the following files:
include/pdes/serial/distributed_lagrange.h
source/pdes/serial/distributed_lagrange.cc