Fluid structure interaction suite: Tools::ParsedBoundaryConditions< dim > Class Template Reference
Tools::ParsedBoundaryConditions< dim > Class Template Reference
A wrapper for boundary conditions.
#include <parsed_boundary_conditions.h>
Public Types
using IdsAndBoundaryConditions = std::tuple< std::set< types::boundary_id >, std::string, BoundaryIdType, std::string >
Public Member Functions
ParsedBoundaryConditions (const std::string &section_name="", const std::string &component_names="u", const std::vector< std::set< types::boundary_id >> &ids={{numbers::internal_face_boundary_id}}, const std::vector< std::string > &selected_components={"u"}, const std::vector< BoundaryIdType > &bc_type={BoundaryIdType::dirichlet}, const std::vector< std::string > &expressions={"0"})
Constructor.
void update_substitution_map (const Differentiation::SD::types::substitution_map &substitution_map)
Update the substitition map of every Functions::SymbolicFunction defined in this object.
void set_additional_function_arguments (const Differentiation::SD::types::substitution_map &arguments)
Call Functions::SymbolicFunction::set_additional_function_arguments() for every function defined in this object.
void set_time (const double &time)
Update time in each Functions::SymbolicFunction defined in this object.
template<typename Tria >
void check_consistency (const Tria &tria) const
Check that the grid is compatible with this boundary condition object, and that the boundary conditions are self consistent.
void check_consistency () const
Make sure the specified boundary conditions make sense.
Public Member Functions inherited from ParameterAcceptor
ParameterAcceptor (const std::string &section_name="")
virtual ~ParameterAcceptor () override
virtual void declare_parameters (ParameterHandler &prm)
virtual void parse_parameters (ParameterHandler &prm)
std::string get_section_name () const
std::vector< std::string > get_section_path () const
void add_parameter (const std::string &entry, ParameterType &parameter, const std::string &documentation="", ParameterHandler &prm_=prm, const Patterns::PatternBase &pattern=*Patterns::Tools::Convert< ParameterType >::to_pattern())
void enter_subsection (const std::string &subsection)
void leave_subsection ()
void enter_my_subsection (ParameterHandler &prm)
void leave_my_subsection (ParameterHandler &prm)
void serialize (Archive &ar, const unsigned int version)
void subscribe (std::atomic< bool > *const validity, const std::string &identifier="") const
void unsubscribe (std::atomic< bool > *const validity, const std::string &identifier="") const
unsigned int n_subscriptions () const
void list_subscribers (StreamType &stream) const
void list_subscribers () const
void subscribe (std::atomic< bool > *const validity, const std::string &identifier="") const
void unsubscribe (std::atomic< bool > *const validity, const std::string &identifier="") const
unsigned int n_subscriptions () const
void list_subscribers (StreamType &stream) const
void list_subscribers () const
Public Member Functions inherited from Subscriptor
Subscriptor ()
Subscriptor (const Subscriptor &)
Subscriptor (Subscriptor &&) noexcept
virtual ~Subscriptor ()
Subscriptor & operator= (const Subscriptor &)
Subscriptor & operator= (Subscriptor &&) noexcept
void serialize (Archive &ar, const unsigned int version)
void subscribe (std::atomic< bool > *const validity, const std::string &identifier="") const
void unsubscribe (std::atomic< bool > *const validity, const std::string &identifier="") const
unsigned int n_subscriptions () const
void list_subscribers (StreamType &stream) const
void list_subscribers () const
void subscribe (std::atomic< bool > *const validity, const std::string &identifier="") const
void unsubscribe (std::atomic< bool > *const validity, const std::string &identifier="") const
unsigned int n_subscriptions () const
void list_subscribers (StreamType &stream) const
void list_subscribers () const
Private Attributes
const std::string component_names
Component names of the boundary conditions.
const unsigned int n_components
Number of components of the problem.
unsigned int n_boundary_conditions
Number of boundary conditions.
std::vector< std::set< types::boundary_id > > ids
Ids on which this object applies boundary conditions.
std::vector< std::string > selected_components
Component on which to apply the boundary condition.
std::vector< BoundaryIdType > bc_type
Type of boundary conditions.
std::vector< std::string > expressions
Expressions for the boundary conditions.
std::vector< std::unique_ptr< Functions::SymbolicFunction< dim > > > functions
The actual functions.
GridInfo grid_info
Information about the grid this BC applies to.
Additional Inherited Members
Static Public Member Functions inherited from ParameterAcceptor
static void initialize (const std::string &filename="", const std::string &output_filename="", const ParameterHandler::OutputStyle output_style_for_output_filename=ParameterHandler::Short, ParameterHandler &prm=ParameterAcceptor::prm, const ParameterHandler::OutputStyle output_style_for_filename=ParameterHandler::DefaultStyle)
static void initialize (std::istream &input_stream, ParameterHandler &prm=ParameterAcceptor::prm)
static void clear ()
static void parse_all_parameters (ParameterHandler &prm=ParameterAcceptor::prm)
static void declare_all_parameters (ParameterHandler &prm=ParameterAcceptor::prm)
static ::ExceptionBase & ExcInUse (int arg1, std::string arg2, std::string arg3)
static ::ExceptionBase & ExcNoSubscriber (std::string arg1, std::string arg2)
Static Public Member Functions inherited from Subscriptor
static ::ExceptionBase & ExcInUse (int arg1, std::string arg2, std::string arg3)
static ::ExceptionBase & ExcNoSubscriber (std::string arg1, std::string arg2)
Public Attributes inherited from ParameterAcceptor
boost::signals2::signal< void()> declare_parameters_call_back
boost::signals2::signal< void()> parse_parameters_call_back
Static Public Attributes inherited from ParameterAcceptor
static ParameterHandler prm
Protected Attributes inherited from ParameterAcceptor
const std::string section_name
std::vector< std::string > subsections
Detailed Description
template<int dim>
class Tools::ParsedBoundaryConditions< dim >
A wrapper for boundary conditions.
This class can be used to store different types of boundary conditions, applied to different ids of the domain boundary.
Definition at line 37 of file parsed_boundary_conditions.h.
Member Typedef Documentation
IdsAndBoundaryConditions
template<int dim> using Tools::ParsedBoundaryConditions< dim >::IdsAndBoundaryConditions = std::tuple<std::set<types::boundary_id>, std::string, BoundaryIdType, std::string>
Definition at line 44 of file parsed_boundary_conditions.h.
Constructor & Destructor Documentation
ParsedBoundaryConditions()
template<int dim> Tools::ParsedBoundaryConditions< dim >::ParsedBoundaryConditions (const std::string & section_name = "", const std::string & component_names = "u", const std::vector< std::set< types::boundary_id >> & ids = {{numbers::internal_face_boundary_id}}, const std::vector< std::string > & selected_components = {"u"}, const std::vector< BoundaryIdType > & bc_type = {BoundaryIdType::dirichlet}, const std::vector< std::string > & expressions = {"0"})
Constructor.
Definition at line 13 of file parsed_boundary_conditions.cc.
References ParameterAcceptor::add_parameter(), Tools::ParsedBoundaryConditions< dim >::check_consistency(), Tools::ParsedBoundaryConditions< dim >::component_names, exp(), Tools::ParsedBoundaryConditions< dim >::functions, Tools::ParsedBoundaryConditions< dim >::ids, Patterns::List::max_int_value, Tools::ParsedBoundaryConditions< dim >::n_components, ParameterAcceptor::parse_parameters_call_back, and ParameterAcceptor::prm.
Member Function Documentation
check_consistency() [1/2]
template<int dim> void Tools::ParsedBoundaryConditions< dim >::check_consistency
Make sure the specified boundary conditions make sense.
Do this, independently of the Triangulation this object is associated with.
Definition at line 71 of file parsed_boundary_conditions.cc.
References AssertThrow, begin(), end(), ExcMessage(), and numbers::invalid_boundary_id.
Referenced by Tools::ParsedBoundaryConditions< dim >::check_consistency(), and Tools::ParsedBoundaryConditions< dim >::ParsedBoundaryConditions().
check_consistency() [2/2]
template<int dim> template<typename Tria > void Tools::ParsedBoundaryConditions< dim >::check_consistency (const Tria & tria) const inline
Check that the grid is compatible with this boundary condition object, and that the boundary conditions are self consistent.
Definition at line 95 of file parsed_boundary_conditions.h.
References Tools::GridInfo::build_info(), Tools::ParsedBoundaryConditions< dim >::check_consistency(), Tools::ParsedBoundaryConditions< dim >::grid_info, and tria.
set_additional_function_arguments()
template<int dim> void Tools::ParsedBoundaryConditions< dim >::set_additional_function_arguments (const Differentiation::SD::types::substitution_map & arguments)
Call Functions::SymbolicFunction::set_additional_function_arguments() for every function defined in this object.
See the documentation of Functions::SymbolicFunction::set_additional_function_arguments().
Definition at line 136 of file parsed_boundary_conditions.cc.
References functions.
set_time()
template<int dim> void Tools::ParsedBoundaryConditions< dim >::set_time (const double & time)
Update time in each Functions::SymbolicFunction defined in this object.
Definition at line 147 of file parsed_boundary_conditions.cc.
References functions.
update_substitution_map()
template<int dim> void Tools::ParsedBoundaryConditions< dim >::update_substitution_map (const Differentiation::SD::types::substitution_map & substitution_map)
Update the substitition map of every Functions::SymbolicFunction defined in this object.
See the documentation of Functions::SymbolicFunction::update_user_substitution_map().
Definition at line 124 of file parsed_boundary_conditions.cc.
References functions.
Member Data Documentation
bc_type
template<int dim> std::vector<BoundaryIdType> Tools::ParsedBoundaryConditions< dim >::bc_type private
Type of boundary conditions.
Definition at line 137 of file parsed_boundary_conditions.h.
component_names
template<int dim> const std::string Tools::ParsedBoundaryConditions< dim >::component_names private
Component names of the boundary conditions.
Definition at line 112 of file parsed_boundary_conditions.h.
Referenced by Tools::ParsedBoundaryConditions< dim >::ParsedBoundaryConditions().
expressions
template<int dim> std::vector<std::string> Tools::ParsedBoundaryConditions< dim >::expressions private
Expressions for the boundary conditions.
Definition at line 142 of file parsed_boundary_conditions.h.
functions
template<int dim> std::vector<std::unique_ptr<Functions::SymbolicFunction<dim> > > Tools::ParsedBoundaryConditions< dim >::functions private
The actual functions.
Definition at line 148 of file parsed_boundary_conditions.h.
Referenced by Tools::ParsedBoundaryConditions< dim >::ParsedBoundaryConditions().
grid_info
template<int dim> GridInfo Tools::ParsedBoundaryConditions< dim >::grid_info mutable private
Information about the grid this BC applies to.
Definition at line 153 of file parsed_boundary_conditions.h.
Referenced by Tools::ParsedBoundaryConditions< dim >::check_consistency().
ids
template<int dim> std::vector<std::set<types::boundary_id> > Tools::ParsedBoundaryConditions< dim >::ids private
Ids on which this object applies boundary conditions.
Definition at line 127 of file parsed_boundary_conditions.h.
Referenced by Tools::ParsedBoundaryConditions< dim >::ParsedBoundaryConditions().
n_boundary_conditions
template<int dim> unsigned int Tools::ParsedBoundaryConditions< dim >::n_boundary_conditions mutable private
Number of boundary conditions.
Definition at line 122 of file parsed_boundary_conditions.h.
n_components
template<int dim> const unsigned int Tools::ParsedBoundaryConditions< dim >::n_components private
Number of components of the problem.
Definition at line 117 of file parsed_boundary_conditions.h.
Referenced by Tools::ParsedBoundaryConditions< dim >::ParsedBoundaryConditions().
selected_components
template<int dim> std::vector<std::string> Tools::ParsedBoundaryConditions< dim >::selected_components private
Component on which to apply the boundary condition.
Definition at line 132 of file parsed_boundary_conditions.h.
The documentation for this class was generated from the following files:
include/tools/parsed_boundary_conditions.h
source/parsed_boundary_conditions.cc