Fluid structure interaction suite: PDEs::MPI::Poisson< dim, spacedim > Class Template Reference
PDEs::MPI::Poisson< dim, spacedim > Class Template Reference
Solve the Poisson problem, in parallel.
#include <poisson.h>
Public Types
using ScratchData = typename LinearProblem< dim, spacedim, LAC::LATrilinos >::ScratchData
using CopyData = typename LinearProblem< dim, spacedim, LAC::LATrilinos >::CopyData
using VectorType = typename LinearProblem< dim, spacedim, LAC::LATrilinos >::VectorType
Public Types inherited from PDEs::LinearProblem< dim, dim, LAC::LATrilinos >
using CopyData = MeshWorker::CopyData< 1, 1, 1 >
Default CopyData object, used in the WorkStream class.
using ScratchData = MeshWorker::ScratchData< dim, spacedim >
Default ScratchData object, used in the workstream class.
using BlockVectorType = typename LAC::LATrilinos ::BlockVector
Block vector type.
using VectorType = typename BlockVectorType::BlockType
Vector type.
using BlockMatrixType = typename LAC::LATrilinos ::BlockSparseMatrix
Block matrix type.
Public Member Functions
Poisson ()
Constructor.
virtual ~Poisson ()=default
Destroy the Poisson object.
Public Member Functions inherited from PDEs::LinearProblem< dim, dim, LAC::LATrilinos >
LinearProblem (const std::string &component_names="u", const std::string &problem_name="")
Constructor.
virtual ~LinearProblem ()=default
Virtual destructor.
virtual void run ()
Main entry point of the problem.
Public Member Functions inherited from ParameterAcceptor
ParameterAcceptor (const std::string &section_name="")
virtual ~ParameterAcceptor () override
virtual void declare_parameters (ParameterHandler &prm)
virtual void parse_parameters (ParameterHandler &prm)
std::string get_section_name () const
std::vector< std::string > get_section_path () const
void add_parameter (const std::string &entry, ParameterType &parameter, const std::string &documentation="", ParameterHandler &prm_=prm, const Patterns::PatternBase &pattern=*Patterns::Tools::Convert< ParameterType >::to_pattern())
void enter_subsection (const std::string &subsection)
void leave_subsection ()
void enter_my_subsection (ParameterHandler &prm)
void leave_my_subsection (ParameterHandler &prm)
void serialize (Archive &ar, const unsigned int version)
void subscribe (std::atomic< bool > *const validity, const std::string &identifier="") const
void unsubscribe (std::atomic< bool > *const validity, const std::string &identifier="") const
unsigned int n_subscriptions () const
void list_subscribers (StreamType &stream) const
void list_subscribers () const
void subscribe (std::atomic< bool > *const validity, const std::string &identifier="") const
void unsubscribe (std::atomic< bool > *const validity, const std::string &identifier="") const
unsigned int n_subscriptions () const
void list_subscribers (StreamType &stream) const
void list_subscribers () const
Public Member Functions inherited from Subscriptor
Subscriptor ()
Subscriptor (const Subscriptor &)
Subscriptor (Subscriptor &&) noexcept
virtual ~Subscriptor ()
Subscriptor & operator= (const Subscriptor &)
Subscriptor & operator= (Subscriptor &&) noexcept
void serialize (Archive &ar, const unsigned int version)
void subscribe (std::atomic< bool > *const validity, const std::string &identifier="") const
void unsubscribe (std::atomic< bool > *const validity, const std::string &identifier="") const
unsigned int n_subscriptions () const
void list_subscribers (StreamType &stream) const
void list_subscribers () const
void subscribe (std::atomic< bool > *const validity, const std::string &identifier="") const
void unsubscribe (std::atomic< bool > *const validity, const std::string &identifier="") const
unsigned int n_subscriptions () const
void list_subscribers (StreamType &stream) const
void list_subscribers () const
Protected Member Functions
virtual void assemble_system_one_cell (const typename DoFHandler< dim, spacedim >::active_cell_iterator &cell, ScratchData &scratch, CopyData &copy) override
Explicitly assemble the Poisson problem on a single cell.
virtual void solve () override
Make sure we initialize the right type of linear solver.
Protected Member Functions inherited from PDEs::LinearProblem< dim, dim, LAC::LATrilinos >
virtual void assemble_system_one_cell (const typename DoFHandler< dim, spacedim >::active_cell_iterator &cell, ScratchData &scratch, CopyData &copy)
Assemble the local system matrix on cell, using scratch for FEValues and other expensive scratch objects, and store the result in the copy object.
virtual void copy_one_cell (const CopyData &copy)
Distribute the data that has been assembled by assemble_system_on_cell() to the global matrix and rhs.
virtual void estimate (Vector< float > &error_per_cell) const
Perform a posteriori error estimation, and store the results in the error_per_cell vector.
void mark (const Vector< float > &error_per_cell)
According to the chosen strategy, mark some cells for refinement, possibily using the error_per_cell vector.
void refine ()
Refine the grid.
virtual void setup_system ()
Initial setup: distribute degrees of freedom, make all vectors and matrices of the right size, initialize functions and pointers.
virtual void assemble_system ()
Actually loop over cells, and assemble the global system.
virtual void output_results (const unsigned cycle) const
Output the solution and the grid in a format that can be read by Paraview or Visit.
virtual void print_system_info () const
print some information about the current processes/mpi/ranks/etc.
Protected Attributes
ParsedTools::Function< spacedim > coefficient
Protected Attributes inherited from PDEs::LinearProblem< dim, dim, LAC::LATrilinos >
boost::signals2::signal< void()> add_constraints_call_back
A signal that is called at the end of setup_system()
boost::signals2::signal< void()> setup_system_call_back
A signal that is called at the end of setup_system()
boost::signals2::signal< void()> output_results_call_back
A signal that is called at the end of output_results()
boost::signals2::signal< void()> assemble_system_call_back
A signal that is called at the end of assemble_system()
boost::signals2::signal< void(ParsedTools::DataOut< dim, spacedim > &)> add_data_vector
Connect to this signal to add data additional vectors to the output system.
const std::string component_names
Comma seperated names of components.
const unsigned int n_components
Number of components.
const std::string problem_name
Name of the problem to solve.
const std::string section_name
Name of the section to use within the parameter file.
MPI_Comm mpi_communicator
Global mpi communicator.
const unsigned int mpi_rank
The mpi rank of this process.
const unsigned int mpi_size
The number of mpi processes.
int number_of_threads
Number of threads to use for multi-threaded assembly.
unsigned int verbosity_level
Verbosity level of deallog.
ConditionalOStream pcout
Output only on processor zero.
TimerOutput timer
Timing information.
ParsedTools::GridGenerator< dim, spacedim > grid_generator
A wrapper around GridIn, GridOut, and GridGenerator namespace.
ParsedTools::GridRefinement grid_refinement
Grid refinement and error estimation.
parallel::distributed::Triangulation< dim, spacedim > triangulation
The problem triangulation.
ParsedTools::FiniteElement< dim, spacedim > finite_element
A wrapper around deal.II FiniteElement classes.
std::unique_ptr< Mapping< dim, spacedim > > mapping
The Mapping between reference and real elements.
DoFHandler< dim, spacedim > dof_handler
Handler of degrees of freedom.
AffineConstraints< double > constraints
Hanging nodes and essential boundary conditions.
std::vector< types::global_dof_index > dofs_per_block
Dofs per block.
std::vector< IndexSet > locally_owned_dofs
All degrees of freedom owned by this MPI process.
std::vector< IndexSet > locally_relevant_dofs
All degrees of freedom needed for output and error estimation.
LAC::LATrilinos ::BlockSparsityPattern system_block_sparsity
System sparsity pattern.
LAC::LATrilinos ::BlockSparseMatrix system_block_matrix
System matrix.
LAC::LATrilinos ::BlockVector locally_relevant_block_solution
A read only copy of the solution vector used for output and error estimation.
LAC::LATrilinos ::BlockVector block_solution
Solution vector.
LAC::LATrilinos ::BlockVector system_block_rhs
The system right hand side.
Vector< float > error_per_cell
Storage for local error estimator.
ParsedLAC::InverseOperator inverse_operator
Inverse operator.
ParsedLAC::AMGPreconditioner preconditioner
Preconditioner.
ParsedTools::Function< spacedim > forcing_term
The actual function to use as a forcing term.
ParsedTools::Function< spacedim > exact_solution
The actual function to use as a exact solution when computing the errors.
ParsedTools::BoundaryConditions< spacedim > boundary_conditions
Boundary conditions used in this class.
ParsedTools::ConvergenceTable error_table
This is a wrapper around the ParsedConvergenceTable class, that allows you to specify what error to computes, and how to compute them.
ParsedTools::DataOut< dim, spacedim > data_out
Wrapper around the DataOut class.
Protected Attributes inherited from ParameterAcceptor
const std::string section_name
std::vector< std::string > subsections
Additional Inherited Members
Static Public Member Functions inherited from ParameterAcceptor
static void initialize (const std::string &filename="", const std::string &output_filename="", const ParameterHandler::OutputStyle output_style_for_output_filename=ParameterHandler::Short, ParameterHandler &prm=ParameterAcceptor::prm, const ParameterHandler::OutputStyle output_style_for_filename=ParameterHandler::DefaultStyle)
static void initialize (std::istream &input_stream, ParameterHandler &prm=ParameterAcceptor::prm)
static void clear ()
static void parse_all_parameters (ParameterHandler &prm=ParameterAcceptor::prm)
static void declare_all_parameters (ParameterHandler &prm=ParameterAcceptor::prm)
static ::ExceptionBase & ExcInUse (int arg1, std::string arg2, std::string arg3)
static ::ExceptionBase & ExcNoSubscriber (std::string arg1, std::string arg2)
Static Public Member Functions inherited from Subscriptor
static ::ExceptionBase & ExcInUse (int arg1, std::string arg2, std::string arg3)
static ::ExceptionBase & ExcNoSubscriber (std::string arg1, std::string arg2)
Public Attributes inherited from ParameterAcceptor
boost::signals2::signal< void()> declare_parameters_call_back
boost::signals2::signal< void()> parse_parameters_call_back
Static Public Attributes inherited from ParameterAcceptor
static ParameterHandler prm
Detailed Description
template<int dim, int spacedim = dim>
class PDEs::MPI::Poisson< dim, spacedim >
Solve the Poisson problem, in parallel.
Definition at line 30 of file poisson.h.
Member Typedef Documentation
ScratchData
template<int dim, int spacedim = dim> using PDEs::MPI::Poisson< dim, spacedim >::ScratchData = typename LinearProblem<dim, spacedim, LAC::LATrilinos>::ScratchData
Definition at line 45 of file poisson.h.
CopyData
template<int dim, int spacedim = dim> using PDEs::MPI::Poisson< dim, spacedim >::CopyData = typename LinearProblem<dim, spacedim, LAC::LATrilinos>::CopyData
Definition at line 48 of file poisson.h.
VectorType
template<int dim, int spacedim = dim> using PDEs::MPI::Poisson< dim, spacedim >::VectorType = typename LinearProblem<dim, spacedim, LAC::LATrilinos>::VectorType
Definition at line 51 of file poisson.h.
Constructor & Destructor Documentation
Poisson()
template<int dim, int spacedim> PDEs::MPI::Poisson< dim, spacedim >::Poisson
Constructor.
Initialize all parameters, including the base class, and make sure the class is ready to run.
Definition at line 25 of file poisson.cc.
~Poisson()
template<int dim, int spacedim = dim> virtual PDEs::MPI::Poisson< dim, spacedim >::~Poisson () virtual default
Destroy the Poisson object.
Member Function Documentation
assemble_system_one_cell()
template<int dim, int spacedim> void PDEs::MPI::Poisson< dim, spacedim >::assemble_system_one_cell (const typename DoFHandler< dim, spacedim >::active_cell_iterator & cell, ScratchData & scratch, CopyData & copy) override protected virtual
Explicitly assemble the Poisson problem on a single cell.
Definition at line 34 of file poisson.cc.
References cell_matrix(), copy(), and DoFHandler< dim, spacedim >::reinit().
solve()
template<int dim, int spacedim> void PDEs::MPI::Poisson< dim, spacedim >::solve override protected virtual
Make sure we initialize the right type of linear solver.
Reimplemented from PDEs::LinearProblem< dim, dim, LAC::LATrilinos >.
Definition at line 70 of file poisson.cc.
References inverse_operator().
Member Data Documentation
coefficient
template<int dim, int spacedim = dim> ParsedTools::Function<spacedim> PDEs::MPI::Poisson< dim, spacedim >::coefficient protected
Definition at line 69 of file poisson.h.
The documentation for this class was generated from the following files:
include/pdes/mpi/poisson.h
source/pdes/mpi/poisson.cc