Fluid structure interaction suite: ScopedLACInitializer Class Reference
ScopedLACInitializer Class Reference
General class, used to initialize different types of Vectors, Matrices and Sparsity Patterns using a common interface.
#include <lac_initializer.h>
Public Member Functions
ScopedLACInitializer (const std::vector< types::global_dof_index > &dofs_per_block, const std::vector< IndexSet > &owned, const std::vector< IndexSet > &relevant, const MPI_Comm &comm=MPI_COMM_WORLD)
void operator() (LAC::LATrilinos::BlockVector &v, bool fast=false)
Initialize a non ghosted TrilinosWrappers::MPI::BlockVector.
void ghosted (LAC::LATrilinos::BlockVector &v, bool fast=false)
Initialize a ghosted TrilinosWrappers::MPI::BlockVector.
void operator() (LAC::LAPETSc::BlockVector &v, bool fast=false)
Initialize a non ghosted TrilinosWrappers::MPI::BlockVector.
void ghosted (LAC::LAPETSc::BlockVector &v, bool fast=false)
Initialize a ghosted TrilinosWrappers::MPI::BlockVector.
void operator() (LAC::LABlockVector &v, bool fast=false)
Initialize a serial BlockVector<double>.
void ghosted (LAC::LABlockVector &v, bool fast=false)
Initiale a ghosted BlockVector<double>.
template<int dim, int spacedim>
void operator() (TrilinosWrappers::BlockSparsityPattern &s, const DoFHandler< dim, spacedim > &dh, const AffineConstraints< double > &cm, const Table< 2, DoFTools::Coupling > &coupling)
Initialize a Trilinos Sparsity Pattern.
template<int dim, int spacedim>
void operator() (BlockSparsityPattern &s, const DoFHandler< dim, spacedim > &dh, const AffineConstraints< double > &cm, const Table< 2, DoFTools::Coupling > &coupling)
Initialize a Deal.II Sparsity Pattern.
void operator() (const LAC::LABlockSparsityPattern &sparsity, LAC::LABlockSparseMatrix &matrix)
Initialize a deal.II matrix.
void operator() (const LAC::LATrilinos::BlockSparsityPattern &sparsity, LAC::LATrilinos::BlockSparseMatrix &matrix)
Initialize a Trilinos matrix.
void operator() (const LAC::LAPETSc::BlockSparsityPattern &, LAC::LAPETSc::BlockSparseMatrix &matrix)
Initialize a PETSc matrix.
Private Attributes
std::unique_ptr< BlockDynamicSparsityPattern > dsp
The dynamic sparisty pattern.
const std::vector< types::global_dof_index > & dofs_per_block
Dofs per block.
const std::vector< IndexSet > & owned
Owned dofs per block.
const std::vector< IndexSet > & relevant
Relevant dofs per block.
const MPI_Comm & comm
MPI Communicator.
Detailed Description
General class, used to initialize different types of Vectors, Matrices and Sparsity Patterns using a common interface.
Definition at line 28 of file lac_initializer.h.
Constructor & Destructor Documentation
ScopedLACInitializer()
ScopedLACInitializer::ScopedLACInitializer (const std::vector< types::global_dof_index > & dofs_per_block, const std::vector< IndexSet > & owned, const std::vector< IndexSet > & relevant, const MPI_Comm & comm = MPI_COMM_WORLD) inline
Definition at line 31 of file lac_initializer.h.
Member Function Documentation
operator()() [1/8]
void ScopedLACInitializer::operator() (LAC::LATrilinos::BlockVector & v, bool fast = false) inline
Initialize a non ghosted TrilinosWrappers::MPI::BlockVector.
Definition at line 45 of file lac_initializer.h.
References comm, owned, and TrilinosWrappers::MPI::BlockVector::reinit().
ghosted() [1/3]
void ScopedLACInitializer::ghosted (LAC::LATrilinos::BlockVector & v, bool fast = false) inline
Initialize a ghosted TrilinosWrappers::MPI::BlockVector.
Definition at line 55 of file lac_initializer.h.
References comm, owned, TrilinosWrappers::MPI::BlockVector::reinit(), and relevant.
Referenced by PDEs::LinearProblem< dim, dim, LAC::LATrilinos >::setup_system().
operator()() [2/8]
void ScopedLACInitializer::operator() (LAC::LAPETSc::BlockVector & v, bool fast = false) inline
Initialize a non ghosted TrilinosWrappers::MPI::BlockVector.
Definition at line 64 of file lac_initializer.h.
References comm, owned, and PETScWrappers::MPI::BlockVector::reinit().
ghosted() [2/3]
void ScopedLACInitializer::ghosted (LAC::LAPETSc::BlockVector & v, bool fast = false) inline
Initialize a ghosted TrilinosWrappers::MPI::BlockVector.
Definition at line 75 of file lac_initializer.h.
References comm, owned, PETScWrappers::MPI::BlockVector::reinit(), and relevant.
operator()() [3/8]
void ScopedLACInitializer::operator() (LAC::LABlockVector & v, bool fast = false) inline
Initialize a serial BlockVector<double>.
Definition at line 85 of file lac_initializer.h.
References dofs_per_block.
ghosted() [3/3]
void ScopedLACInitializer::ghosted (LAC::LABlockVector & v, bool fast = false) inline
Initiale a ghosted BlockVector<double>.
Same as above.
Definition at line 95 of file lac_initializer.h.
References dofs_per_block.
operator()() [4/8]
template<int dim, int spacedim> void ScopedLACInitializer::operator() (TrilinosWrappers::BlockSparsityPattern & s, const DoFHandler< dim, spacedim > & dh, const AffineConstraints< double > & cm, const Table< 2, DoFTools::Coupling > & coupling) inline
Initialize a Trilinos Sparsity Pattern.
Definition at line 105 of file lac_initializer.h.
References comm, TrilinosWrappers::BlockSparsityPattern::compress(), DoFTools::make_sparsity_pattern(), owned, TrilinosWrappers::BlockSparsityPattern::reinit(), relevant, and Utilities::MPI::this_mpi_process().
operator()() [5/8]
template<int dim, int spacedim> void ScopedLACInitializer::operator() (BlockSparsityPattern & s, const DoFHandler< dim, spacedim > & dh, const AffineConstraints< double > & cm, const Table< 2, DoFTools::Coupling > & coupling) inline
Initialize a Deal.II Sparsity Pattern.
Definition at line 126 of file lac_initializer.h.
References BlockSparsityPattern::copy_from(), dofs_per_block, dsp, and DoFTools::make_sparsity_pattern().
operator()() [6/8]
void ScopedLACInitializer::operator() (const LAC::LABlockSparsityPattern & sparsity, LAC::LABlockSparseMatrix & matrix) inline
Initialize a deal.II matrix.
Definition at line 143 of file lac_initializer.h.
References matrix.
operator()() [7/8]
void ScopedLACInitializer::operator() (const LAC::LATrilinos::BlockSparsityPattern & sparsity, LAC::LATrilinos::BlockSparseMatrix & matrix) inline
Initialize a Trilinos matrix.
Definition at line 154 of file lac_initializer.h.
References matrix.
operator()() [8/8]
void ScopedLACInitializer::operator() (const LAC::LAPETSc::BlockSparsityPattern & , LAC::LAPETSc::BlockSparseMatrix & matrix) inline
Initialize a PETSc matrix.
Definition at line 166 of file lac_initializer.h.
References Assert, comm, dsp, ExcNotInitialized(), matrix, and owned.
Member Data Documentation
dsp
std::unique_ptr<BlockDynamicSparsityPattern> ScopedLACInitializer::dsp private
The dynamic sparisty pattern.
Definition at line 171 of file lac_initializer.h.
Referenced by operator()().
dofs_per_block
const std::vector<types::global_dof_index>& ScopedLACInitializer::dofs_per_block private
Dofs per block.
Definition at line 183 of file lac_initializer.h.
Referenced by ghosted(), and operator()().
owned
const std::vector<IndexSet>& ScopedLACInitializer::owned private
Owned dofs per block.
Definition at line 188 of file lac_initializer.h.
Referenced by ghosted(), and operator()().
relevant
const std::vector<IndexSet>& ScopedLACInitializer::relevant private
Relevant dofs per block.
Definition at line 193 of file lac_initializer.h.
Referenced by ghosted(), and operator()().
comm
const MPI_Comm& ScopedLACInitializer::comm private
MPI Communicator.
Definition at line 198 of file lac_initializer.h.
Referenced by ghosted(), and operator()().
The documentation for this class was generated from the following file:
include/lac_initializer.h