Fluid structure interaction suite: Tools::ParsedInverseOperator Class Reference
Tools::ParsedInverseOperator Class Reference
A factory that can generate inverse operators according to parameter files.
#include <parsed_inverse_operator.h>
Public Member Functions
ParsedInverseOperator (const std::string &section_name="", const std::string &default_solver="cg", const unsigned int max_iter=1000, const double tolerance=1e-12, const double reduction=1e-12)
Store the parameters that will be needed to create a linear operator.
template<typename Domain , typename Payload , typename PreconditionerType , typename Range = Domain>
LinearOperator< Domain, Range, Payload > operator() (const LinearOperator< Range, Domain, Payload > &op, const PreconditionerType &prec) const
Create an inverse operator according to the parameters given in the parameter file.
Public Member Functions inherited from ParameterAcceptor
ParameterAcceptor (const std::string &section_name="")
virtual ~ParameterAcceptor () override
virtual void declare_parameters (ParameterHandler &prm)
virtual void parse_parameters (ParameterHandler &prm)
std::string get_section_name () const
std::vector< std::string > get_section_path () const
void add_parameter (const std::string &entry, ParameterType &parameter, const std::string &documentation="", ParameterHandler &prm_=prm, const Patterns::PatternBase &pattern=*Patterns::Tools::Convert< ParameterType >::to_pattern())
void enter_subsection (const std::string &subsection)
void leave_subsection ()
void enter_my_subsection (ParameterHandler &prm)
void leave_my_subsection (ParameterHandler &prm)
void serialize (Archive &ar, const unsigned int version)
void subscribe (std::atomic< bool > *const validity, const std::string &identifier="") const
void unsubscribe (std::atomic< bool > *const validity, const std::string &identifier="") const
unsigned int n_subscriptions () const
void list_subscribers (StreamType &stream) const
void list_subscribers () const
void subscribe (std::atomic< bool > *const validity, const std::string &identifier="") const
void unsubscribe (std::atomic< bool > *const validity, const std::string &identifier="") const
unsigned int n_subscriptions () const
void list_subscribers (StreamType &stream) const
void list_subscribers () const
Public Member Functions inherited from Subscriptor
Subscriptor ()
Subscriptor (const Subscriptor &)
Subscriptor (Subscriptor &&) noexcept
virtual ~Subscriptor ()
Subscriptor & operator= (const Subscriptor &)
Subscriptor & operator= (Subscriptor &&) noexcept
void serialize (Archive &ar, const unsigned int version)
void subscribe (std::atomic< bool > *const validity, const std::string &identifier="") const
void unsubscribe (std::atomic< bool > *const validity, const std::string &identifier="") const
unsigned int n_subscriptions () const
void list_subscribers (StreamType &stream) const
void list_subscribers () const
void subscribe (std::atomic< bool > *const validity, const std::string &identifier="") const
void unsubscribe (std::atomic< bool > *const validity, const std::string &identifier="") const
unsigned int n_subscriptions () const
void list_subscribers (StreamType &stream) const
void list_subscribers () const
Private Attributes
ReductionControl control
ReductionControl.
std::string solver_name
Solver name.
unsigned int max_iterations
Default number of maximum iterations required to succesfully complete a solution step.
double tolerance
Default reduction required to succesfully complete a solution step.
double reduction
Default reduction required to succesfully complete a solution step.
Additional Inherited Members
Static Public Member Functions inherited from ParameterAcceptor
static void initialize (const std::string &filename="", const std::string &output_filename="", const ParameterHandler::OutputStyle output_style_for_output_filename=ParameterHandler::Short, ParameterHandler &prm=ParameterAcceptor::prm, const ParameterHandler::OutputStyle output_style_for_filename=ParameterHandler::DefaultStyle)
static void initialize (std::istream &input_stream, ParameterHandler &prm=ParameterAcceptor::prm)
static void clear ()
static void parse_all_parameters (ParameterHandler &prm=ParameterAcceptor::prm)
static void declare_all_parameters (ParameterHandler &prm=ParameterAcceptor::prm)
static ::ExceptionBase & ExcInUse (int arg1, std::string arg2, std::string arg3)
static ::ExceptionBase & ExcNoSubscriber (std::string arg1, std::string arg2)
Static Public Member Functions inherited from Subscriptor
static ::ExceptionBase & ExcInUse (int arg1, std::string arg2, std::string arg3)
static ::ExceptionBase & ExcNoSubscriber (std::string arg1, std::string arg2)
Public Attributes inherited from ParameterAcceptor
boost::signals2::signal< void()> declare_parameters_call_back
boost::signals2::signal< void()> parse_parameters_call_back
Static Public Attributes inherited from ParameterAcceptor
static ParameterHandler prm
Protected Attributes inherited from ParameterAcceptor
const std::string section_name
std::vector< std::string > subsections
Detailed Description
A factory that can generate inverse operators according to parameter files.
This object is a parsed inverse operator, which uses a parameter file to select a solver type, maximum iterators, an absolute tolerance, and a relative tolerance.
Example usage is the following:
ParsedInverseOperator inverse("/", "cg", 100, 1e-12, 1e-12);
ParameterAcceptor::initialize(...);
auto Ainv = inverse(linear_operator<VEC>(A), preconditioner);
x = Ainv*b;
Definition at line 38 of file parsed_inverse_operator.h.
Constructor & Destructor Documentation
ParsedInverseOperator()
Tools::ParsedInverseOperator::ParsedInverseOperator (const std::string & section_name = "", const std::string & default_solver = "cg", const unsigned int max_iter = 1000, const double tolerance = 1e-12, const double reduction = 1e-12)
Store the parameters that will be needed to create a linear operator.
A section name can be specified, the solver type, the maximum number of iterations, and the reduction to reach convergence. If you know in advance the operators this object will need, you can also supply them here. They default to the identity, and you can assign them later by setting op and prec.
Definition at line 8 of file parsed_inverse_operator.cc.
References ParameterAcceptor::add_parameter(), max_iterations, ParameterAcceptor::prm, reduction, solver_name, and tolerance.
Member Function Documentation
operator()()
template<typename Domain , typename Payload , typename PreconditionerType , typename Range > LinearOperator< Domain, Range, Payload > Tools::ParsedInverseOperator::operator() (const LinearOperator< Range, Domain, Payload > & op, const PreconditionerType & prec) const
Create an inverse operator according to the parameters given in the parameter file.
Parameters
op The operator to invert.
preconditioner The preconditioner to use.
Definition at line 109 of file parsed_inverse_operator.h.
References Assert, control, ExcInternalError(), inverse_operator(), max_iterations, reduction, ReductionControl::set_max_steps(), ReductionControl::set_reduction(), ReductionControl::set_tolerance(), solver_name, and tolerance.
Member Data Documentation
control
ReductionControl Tools::ParsedInverseOperator::control mutable private
ReductionControl.
Used internally by the solver.
Definition at line 75 of file parsed_inverse_operator.h.
Referenced by operator()().
max_iterations
unsigned int Tools::ParsedInverseOperator::max_iterations private
Default number of maximum iterations required to succesfully complete a solution step.
Definition at line 86 of file parsed_inverse_operator.h.
Referenced by operator()(), and ParsedInverseOperator().
reduction
double Tools::ParsedInverseOperator::reduction private
Default reduction required to succesfully complete a solution step.
Definition at line 98 of file parsed_inverse_operator.h.
Referenced by operator()(), and ParsedInverseOperator().
solver_name
std::string Tools::ParsedInverseOperator::solver_name private
Solver name.
Definition at line 80 of file parsed_inverse_operator.h.
Referenced by operator()(), and ParsedInverseOperator().
tolerance
double Tools::ParsedInverseOperator::tolerance private
Default reduction required to succesfully complete a solution step.
Definition at line 92 of file parsed_inverse_operator.h.
Referenced by operator()(), and ParsedInverseOperator().
The documentation for this class was generated from the following files:
include/tools/parsed_inverse_operator.h
source/parsed_inverse_operator.cc