Fluid structure interaction suite: apps/dof_plotter.cc File Reference
dof_plotter.cc File Reference
Basic applications
Degrees of freedom plotter.
#include <deal.II/dofs/dof_handler.h>
#include <deal.II/dofs/dof_tools.h>
#include <deal.II/fe/mapping_fe.h>
#include <deal.II/grid/reference_cell.h>
#include <deal.II/lac/dynamic_sparsity_pattern.h>
#include <deal.II/lac/full_matrix.h>
#include <deal.II/lac/linear_operator_tools.h>
#include <deal.II/lac/precondition.h>
#include <deal.II/lac/sparse_direct.h>
#include <deal.II/lac/sparse_matrix.h>
#include <deal.II/lac/vector.h>
#include <deal.II/numerics/matrix_tools.h>
#include "parsed_tools/components.h"
#include "parsed_tools/data_out.h"
#include "parsed_tools/finite_element.h"
#include "parsed_tools/grid_generator.h"
#include "parsed_tools/grid_info.h"
Functions
int main (int argc, char **argv)
Detailed Description
Degrees of freedom plotter.
Illustrates the use of ParsedTools::GridGenerator, ParsedTools::FiniteElement, and ParsedTools::DataOut. It surrogates step-2 of the deal.II library, and it builds on mesh_handler.cc.
Definition in file dof_plotter.cc.
Function Documentation
main()
int main (int argc, char ** argv)
Definition at line 53 of file dof_plotter.cc.
References ParsedTools::DataOut< dim, spacedim >::add_data_vector(), ParameterHandler::add_parameter(), ParsedTools::DataOut< dim, spacedim >::attach_dof_handler(), SparsityPattern::compress(), DynamicSparsityPattern::compress(), SparsityPattern::copy_from(), MatrixCreator::create_mass_matrix(), deallog, LogStream::depth_console(), DoFHandler< dim, spacedim >::distribute_dofs(), ParsedTools::GridGenerator< dim, spacedim >::generate(), ParsedTools::Components::get_cell_quadrature(), SparseDirectUMFPACK::initialize(), ParameterAcceptor::initialize(), DoFTools::make_sparsity_pattern(), mass_matrix(), DoFHandler< dim, spacedim >::n_dofs(), ParsedTools::GridInfo::print_info(), ParameterAcceptor::prm, Utilities::MPI::this_mpi_process(), tria, SparseDirectUMFPACK::vmult(), ParsedTools::GridGenerator< dim, spacedim >::write(), and ParsedTools::DataOut< dim, spacedim >::write_data_and_clear().