Fluid structure interaction suite: apps/mesh_handler.cc File Reference
mesh_handler.cc File Reference
Basic applications
Mesh generator and reader.
#include <deal.II/base/utilities.h>
#include <deal.II/grid/reference_cell.h>
#include "argh.hpp"
#include "parsed_tools/grid_generator.h"
#include "parsed_tools/grid_info.h"
#include "runner.h"
Functions
template<int dim, int spacedim>
void run (char **argv, const std::string &input_parameter_file, const std::string &output_parameter_file)
int main (int argc, char **argv)
Detailed Description
Mesh generator and reader.
This program is useful to debug input grid files, to convert from one format to another, or simply to generate and view one of the internal deal.II grids.
The mesh_handler executable can be driven by a configuration file, or by command line arguments.
Definition in file mesh_handler.cc.
Function Documentation
run()
template<int dim, int spacedim> void run (char ** argv, const std::string & input_parameter_file, const std::string & output_parameter_file)
Definition at line 42 of file mesh_handler.cc.
References ParameterHandler::add_parameter(), deallog, LogStream::depth_console(), ParsedTools::GridGenerator< dim, spacedim >::generate(), ParameterHandler::log_parameters(), ParsedTools::GridInfo::print_info(), ParameterAcceptor::prm, setup_parameters_from_cli(), tria, and ParsedTools::GridGenerator< dim, spacedim >::write().
main()
int main (int argc, char ** argv)
Definition at line 72 of file mesh_handler.cc.
References AssertThrow, deallog, LogStream::depth_console(), ExcImpossibleInDimSpacedim(), and get_dimensions_and_parameter_files().