var modules =
[
    [ "Basic applications", "group__basics.html", null ],
    [ "Computational solid dynamic applications", "group__csd.html", null ],
    [ "Computational fluid dynamic applications", "group__cfd.html", null ],
    [ "Automatic and symbolic differentiation", "http://www.dealii.org/developer/doxygen/deal.II/group__auto__symb__diff.html", null ],
    [ "deal.II and the C++11 standard", "http://www.dealii.org/developer/doxygen/deal.II/group__CPP11.html", "group__CPP11" ],
    [ "Concepts, or expectations on template parameters", "http://www.dealii.org/developer/doxygen/deal.II/group__Concepts.html", null ],
    [ "Constraints on degrees of freedom", "http://www.dealii.org/developer/doxygen/deal.II/group__constraints.html", "group__constraints" ],
    [ "CUDA Wrappers", "http://www.dealii.org/developer/doxygen/deal.II/group__CUDAWrappers.html", "group__CUDAWrappers" ],
    [ "Parallel computing with multiple processors using distributed memory", "http://www.dealii.org/developer/doxygen/deal.II/group__distributed.html", null ],
    [ "Degrees of Freedom", "http://www.dealii.org/developer/doxygen/deal.II/group__dofs.html", "group__dofs" ],
    [ "Exceptions and assertions", "http://www.dealii.org/developer/doxygen/deal.II/group__Exceptions.html", "group__Exceptions" ],
    [ "Finite elements", "http://www.dealii.org/developer/doxygen/deal.II/group__feall.html", "group__feall" ],
    [ "Base classes", "http://www.dealii.org/developer/doxygen/deal.II/group__febase.html", null ],
    [ "Finite element access/FEValues classes", "http://www.dealii.org/developer/doxygen/deal.II/group__feaccess.html", "group__feaccess" ],
    [ "Finite element space descriptions", "http://www.dealii.org/developer/doxygen/deal.II/group__fe.html", null ],
    [ "Mappings between reference and real cell", "http://www.dealii.org/developer/doxygen/deal.II/group__mapping.html", "group__mapping" ],
    [ "How Mapping, FiniteElement, and FEValues work together", "http://www.dealii.org/developer/doxygen/deal.II/group__FE__vs__Mapping__vs__FEValues.html", null ],
    [ "Functions", "http://www.dealii.org/developer/doxygen/deal.II/group__functions.html", null ],
    [ "The geodynamics demonstration suite", "http://www.dealii.org/developer/doxygen/deal.II/group__geodynamics.html", null ],
    [ "Geometric and other primitives", "http://www.dealii.org/developer/doxygen/deal.II/group__geomprimitives.html", null ],
    [ "Grids and Triangulations", "http://www.dealii.org/developer/doxygen/deal.II/group__grid.html", "group__grid" ],
    [ "hp-finite element support", "http://www.dealii.org/developer/doxygen/deal.II/group__hp.html", "group__hp" ],
    [ "hp-Collections", "http://www.dealii.org/developer/doxygen/deal.II/group__hpcollection.html", null ],
    [ "Integrators", "http://www.dealii.org/developer/doxygen/deal.II/group__Integrators.html", "group__Integrators" ],
    [ "Input/Output", "http://www.dealii.org/developer/doxygen/deal.II/group__IO.html", "group__IO" ],
    [ "Input", "http://www.dealii.org/developer/doxygen/deal.II/group__input.html", null ],
    [ "Graphical output", "http://www.dealii.org/developer/doxygen/deal.II/group__output.html", null ],
    [ "Textual output", "http://www.dealii.org/developer/doxygen/deal.II/group__textoutput.html", null ],
    [ "Iterators on mesh-like containers", "http://www.dealii.org/developer/doxygen/deal.II/group__Iterators.html", "group__Iterators" ],
    [ "Accessor classes of the mesh iterators", "http://www.dealii.org/developer/doxygen/deal.II/group__Accessors.html", null ],
    [ "Linear algebra classes", "http://www.dealii.org/developer/doxygen/deal.II/group__LAC.html", "group__LAC" ],
    [ "Linear Operators", "http://www.dealii.org/developer/doxygen/deal.II/group__LAOperators.html", "group__LAOperators" ],
    [ "Manifold description for triangulations", "http://www.dealii.org/developer/doxygen/deal.II/group__manifold.html", "group__manifold" ],
    [ "Matrix classes", "http://www.dealii.org/developer/doxygen/deal.II/group__Matrices.html", "group__Matrices" ],
    [ "Basic matrices", "http://www.dealii.org/developer/doxygen/deal.II/group__Matrix1.html", null ],
    [ "Derived matrices", "http://www.dealii.org/developer/doxygen/deal.II/group__Matrix2.html", null ],
    [ "Matrix-free infrastructure", "http://www.dealii.org/developer/doxygen/deal.II/group__matrixfree.html", "group__matrixfree" ],
    [ "Memory handling", "http://www.dealii.org/developer/doxygen/deal.II/group__memory.html", null ],
    [ "The MeshWorker interface", "http://www.dealii.org/developer/doxygen/deal.II/group__MeshWorker.html", "group__MeshWorker" ],
    [ "Multilevel support", "http://www.dealii.org/developer/doxygen/deal.II/group__mg.html", null ],
    [ "Parallel computing with multiple processors accessing shared memory", "http://www.dealii.org/developer/doxygen/deal.II/group__threads.html", "group__threads" ],
    [ "Numerical algorithms", "http://www.dealii.org/developer/doxygen/deal.II/group__numerics.html", null ],
    [ "Parallel computing", "http://www.dealii.org/developer/doxygen/deal.II/group__Parallel.html", "group__Parallel" ],
    [ "PETScWrappers", "http://www.dealii.org/developer/doxygen/deal.II/group__PETScWrappers.html", "group__PETScWrappers" ],
    [ "Physics", "http://www.dealii.org/developer/doxygen/deal.II/group__physics.html", null ],
    [ "Polynomials and polynomial spaces", "http://www.dealii.org/developer/doxygen/deal.II/group__Polynomials.html", null ],
    [ "Preconditioners and Relaxation Operators", "http://www.dealii.org/developer/doxygen/deal.II/group__Preconditioners.html", null ],
    [ "Quadrature formulas", "http://www.dealii.org/developer/doxygen/deal.II/group__Quadrature.html", "group__Quadrature" ],
    [ "Grid reordering and cell orientation", "http://www.dealii.org/developer/doxygen/deal.II/group__reordering.html", null ],
    [ "Simplex support (experimental)", "http://www.dealii.org/developer/doxygen/deal.II/group__simplex.html", "group__simplex" ],
    [ "SLEPcWrappers", "http://www.dealii.org/developer/doxygen/deal.II/group__SLEPcWrappers.html", null ],
    [ "Linear solver classes", "http://www.dealii.org/developer/doxygen/deal.II/group__Solvers.html", null ],
    [ "Sparsity patterns", "http://www.dealii.org/developer/doxygen/deal.II/group__Sparsity.html", null ],
    [ "TrilinosWrappers", "http://www.dealii.org/developer/doxygen/deal.II/group__TrilinosWrappers.html", "group__TrilinosWrappers" ],
    [ "The interplay of UpdateFlags, Mapping, and FiniteElement in FEValues", "http://www.dealii.org/developer/doxygen/deal.II/group__UpdateFlags.html", null ],
    [ "Utility functions and classes", "http://www.dealii.org/developer/doxygen/deal.II/group__utilities.html", "group__utilities" ],
    [ "Data storage primitives", "http://www.dealii.org/developer/doxygen/deal.II/group__data.html", null ],
    [ "Vector memory management", "http://www.dealii.org/developer/doxygen/deal.II/group__VMemory.html", null ],
    [ "Handling vector valued problems", "http://www.dealii.org/developer/doxygen/deal.II/group__vector__valued.html", null ],
    [ "Vector classes", "http://www.dealii.org/developer/doxygen/deal.II/group__Vectors.html", "group__Vectors" ],
    [ "OpenCASCADE", "http://www.dealii.org/developer/doxygen/deal.II/group__OpenCASCADE.html", null ]
];