Fluid structure interaction suite: magic_enum::flags Namespace Reference
magic_enum::flags Namespace Reference
Namespaces
bitwise_operators
ostream_operators
Functions
template<typename E >
constexpr auto enum_count () noexcept -> detail::enable_if_enum_t< E, std::size_t >
template<typename E >
constexpr auto enum_value (std::size_t index) noexcept -> detail::enable_if_enum_t< E, std::decay_t< E >>
template<typename E , std::size_t I>
constexpr auto enum_value () noexcept -> detail::enable_if_enum_t< E, std::decay_t< E >>
template<typename E >
constexpr auto enum_values () noexcept -> detail::enable_if_enum_t< E, detail::values_t< E, true >>
template<typename E >
auto enum_name (E value) -> detail::enable_if_enum_t< E, string >
template<typename E >
constexpr auto enum_names () noexcept -> detail::enable_if_enum_t< E, detail::names_t< E, true >>
template<typename E >
constexpr auto enum_entries () noexcept -> detail::enable_if_enum_t< E, detail::entries_t< E, true >>
template<typename E >
constexpr auto enum_cast (underlying_type_t< E > value) noexcept -> detail::enable_if_enum_t< E, optional< std::decay_t< E >>>
template<typename E , typename BinaryPredicate >
constexpr auto enum_cast (string_view value, BinaryPredicate p) noexcept(std::is_nothrow_invocable_r_v< bool, BinaryPredicate, char, char >) -> detail::enable_if_enum_t< E, optional< std::decay_t< E >>>
template<typename E >
constexpr auto enum_cast (string_view value) noexcept -> detail::enable_if_enum_t< E, optional< std::decay_t< E >>>
template<typename E >
constexpr auto enum_index (E value) noexcept -> detail::enable_if_enum_t< E, optional< std::size_t >>
template<typename E >
constexpr auto enum_contains (E value) noexcept -> detail::enable_if_enum_t< E, bool >
template<typename E >
constexpr auto enum_contains (underlying_type_t< E > value) noexcept -> detail::enable_if_enum_t< E, bool >
template<typename E , typename BinaryPredicate >
constexpr auto enum_contains (string_view value, BinaryPredicate p) noexcept(std::is_nothrow_invocable_r_v< bool, BinaryPredicate, char, char >) -> detail::enable_if_enum_t< E, bool >
template<typename E >
constexpr auto enum_contains (string_view value) noexcept -> detail::enable_if_enum_t< E, bool >
Function Documentation
enum_cast() [1/3]
template<typename E > constexpr auto magic_enum::flags::enum_cast (string_view value) -> detail::enable_if_enum_t<E, optional<std::decay_t<E>>> constexpr noexcept
Definition at line 1061 of file magic_enum.hpp.
enum_cast() [2/3]
template<typename E , typename BinaryPredicate > constexpr auto magic_enum::flags::enum_cast (string_view value, BinaryPredicate p) -> detail::enable_if_enum_t<E, optional<std::decay_t<E>>> constexpr noexcept
Definition at line 1028 of file magic_enum.hpp.
References magic_enum::detail::cmp_equal(), d(), and magic_enum::detail::find().
enum_cast() [3/3]
template<typename E > constexpr auto magic_enum::flags::enum_cast (underlying_type_t< E > value) -> detail::enable_if_enum_t<E, optional<std::decay_t<E>>> constexpr noexcept
Definition at line 998 of file magic_enum.hpp.
References max, and min.
enum_contains() [1/4]
template<typename E > constexpr auto magic_enum::flags::enum_contains (E value) -> detail::enable_if_enum_t<E, bool> constexpr noexcept
Definition at line 1090 of file magic_enum.hpp.
enum_contains() [2/4]
template<typename E > constexpr auto magic_enum::flags::enum_contains (string_view value) -> detail::enable_if_enum_t<E, bool> constexpr noexcept
Definition at line 1116 of file magic_enum.hpp.
enum_contains() [3/4]
template<typename E , typename BinaryPredicate > constexpr auto magic_enum::flags::enum_contains (string_view value, BinaryPredicate p) -> detail::enable_if_enum_t<E, bool> constexpr noexcept
Definition at line 1107 of file magic_enum.hpp.
enum_contains() [4/4]
template<typename E > constexpr auto magic_enum::flags::enum_contains (underlying_type_t< E > value) -> detail::enable_if_enum_t<E, bool> constexpr noexcept
Definition at line 1099 of file magic_enum.hpp.
enum_count()
template<typename E > constexpr auto magic_enum::flags::enum_count () -> detail::enable_if_enum_t<E, std::size_t> constexpr noexcept
Definition at line 909 of file magic_enum.hpp.
enum_entries()
template<typename E > constexpr auto magic_enum::flags::enum_entries () -> detail::enable_if_enum_t<E, detail::entries_t<E, true>> constexpr noexcept
Definition at line 988 of file magic_enum.hpp.
enum_index()
template<typename E > constexpr auto magic_enum::flags::enum_index (E value) -> detail::enable_if_enum_t<E, optional<std::size_t>> constexpr noexcept
Definition at line 1073 of file magic_enum.hpp.
References magic_enum::detail::is_pow2().
enum_name()
template<typename E > auto magic_enum::flags::enum_name (E value) -> detail::enable_if_enum_t<E, string>
Definition at line 953 of file magic_enum.hpp.
References magic_enum::detail::n().
enum_names()
template<typename E > constexpr auto magic_enum::flags::enum_names () -> detail::enable_if_enum_t<E, detail::names_t<E, true>> constexpr noexcept
Definition at line 979 of file magic_enum.hpp.
enum_value() [1/2]
template<typename E , std::size_t I> constexpr auto magic_enum::flags::enum_value () -> detail::enable_if_enum_t<E, std::decay_t<E>> constexpr noexcept
Definition at line 933 of file magic_enum.hpp.
enum_value() [2/2]
template<typename E > constexpr auto magic_enum::flags::enum_value (std::size_t index) -> detail::enable_if_enum_t<E, std::decay_t<E>> constexpr noexcept
Definition at line 918 of file magic_enum.hpp.
References index, magic_enum::detail::log2(), and min.
enum_values()
template<typename E > constexpr auto magic_enum::flags::enum_values () -> detail::enable_if_enum_t<E, detail::values_t<E, true>> constexpr noexcept
Definition at line 943 of file magic_enum.hpp.