Fluid structure interaction suite: NonMatching Namespace Reference
NonMatching Namespace Reference
Namespaces
internal
Classes
struct AdditionalQGeneratorData
class FaceQuadratureGenerator
class FEImmersedSurfaceValues
class FEValues
class ImmersedSurfaceQuadrature
class MeshClassifier
class QuadratureGenerator
struct RegionUpdateFlags
Enumerations
enum LocationToLevelSet { LocationToLevelSet::inside, LocationToLevelSet::outside, LocationToLevelSet::intersected, LocationToLevelSet::unassigned }
Functions
void create_coupling_sparsity_pattern (const DoFHandler< dim0, spacedim > &space_dh, const DoFHandler< dim1, spacedim > &immersed_dh, const Quadrature< dim1 > &quad, Sparsity &sparsity, const AffineConstraints< number > &constraints=AffineConstraints< number >(), const ComponentMask &space_comps=ComponentMask(), const ComponentMask &immersed_comps=ComponentMask(), const Mapping< dim0, spacedim > &space_mapping=StaticMappingQ1< dim0, spacedim >::mapping, const Mapping< dim1, spacedim > &immersed_mapping=StaticMappingQ1< dim1, spacedim >::mapping, const AffineConstraints< number > &immersed_constraints=AffineConstraints< number >())
void create_coupling_sparsity_pattern (const GridTools::Cache< dim0, spacedim > &cache, const DoFHandler< dim0, spacedim > &space_dh, const DoFHandler< dim1, spacedim > &immersed_dh, const Quadrature< dim1 > &quad, Sparsity &sparsity, const AffineConstraints< number > &constraints=AffineConstraints< number >(), const ComponentMask &space_comps=ComponentMask(), const ComponentMask &immersed_comps=ComponentMask(), const Mapping< dim1, spacedim > &immersed_mapping=StaticMappingQ1< dim1, spacedim >::mapping, const AffineConstraints< number > &immersed_constraints=AffineConstraints< number >())
void create_coupling_mass_matrix (const DoFHandler< dim0, spacedim > &space_dh, const DoFHandler< dim1, spacedim > &immersed_dh, const Quadrature< dim1 > &quad, Matrix &matrix, const AffineConstraints< typename Matrix::value_type > &constraints=AffineConstraints< typename Matrix::value_type >(), const ComponentMask &space_comps=ComponentMask(), const ComponentMask &immersed_comps=ComponentMask(), const Mapping< dim0, spacedim > &space_mapping=StaticMappingQ1< dim0, spacedim >::mapping, const Mapping< dim1, spacedim > &immersed_mapping=StaticMappingQ1< dim1, spacedim >::mapping, const AffineConstraints< typename Matrix::value_type > &immersed_constraints=AffineConstraints< typename Matrix::value_type >())
void create_coupling_mass_matrix (const GridTools::Cache< dim0, spacedim > &cache, const DoFHandler< dim0, spacedim > &space_dh, const DoFHandler< dim1, spacedim > &immersed_dh, const Quadrature< dim1 > &quad, Matrix &matrix, const AffineConstraints< typename Matrix::value_type > &constraints=AffineConstraints< typename Matrix::value_type >(), const ComponentMask &space_comps=ComponentMask(), const ComponentMask &immersed_comps=ComponentMask(), const Mapping< dim1, spacedim > &immersed_mapping=StaticMappingQ1< dim1, spacedim >::mapping, const AffineConstraints< typename Matrix::value_type > &immersed_constraints=AffineConstraints< typename Matrix::value_type >())
void create_coupling_sparsity_pattern (const double &epsilon, const GridTools::Cache< dim0, spacedim > &cache0, const GridTools::Cache< dim1, spacedim > &cache1, const DoFHandler< dim0, spacedim > &dh0, const DoFHandler< dim1, spacedim > &dh1, const Quadrature< dim1 > &quad, Sparsity &sparsity, const AffineConstraints< Number > &constraints0=AffineConstraints< Number >(), const ComponentMask &comps0=ComponentMask(), const ComponentMask &comps1=ComponentMask())
void create_coupling_mass_matrix (Functions::CutOffFunctionBase< spacedim > &kernel, const double &epsilon, const GridTools::Cache< dim0, spacedim > &cache0, const GridTools::Cache< dim1, spacedim > &cache1, const DoFHandler< dim0, spacedim > &dh0, const DoFHandler< dim1, spacedim > &dh1, const Quadrature< dim0 > &quadrature0, const Quadrature< dim1 > &quadrature1, Matrix &matrix, const AffineConstraints< typename Matrix::value_type > &constraints0=AffineConstraints< typename Matrix::value_type >(), const ComponentMask &comps0=ComponentMask(), const ComponentMask &comps1=ComponentMask())
template<int dim0, int dim1, int spacedim>
Quadrature< spacedim > compute_intersection (const typename Triangulation< dim0, spacedim >::cell_iterator &cell0, const typename Triangulation< dim1, spacedim >::cell_iterator &cell1, const unsigned int degree, const Mapping< dim0, spacedim > &mapping0=(ReferenceCells::get_hypercube< dim0 >() .template get_default_linear_mapping< dim0, spacedim >()), const Mapping< dim1, spacedim > &mapping1=(ReferenceCells::get_hypercube< dim1 >() .template get_default_linear_mapping< dim1, spacedim >()))
Intersect cell0 and cell1 and construct a Quadrature<spacedim> of degree degree` over the intersection, i.e.
template<int dim0, int dim1, int spacedim>
std::vector< std::tuple< typename Triangulation< dim0, spacedim >::active_cell_iterator, typename Triangulation< dim1, spacedim >::active_cell_iterator, Quadrature< spacedim > > > compute_intersection (const GridTools::Cache< dim0, spacedim > &space_cache, const GridTools::Cache< dim1, spacedim > &immersed_cache, const unsigned int degree)
Given two triangulations cached inside GridTools::Cache objects, compute all intersections between the two and return a vector where each entry is a tuple containing iterators to the respective cells and a Quadrature<spacedim> formula to integrate over the intersection.
template<int dim0, int dim1, int spacedim, typename Sparsity , typename number = double>
void create_coupling_sparsity_pattern_with_exact_intersections (const std::vector< std::tuple< typename Triangulation< dim0, spacedim >::active_cell_iterator, typename Triangulation< dim1, spacedim >::active_cell_iterator, Quadrature< spacedim >>> &intersections_info, const DoFHandler< dim0, spacedim > &space_dh, const DoFHandler< dim1, spacedim > &immersed_dh, Sparsity &sparsity, const AffineConstraints< number > &constraints=AffineConstraints< number >(), const ComponentMask &space_comps=ComponentMask(), const ComponentMask &immersed_comps=ComponentMask(), const AffineConstraints< number > &immersed_constraints=AffineConstraints< number >())
Function Documentation
compute_intersection() [1/2]
template<int dim0, int dim1, int spacedim> Quadrature< spacedim > NonMatching::compute_intersection (const typename Triangulation< dim0, spacedim >::cell_iterator & cell0, const typename Triangulation< dim1, spacedim >::cell_iterator & cell1, const unsigned int degree, const Mapping< dim0, spacedim > & mapping0 = (ReferenceCells::get_hypercube<dim0>() .template get_default_linear_mapping<dim0, spacedim>()), const Mapping< dim1, spacedim > & mapping1 = (ReferenceCells::get_hypercube<dim1>() .template get_default_linear_mapping<dim1, spacedim>()))
Intersect cell0 and cell1 and construct a Quadrature<spacedim> of degree degree` over the intersection, i.e.
in the real space. Mappings for both cells are in mapping0 and mapping1, respectively.
Template Parameters
dim0
dim1
spacedim
Parameters
cell0 A cell_iteratator to the first cell
cell1 A cell_iteratator to the first cell
degree The degree of the Quadrature you want to build there
mapping0 The Mapping object describing the first cell
mapping1 The Mapping object describing the second cell
Returns
Quadrature<spacedim>
Definition at line 302 of file compute_intersections.cc.
References Assert, and ExcMessage().
compute_intersection() [2/2]
template<int dim0, int dim1, int spacedim> std::vector< std::tuple< typename Triangulation< dim0, spacedim >::active_cell_iterator, typename Triangulation< dim1, spacedim >::active_cell_iterator, Quadrature< spacedim > > > NonMatching::compute_intersection (const GridTools::Cache< dim0, spacedim > & space_cache, const GridTools::Cache< dim1, spacedim > & immersed_cache, const unsigned int degree)
Given two triangulations cached inside GridTools::Cache objects, compute all intersections between the two and return a vector where each entry is a tuple containing iterators to the respective cells and a Quadrature<spacedim> formula to integrate over the intersection.
Template Parameters
dim0 Intrinsic dimension of the immersed grid
dim1 Intrinsic dimension of the ambient grid
spacedim
Parameters
space_cache
immersed_cache
degree Degree of the desired quadrature formula
Returns
std::vector<std::tuple< typename Triangulation<dim0, spacedim>::active_cell_iterator, typename Triangulation<dim1, spacedim>::active_cell_iterator, Quadrature<spacedim>>>
Definition at line 289 of file compute_intersections.cc.
References Assert, and ExcMessage().
create_coupling_sparsity_pattern_with_exact_intersections()
template<int dim0, int dim1, int spacedim, typename Sparsity , typename number = double> void NonMatching::create_coupling_sparsity_pattern_with_exact_intersections (const std::vector< std::tuple< typename Triangulation< dim0, spacedim >::active_cell_iterator, typename Triangulation< dim1, spacedim >::active_cell_iterator, Quadrature< spacedim >>> & intersections_info, const DoFHandler< dim0, spacedim > & space_dh, const DoFHandler< dim1, spacedim > & immersed_dh, Sparsity & sparsity, const AffineConstraints< number > & constraints = AffineConstraints<number>(), const ComponentMask & space_comps = ComponentMask(), const ComponentMask & immersed_comps = ComponentMask(), const AffineConstraints< number > & immersed_constraints = AffineConstraints<number>())
Definition at line 142 of file create_coupling_sparsity_pattern_with_exact_intersections.cc.
References Assert, and ExcMessage().