Fluid structure interaction suite: magic_enum::detail Namespace Reference
magic_enum::detail Namespace Reference
Classes
struct char_equal_to
struct enable_if_enum
struct enable_if_enum< true, T, R >
struct is_scoped_enum
struct is_scoped_enum< T, true >
struct is_unscoped_enum
struct is_unscoped_enum< T, true >
class static_string
class static_string< 0 >
struct supported
struct underlying_type
struct underlying_type< T, true >
Typedefs
template<typename E , bool IsFlags = false, typename D = std::decay_t<E>>
using values_t = decltype((values_v< D, IsFlags >))
template<typename E , bool IsFlags = false>
using index_t = std::conditional_t< range_size_v< E, IsFlags ><(std::numeric_limits< std::uint8_t >::max)(), std::uint8_t, std::uint16_t >
template<typename E , bool IsFlags = false, typename D = std::decay_t<E>>
using names_t = decltype((names_v< D, IsFlags >))
template<typename E , bool IsFlags = false, typename D = std::decay_t<E>>
using entries_t = decltype((entries_v< D, IsFlags >))
template<typename T , typename R = void>
using enable_if_enum_t = std::enable_if_t< std::is_enum_v< std::decay_t< T > >, R >
template<typename T , typename Enable = std::enable_if_t<std::is_enum_v<std::decay_t<T>>>>
using enum_concept = T
Functions
constexpr string_view pretty_name (string_view name) noexcept
constexpr std::size_t find (string_view str, char c) noexcept
template<typename T , std::size_t N, std::size_t... I>
constexpr std::array< std::remove_cv_t< T >, N > to_array (T(&a)[N], std::index_sequence< I... >)
template<typename BinaryPredicate >
constexpr bool cmp_equal (string_view lhs, string_view rhs, BinaryPredicate &&p) noexcept(std::is_nothrow_invocable_r_v< bool, BinaryPredicate, char, char >)
template<typename L , typename R >
constexpr bool cmp_less (L lhs, R rhs) noexcept
template<typename I >
constexpr I log2 (I value) noexcept
template<typename I >
constexpr bool is_pow2 (I x) noexcept
template<typename E >
constexpr auto n () noexcept
template<typename E , E V>
constexpr auto n () noexcept
template<typename E , auto V>
constexpr bool is_valid () noexcept
template<typename E , int O, bool IsFlags = false, typename U = std::underlying_type_t<E>>
constexpr E value (std::size_t i) noexcept
template<typename E , bool IsFlags, typename U = std::underlying_type_t<E>>
constexpr int reflected_min () noexcept
template<typename E , bool IsFlags, typename U = std::underlying_type_t<E>>
constexpr int reflected_max () noexcept
template<std::size_t N>
constexpr std::size_t values_count (const bool(&valid)[N]) noexcept
template<typename E , bool IsFlags, int Min, std::size_t... I>
constexpr auto values (std::index_sequence< I... >) noexcept
template<typename E , bool IsFlags, typename U = std::underlying_type_t<E>>
constexpr auto values () noexcept
template<typename E , bool IsFlags, typename U = std::underlying_type_t<E>>
constexpr std::size_t range_size () noexcept
template<typename E , bool IsFlags, std::size_t... I>
constexpr auto indexes (std::index_sequence< I... >) noexcept
template<typename E , bool IsFlags, std::size_t... I>
constexpr auto names (std::index_sequence< I... >) noexcept
template<typename E , bool IsFlags, std::size_t... I>
constexpr auto entries (std::index_sequence< I... >) noexcept
template<typename E , bool IsFlags, typename U = std::underlying_type_t<E>>
constexpr bool is_sparse () noexcept
template<typename E , typename U = std::underlying_type_t<E>>
constexpr std::size_t undex (U value) noexcept
template<typename E , typename U = std::underlying_type_t<E>>
constexpr std::size_t endex (E value) noexcept
template<typename E , typename U = std::underlying_type_t<E>>
constexpr U value_ors () noexcept
Variables
template<typename T >
constexpr bool is_enum_v = std::is_enum_v<T> && std::is_same_v<T, std::decay_t<T>>
template<typename E >
constexpr auto type_name_v = n<E>()
template<typename E , E V>
constexpr auto enum_name_v = n<E, V>()
template<typename E , bool IsFlags = false>
constexpr auto reflected_min_v = reflected_min<E, IsFlags>()
template<typename E , bool IsFlags = false>
constexpr auto reflected_max_v = reflected_max<E, IsFlags>()
template<typename E , bool IsFlags = false>
constexpr auto values_v = values<E, IsFlags>()
template<typename E , bool IsFlags = false>
constexpr auto count_v = values_v<E, IsFlags>.size()
template<typename E , bool IsFlags = false, typename U = std::underlying_type_t<E>>
constexpr auto min_v = (count_v<E, IsFlags> > 0) ? static_cast<U>(values_v<E, IsFlags>.front()) : U{0}
template<typename E , bool IsFlags = false, typename U = std::underlying_type_t<E>>
constexpr auto max_v = (count_v<E, IsFlags> > 0) ? static_cast<U>(values_v<E, IsFlags>.back()) : U{0}
template<typename E , bool IsFlags = false>
constexpr auto range_size_v = range_size<E, IsFlags>()
template<typename E , bool IsFlags = false>
constexpr auto invalid_index_v = (std::numeric_limits<index_t<E, IsFlags>>::max)()
template<typename E , bool IsFlags = false>
constexpr auto indexes_v = indexes<E, IsFlags>(std::make_index_sequence<range_size_v<E, IsFlags>>{})
template<typename E , bool IsFlags = false>
constexpr auto names_v = names<E, IsFlags>(std::make_index_sequence<count_v<E, IsFlags>>{})
template<typename E , bool IsFlags = false>
constexpr auto entries_v = entries<E, IsFlags>(std::make_index_sequence<count_v<E, IsFlags>>{})
template<typename E , bool IsFlags = false>
constexpr bool is_sparse_v = is_sparse<E, IsFlags>()
Typedef Documentation
enable_if_enum_t
template<typename T , typename R = void> using magic_enum::detail::enable_if_enum_t = typedef std::enable_if_t<std::is_enum_v<std::decay_t<T> >, R>
Definition at line 601 of file magic_enum.hpp.
entries_t
template<typename E , bool IsFlags = false, typename D = std::decay_t<E>> using magic_enum::detail::entries_t = typedef decltype((entries_v<D, IsFlags>))
Definition at line 542 of file magic_enum.hpp.
enum_concept
template<typename T , typename Enable = std::enable_if_t<std::is_enum_v<std::decay_t<T>>>> using magic_enum::detail::enum_concept = typedef T
Definition at line 604 of file magic_enum.hpp.
index_t
template<typename E , bool IsFlags = false> using magic_enum::detail::index_t = typedef std::conditional_t<range_size_v<E, IsFlags> < (std::numeric_limits<std::uint8_t>::max)(), std::uint8_t, std::uint16_t>
Definition at line 501 of file magic_enum.hpp.
names_t
template<typename E , bool IsFlags = false, typename D = std::decay_t<E>> using magic_enum::detail::names_t = typedef decltype((names_v<D, IsFlags>))
Definition at line 529 of file magic_enum.hpp.
values_t
template<typename E , bool IsFlags = false, typename D = std::decay_t<E>> using magic_enum::detail::values_t = typedef decltype((values_v<D, IsFlags>))
Definition at line 474 of file magic_enum.hpp.
Function Documentation
cmp_equal()
template<typename BinaryPredicate > constexpr bool magic_enum::detail::cmp_equal (string_view lhs, string_view rhs, BinaryPredicate && p) constexpr noexcept
Definition at line 249 of file magic_enum.hpp.
Referenced by magic_enum::enum_cast(), and magic_enum::flags::enum_cast().
cmp_less()
template<typename L , typename R > constexpr bool magic_enum::detail::cmp_less (L lhs, R rhs) constexpr noexcept
Definition at line 280 of file magic_enum.hpp.
Referenced by reflected_max(), and reflected_min().
endex()
template<typename E , typename U = std::underlying_type_t<E>> constexpr std::size_t magic_enum::detail::endex (E value) constexpr noexcept
Definition at line 572 of file magic_enum.hpp.
References value().
entries()
template<typename E , bool IsFlags, std::size_t... I> constexpr auto magic_enum::detail::entries (std::index_sequence< I... >) constexpr noexcept
Definition at line 532 of file magic_enum.hpp.
find()
constexpr std::size_t magic_enum::detail::find (string_view str, char c) constexpr noexcept
Definition at line 221 of file magic_enum.hpp.
Referenced by magic_enum::flags::enum_cast(), Tools::ParsedFiniteElement< dim, spacedim >::get_first_occurence(), and Tools::ParsedFiniteElement< dim, spacedim >::is_vector().
indexes()
template<typename E , bool IsFlags, std::size_t... I> constexpr auto magic_enum::detail::indexes (std::index_sequence< I... >) constexpr noexcept
Definition at line 507 of file magic_enum.hpp.
References log2(), and min.
is_pow2()
template<typename I > constexpr bool magic_enum::detail::is_pow2 (I x) constexpr noexcept
Definition at line 310 of file magic_enum.hpp.
Referenced by magic_enum::flags::enum_index().
is_sparse()
template<typename E , bool IsFlags, typename U = std::underlying_type_t<E>> constexpr bool magic_enum::detail::is_sparse () constexpr noexcept
Definition at line 545 of file magic_enum.hpp.
is_valid()
template<typename E , auto V> constexpr bool magic_enum::detail::is_valid () constexpr noexcept
Definition at line 365 of file magic_enum.hpp.
Referenced by reflected_max(), and reflected_min().
log2()
template<typename I > constexpr I magic_enum::detail::log2 (I value) constexpr noexcept
Definition at line 300 of file magic_enum.hpp.
References value().
Referenced by magic_enum::flags::enum_value(), indexes(), and range_size().
n() [1/2]
template<typename E > constexpr auto magic_enum::detail::n () constexpr noexcept
Definition at line 320 of file magic_enum.hpp.
References magic_enum::detail::static_string< N >::size().
n() [2/2]
template<typename E , E V> constexpr auto magic_enum::detail::n () constexpr noexcept
Definition at line 340 of file magic_enum.hpp.
References pretty_name(), and magic_enum::detail::static_string< N >::size().
Referenced by magic_enum::flags::enum_name().
names()
template<typename E , bool IsFlags, std::size_t... I> constexpr auto magic_enum::detail::names (std::index_sequence< I... >) constexpr noexcept
Definition at line 519 of file magic_enum.hpp.
Referenced by Tools::ParsedConstants::ParsedConstants().
pretty_name()
constexpr string_view magic_enum::detail::pretty_name (string_view name) constexpr noexcept
Definition at line 195 of file magic_enum.hpp.
Referenced by n().
range_size()
template<typename E , bool IsFlags, typename U = std::underlying_type_t<E>> constexpr std::size_t magic_enum::detail::range_size () constexpr noexcept
Definition at line 486 of file magic_enum.hpp.
References log2(), max, and min.
Referenced by values().
reflected_max()
template<typename E , bool IsFlags, typename U = std::underlying_type_t<E>> constexpr int magic_enum::detail::reflected_max () constexpr noexcept
Definition at line 402 of file magic_enum.hpp.
References cmp_less(), E(), and is_valid().
reflected_min()
template<typename E , bool IsFlags, typename U = std::underlying_type_t<E>> constexpr int magic_enum::detail::reflected_min () constexpr noexcept
Definition at line 383 of file magic_enum.hpp.
References cmp_less(), E(), and is_valid().
to_array()
template<typename T , std::size_t N, std::size_t... I> constexpr std::array<std::remove_cv_t<T>, N> magic_enum::detail::to_array (T(&) a[N], std::index_sequence< I... >) constexpr
Definition at line 244 of file magic_enum.hpp.
Referenced by values().
undex()
template<typename E , typename U = std::underlying_type_t<E>> constexpr std::size_t magic_enum::detail::undex (U value) constexpr noexcept
Definition at line 555 of file magic_enum.hpp.
References value().
value()
template<typename E , int O, bool IsFlags = false, typename U = std::underlying_type_t<E>> constexpr E magic_enum::detail::value (std::size_t i) constexpr noexcept
Definition at line 372 of file magic_enum.hpp.
References E().
Referenced by endex(), log2(), undex(), and value_ors().
value_ors()
template<typename E , typename U = std::underlying_type_t<E>> constexpr U magic_enum::detail::value_ors () constexpr noexcept
Definition at line 579 of file magic_enum.hpp.
References value().
values() [1/2]
template<typename E , bool IsFlags, typename U = std::underlying_type_t<E>> constexpr auto magic_enum::detail::values () constexpr noexcept
Definition at line 459 of file magic_enum.hpp.
References max, min, and range_size().
values() [2/2]
template<typename E , bool IsFlags, int Min, std::size_t... I> constexpr auto magic_enum::detail::values (std::index_sequence< I... >) constexpr noexcept
Definition at line 439 of file magic_enum.hpp.
References E(), to_array(), valid, and values_count().
values_count()
template<std::size_t N> constexpr std::size_t magic_enum::detail::values_count (const bool(&) valid[N]) constexpr noexcept
Definition at line 427 of file magic_enum.hpp.
References valid.
Referenced by values().
Variable Documentation
count_v
template<typename E , bool IsFlags = false> constexpr auto magic_enum::detail::count_v = values_v<E, IsFlags>.size() inline constexpr
Definition at line 477 of file magic_enum.hpp.
entries_v
template<typename E , bool IsFlags = false> constexpr auto magic_enum::detail::entries_v = entries<E, IsFlags>(std::make_index_sequence<count_v<E, IsFlags>>{}) inline constexpr
Definition at line 539 of file magic_enum.hpp.
enum_name_v
template<typename E , E V> constexpr auto magic_enum::detail::enum_name_v = n<E, V>() inline constexpr
Definition at line 362 of file magic_enum.hpp.
indexes_v
template<typename E , bool IsFlags = false> constexpr auto magic_enum::detail::indexes_v = indexes<E, IsFlags>(std::make_index_sequence<range_size_v<E, IsFlags>>{}) inline constexpr
Definition at line 516 of file magic_enum.hpp.
invalid_index_v
template<typename E , bool IsFlags = false> constexpr auto magic_enum::detail::invalid_index_v = (std::numeric_limits<index_t<E, IsFlags>>::max)() inline constexpr
Definition at line 504 of file magic_enum.hpp.
is_enum_v
template<typename T > constexpr bool magic_enum::detail::is_enum_v = std::is_enum_v<T> && std::is_same_v<T, std::decay_t<T>> inline constexpr
Definition at line 317 of file magic_enum.hpp.
is_sparse_v
template<typename E , bool IsFlags = false> constexpr bool magic_enum::detail::is_sparse_v = is_sparse<E, IsFlags>() inline constexpr
Definition at line 552 of file magic_enum.hpp.
max_v
template<typename E , bool IsFlags = false, typename U = std::underlying_type_t<E>> constexpr auto magic_enum::detail::max_v = (count_v<E, IsFlags> > 0) ? static_cast<U>(values_v<E, IsFlags>.back()) : U{0} inline constexpr
Definition at line 483 of file magic_enum.hpp.
min_v
template<typename E , bool IsFlags = false, typename U = std::underlying_type_t<E>> constexpr auto magic_enum::detail::min_v = (count_v<E, IsFlags> > 0) ? static_cast<U>(values_v<E, IsFlags>.front()) : U{0} inline constexpr
Definition at line 480 of file magic_enum.hpp.
names_v
template<typename E , bool IsFlags = false> constexpr auto magic_enum::detail::names_v = names<E, IsFlags>(std::make_index_sequence<count_v<E, IsFlags>>{}) inline constexpr
Definition at line 526 of file magic_enum.hpp.
range_size_v
template<typename E , bool IsFlags = false> constexpr auto magic_enum::detail::range_size_v = range_size<E, IsFlags>() inline constexpr
Definition at line 498 of file magic_enum.hpp.
reflected_max_v
template<typename E , bool IsFlags = false> constexpr auto magic_enum::detail::reflected_max_v = reflected_max<E, IsFlags>() inline constexpr
Definition at line 424 of file magic_enum.hpp.
reflected_min_v
template<typename E , bool IsFlags = false> constexpr auto magic_enum::detail::reflected_min_v = reflected_min<E, IsFlags>() inline constexpr
Definition at line 421 of file magic_enum.hpp.
type_name_v
template<typename E > constexpr auto magic_enum::detail::type_name_v = n<E>() inline constexpr
Definition at line 337 of file magic_enum.hpp.
values_v
template<typename E , bool IsFlags = false> constexpr auto magic_enum::detail::values_v = values<E, IsFlags>() inline constexpr
Definition at line 471 of file magic_enum.hpp.