Fluid structure interaction suite: magic_enum::bitwise_operators Namespace Reference
magic_enum::bitwise_operators Namespace Reference
Functions
template<typename E , std::enable_if_t< std::is_enum_v< E >, int > = 0>
constexpr E operator~ (E rhs) noexcept
template<typename E , std::enable_if_t< std::is_enum_v< E >, int > = 0>
constexpr E operator| (E lhs, E rhs) noexcept
template<typename E , std::enable_if_t< std::is_enum_v< E >, int > = 0>
constexpr E operator& (E lhs, E rhs) noexcept
template<typename E , std::enable_if_t< std::is_enum_v< E >, int > = 0>
constexpr E operator^ (E lhs, E rhs) noexcept
template<typename E , std::enable_if_t< std::is_enum_v< E >, int > = 0>
constexpr E & operator|= (E &lhs, E rhs) noexcept
template<typename E , std::enable_if_t< std::is_enum_v< E >, int > = 0>
constexpr E & operator&= (E &lhs, E rhs) noexcept
template<typename E , std::enable_if_t< std::is_enum_v< E >, int > = 0>
constexpr E & operator^= (E &lhs, E rhs) noexcept
Function Documentation
operator&()
template<typename E , std::enable_if_t< std::is_enum_v< E >, int > = 0> constexpr E magic_enum::bitwise_operators::operator& (E lhs, E rhs) constexpr noexcept
Definition at line 876 of file magic_enum.hpp.
References E().
operator&=()
template<typename E , std::enable_if_t< std::is_enum_v< E >, int > = 0> constexpr E& magic_enum::bitwise_operators::operator&= (E & lhs, E rhs) constexpr noexcept
Definition at line 891 of file magic_enum.hpp.
References E().
operator^()
template<typename E , std::enable_if_t< std::is_enum_v< E >, int > = 0> constexpr E magic_enum::bitwise_operators::operator^ (E lhs, E rhs) constexpr noexcept
Definition at line 881 of file magic_enum.hpp.
References E().
operator^=()
template<typename E , std::enable_if_t< std::is_enum_v< E >, int > = 0> constexpr E& magic_enum::bitwise_operators::operator^= (E & lhs, E rhs) constexpr noexcept
Definition at line 896 of file magic_enum.hpp.
References E().
operator|()
template<typename E , std::enable_if_t< std::is_enum_v< E >, int > = 0> constexpr E magic_enum::bitwise_operators::operator| (E lhs, E rhs) constexpr noexcept
Definition at line 871 of file magic_enum.hpp.
References E().
operator|=()
template<typename E , std::enable_if_t< std::is_enum_v< E >, int > = 0> constexpr E& magic_enum::bitwise_operators::operator|= (E & lhs, E rhs) constexpr noexcept
Definition at line 886 of file magic_enum.hpp.
References E().
operator~()
template<typename E , std::enable_if_t< std::is_enum_v< E >, int > = 0> constexpr E magic_enum::bitwise_operators::operator~ (E rhs) constexpr noexcept
Definition at line 866 of file magic_enum.hpp.
References E().