Fluid structure interaction suite: include/runner.h File Reference
runner.h File Reference
#include <deal.II/base/parameter_handler.h>
#include <deal.II/base/utilities.h>
#include "argh.hpp"
#include "text_flow.hpp"
Macros
#define RUNNER_DIM(ClassName, ParameterName, argc, argv)
Body of the main function for a program that runs a simulation in dimension dim only using the ParameterAcceptor class, dimensions 1, 2, and 3.
#define RUNNER_DIM_NO_ONE(ClassName, ParameterName, argc, argv)
Body of the main function for a program that runs a simulation in dimensions two or three using the ParameterAcceptor class.
#define RUNNER_DIM_SPACEDIM(ClassName, ParameterName, argc, argv)
Body of the main function for a program that runs a simulation in dim and spacedim, using the ParameterAcceptor class.
#define RUNNER_DIM_SPACEDIM_NO_ONE(ClassName, ParameterName, argc, argv)
Body of the main function for a program that runs a simulation in dim and spacedim, using the ParameterAcceptor class.
Functions
std::tuple< int, int, std::string, std::string > get_dimensions_and_parameter_files (char **argv)
Parse from the command line the parameter file names (both input and output) and the running dimensions (both dim and spacedim).
int setup_parameters_from_cli (char **argv, const std::string &input_parameter_file, const std::string &output_parameter_file)
Setup the ParameterAcceptor::prm according to the parameters specified in the parameter file, and the parameters specified from the command line.
Macro Definition Documentation
RUNNER_DIM
#define RUNNER_DIM (ClassName, ParameterName, argc, argv)
Value:
  try                                                                      \
    {                                                                      \
      Utilities::MPI::MPI_InitFinalize mpi_initialization(argc, argv);     \
      std::string                      par_name = ParameterName "_2d.prm"; \
      if (argc > 1)                                                        \
        par_name = argv[1];                                                \
                                                                           \
      RUN_DIM(ClassName, par_name) else                                    \
      {                                                                    \
        AssertThrow(false,                                                 \
                    ExcMessage("The parameter file name should contain "   \
                               "either 1d, 2d, or 3d"));                   \
      }                                                                    \
    }                                                                      \
  STANDARD_CATCH()
Body of the main function for a program that runs a simulation in dimension dim only using the ParameterAcceptor class, dimensions 1, 2, and 3.
Definition at line 441 of file runner.h.
RUNNER_DIM_NO_ONE
#define RUNNER_DIM_NO_ONE (ClassName, ParameterName, argc, argv)
Value:
  try                                                                      \
    {                                                                      \
      Utilities::MPI::MPI_InitFinalize mpi_initialization(argc, argv);     \
      std::string                      par_name = ParameterName "_2d.prm"; \
      if (argc > 1)                                                        \
        par_name = argv[1];                                                \
                                                                           \
      RUN_DIM_NO_ONE(ClassName, par_name) else                             \
      {                                                                    \
        AssertThrow(false,                                                 \
                    ExcMessage("The parameter file name should contain "   \
                               "either 2d or 3d"));                        \
      }                                                                    \
    }                                                                      \
  STANDARD_CATCH()
Body of the main function for a program that runs a simulation in dimensions two or three using the ParameterAcceptor class.
Not instantiated for dimension one.
Definition at line 463 of file runner.h.
RUNNER_DIM_SPACEDIM
#define RUNNER_DIM_SPACEDIM (ClassName, ParameterName, argc, argv)
Value:
  try                                                                      \
    {                                                                      \
      Utilities::MPI::MPI_InitFinalize mpi_initialization(argc, argv);     \
      std::string                      par_name = ParameterName "_2d.prm"; \
      if (argc > 1)                                                        \
        par_name = argv[1];                                                \
                                                                           \
      RUN_DIM_SPACEDIM(ClassName, par_name)                                \
      else RUN_DIM(ClassName, par_name) else                               \
      {                                                                    \
        AssertThrow(false,                                                 \
                    ExcMessage("The parameter file name should contain "   \
                               "either  1d, 1d_2d, 2d, 2d_3d, or 3d"));    \
      }                                                                    \
    }                                                                      \
  STANDARD_CATCH()
Body of the main function for a program that runs a simulation in dim and spacedim, using the ParameterAcceptor class.
Instantiate for <1,1>, <1,2>, <2,2>, <2,3>, and <3,3>
Definition at line 485 of file runner.h.
RUNNER_DIM_SPACEDIM_NO_ONE
#define RUNNER_DIM_SPACEDIM_NO_ONE (ClassName, ParameterName, argc, argv)
Value:
  try                                                                      \
    {                                                                      \
      Utilities::MPI::MPI_InitFinalize mpi_initialization(argc, argv);     \
      std::string                      par_name = ParameterName "_2d.prm"; \
      if (argc > 1)                                                        \
        par_name = argv[1];                                                \
                                                                           \
      RUN_DIM_SPACEDIM(ClassName, par_name)                                \
      else RUN_DIM_NO_ONE(ClassName, par_name) else                        \
      {                                                                    \
        AssertThrow(false,                                                 \
                    ExcMessage("The parameter file name should contain "   \
                               "either 1d_2d, 2d_3d, 2d, or 3d"));         \
      }                                                                    \
    }                                                                      \
  STANDARD_CATCH()
Body of the main function for a program that runs a simulation in dim and spacedim, using the ParameterAcceptor class.
Instantiate for <1,2>, <2,2>, <2,3>, and <3,3>
Definition at line 508 of file runner.h.
Function Documentation
get_dimensions_and_parameter_files()
std::tuple<int, int, std::string, std::string> get_dimensions_and_parameter_files (char ** argv)
Parse from the command line the parameter file names (both input and output) and the running dimensions (both dim and spacedim).
This function uses the command line interface parsers from the argh library (https://github.com/adishavit/argh), and recognizes the following parameters from the command line:
./your_code_here --help
Usage: ./your_code_here [OPTIONS] [PRM FILE]
Options:
-h, --help                        Print this help message
-p, --prm_file <filename>         Input parameter file. Defaults to the
                                  empty string (meaning: use the default
                                  values, or the values specified on the
                                  command line). Notice that you can
                                  specify the input paramter file also as
                                  the first positional arguement to the
                                  program.
-o, --output_prm_file <filename>  Where to write the file containing the
                                  actual parameters used in this run of
                                  the program. It defaults to the string
                                  `used_./mesh_handler' followed by a
                                  string of the type '1d_2d' containing
                                  the dimension and the spacedimension at
                                  which the program was run if the input
                                  parameter file is not specified,
                                  otherwise it defaults to the string
                                  `used_' followed by the name of the
                                  input parameter file.
-d, --dim <value>                 Dimension at which this program should
                                  be run. Defaults to 2.
-s, --spacedim <value>            Space dimension at which this program
                                  should run. Defaults to 2.
-"Section/option name"=<value>    Any of the options that you can specify
                                  in the parameter file. The format here
                                  is the following: -"Section/Subsection/
                                  option"="value,another value", where the
                                  quotes are required only if an otpion
                                  contains spaces, or if a value contains
                                  separators, like commas, columns, etc.
Warning
This function is usually called before any class initialization takes place. You should use this function in conjunction with its companion function setup_parameters_from_cli() after you have initialized your classes and ParameterAcceptor::initialize() has been called at least once.
Example usage (assuming you have a class called MyClass derived from ParameterAcceptor):
int main(int argc, char **argv) {
 auto [dim, spacedim, infile, outfile] =
      get_dimensions_and_parameter_files(argv);
 // do something with dim and spacedim...
 MyClass<dimpar, spacedimpar> my_class;
 ParameterAcceptor::initialize();
 // Check we were not asked to print help message
 if(setup_parameters_from_cli(argv, infile, outfile) == -1)
   return 0;
 my_class.run();
}
Parameters
argv Arguments of the command line.
Returns
(dim, spacedim, input_parameters, output_parameters) Desired dimension and spacedimesion of the problem to run, and input and output parameter filenames.
Definition at line 99 of file runner.h.
References deallog.
Referenced by main().
setup_parameters_from_cli()
int setup_parameters_from_cli (char ** argv, const std::string & input_parameter_file, const std::string & output_parameter_file)
Setup the ParameterAcceptor::prm according to the parameters specified in the parameter file, and the parameters specified from the command line.
This function uses the command line interface parsers from the argh library (https://github.com/adishavit/argh), and allows you to specify input parameter files, output parameter files, and to change any option recognized by the parameter file itself from the command line.
This function is usually used in conjunction with the function get_dimensions_and_parameter_files(), in order to ask from the command line what simulation to run (1d, 2d, 3d, etc.), and what input parameter files to read from. These are then passed to this function, after you have called at least once ParameterAcceptor::initialize() on your classes (which you will have instantiated with the correct dimension thanks to the function above).
Example usage (assuming you have a class called MyClass derived from ParameterAcceptor):
int main(int argc, char **argv) {
 auto [dim, spacedim, infile, outfile] =
      get_dimensions_and_parameter_files(argv);
 // do something with dim and spacedim...
 if(dim == 2 && spacedim == 2) {
   MyClass<2, 2> my_class;
   ParameterAcceptor::initialize();
   // Check we were not asked to print help message
   if(setup_parameters_from_cli(argv, infile, outfile) == -1)
     return 0;
   my_class.run();
 }
}
If the option -h or --help is found on the command line, this function outputs the following help message:
./your_code_here --help
Usage: ./your_code_here [OPTIONS] [PRM FILE]
Options:
-h, --help                        Print this help message
-p, --prm_file <filename>         Input parameter file. Defaults to the
                                  empty string (meaning: use the default
                                  values, or the values specified on the
                                  command line). Notice that you can
                                  specify the input paramter file also as
                                  the first positional arguement to the
                                  program.
-o, --output_prm_file <filename>  Where to write the file containing the
                                  actual parameters used in this run of
                                  the program. It defaults to the string
                                  `used_./mesh_handler' followed by a
                                  string of the type '1d_2d' containing
                                  the dimension and the spacedimension at
                                  which the program was run if the input
                                  parameter file is not specified,
                                  otherwise it defaults to the string
                                  `used_' followed by the name of the
                                  input parameter file.
-d, --dim <value>                 Dimension at which this program should
                                  be run. Defaults to 2.
-s, --spacedim <value>            Space dimension at which this program
                                  should run. Defaults to 2.
-"Section/option name"=<value>    Any of the options that you can specify
                                  in the parameter file. The format here
                                  is the following: -"Section/Subsection/
                                  option"="value,another value", where the
                                  quotes are required only if an otpion
                                  contains spaces, or if a value contains
                                  separators, like commas, columns, etc.
followed by a list of the options that are recognized by the parameter file, i.e., for the mesh_handler.cc application, we get:
...
-"Section/option name"=<value>     Any of the options that you can specify
                                   in the parameter file. The format here
                                   is the following: -"Section/Subsection/
                                   option"="value,another value", where the
                                   quotes are required only if an otpion
                                   contains spaces, or if a value contains
                                   separators, like commas, columns, etc.
Listing of Parameters:
set Arguments                  =   Any string
set Initial grid refinement    =   An integer
set Input name                 =   Any string
set Output name                =   Any string
set Transform to simplex grid  =   A boolean value (true or false)
set Verbosity                  =   An integer n such that -1 <= n <=
2147483647
Returns
0: everything is fine, 1: unused parameters, -1: help printed
Definition at line 246 of file runner.h.
References b(), deallog, ParameterHandler::Description, ParameterHandler::enter_subsection(), ParameterAcceptor::initialize(), ParameterHandler::KeepDeclarationOrder, ParameterHandler::leave_subsection(), ParameterHandler::print_parameters(), ParameterAcceptor::prm, sec(), ParameterHandler::set(), ParameterHandler::Short, and Utilities::split_string_list().
Referenced by run().