Fluid structure interaction suite: dealii::Patterns::Tools::Convert< Differentiation::SD::Expression > Struct Reference
dealii::Patterns::Tools::Convert< Differentiation::SD::Expression > Struct Reference
Helper class to parse symbolic expressions.
#include <symbolic_function.h>
Public Types
using T = Differentiation::SD::Expression
Shorthand for the type of the parsed expression.
Static Public Member Functions
static std::unique_ptr< Patterns::PatternBase > to_pattern ()
Default pattern for parsing symbolic expressions.
static std::string to_string (const T &t, const Patterns::PatternBase &pattern= *to_pattern())
Convert a Differentiation::SD::Expression expression to a string.
static T to_value (const std::string &s, const Patterns::PatternBase &pattern= *to_pattern())
Convert a string to a Differentiation::SD::Expression expression.
Detailed Description
Helper class to parse symbolic expressions.
Definition at line 36 of file symbolic_function.h.
Member Typedef Documentation
T
using dealii::Patterns::Tools::Convert< Differentiation::SD::Expression >::T = Differentiation::SD::Expression
Shorthand for the type of the parsed expression.
Definition at line 41 of file symbolic_function.h.
Member Function Documentation
to_pattern()
static std::unique_ptr<Patterns::PatternBase> dealii::Patterns::Tools::Convert< Differentiation::SD::Expression >::to_pattern () inline static
Default pattern for parsing symbolic expressions.
Since we don't really have many restrictions, this pattern is simply the Patterns::Anything() pattern.
Definition at line 50 of file symbolic_function.h.
References Patterns::Anything::clone().
to_string()
static std::string dealii::Patterns::Tools::Convert< Differentiation::SD::Expression >::to_string (const T & t, const Patterns::PatternBase & pattern = *to_pattern()) inline static
Convert a Differentiation::SD::Expression expression to a string.
Definition at line 59 of file symbolic_function.h.
References AssertThrow, and ExcMessage().
to_value()
static T dealii::Patterns::Tools::Convert< Differentiation::SD::Expression >::to_value (const std::string & s, const Patterns::PatternBase & pattern = *to_pattern()) inline static
Convert a string to a Differentiation::SD::Expression expression.
Definition at line 76 of file symbolic_function.h.
References AssertThrow, and ExcMessage().
The documentation for this struct was generated from the following file:
include/parsed_tools/symbolic_function.h