Fluid structure interaction suite: dealii::Patterns::Tools::Convert< T, typename std::enable_if< std::is_enum< T >::value >::type > Struct Template Reference
dealii::Patterns::Tools::Convert< T, typename std::enable_if< std::is_enum< T >::value >::type > Struct Template Reference
Helper class to convert enum types to strings and viceversa.
#include <enum.h>
Static Public Member Functions
static std::unique_ptr< Patterns::PatternBase > to_pattern ()
static std::string to_string (const T &value, const Patterns::PatternBase &p= *Convert< T >::to_pattern())
static T to_value (const std::string &s, const Patterns::PatternBase &p= *to_pattern())
Detailed Description
template<class T>
struct dealii::Patterns::Tools::Convert< T, typename std::enable_if< std::is_enum< T >::value >::type >
Helper class to convert enum types to strings and viceversa.
Definition at line 35 of file enum.h.
Member Function Documentation
to_pattern()
template<class T > static std::unique_ptr<Patterns::PatternBase> dealii::Patterns::Tools::Convert< T, typename std::enable_if< std::is_enum< T >::value >::type >::to_pattern () inline static
Definition at line 38 of file enum.h.
References Patterns::List::clone().
to_string()
template<class T > static std::string dealii::Patterns::Tools::Convert< T, typename std::enable_if< std::is_enum< T >::value >::type >::to_string (const T & value, const Patterns::PatternBase & p = *Convert<T>::to_pattern()) inline static
Definition at line 56 of file enum.h.
References value, and values.
to_value()
template<class T > static T dealii::Patterns::Tools::Convert< T, typename std::enable_if< std::is_enum< T >::value >::type >::to_value (const std::string & s, const Patterns::PatternBase & p = *to_pattern()) inline static
Definition at line 69 of file enum.h.
References AssertThrow, ExcNoMatch(), operator|(), and value.
The documentation for this struct was generated from the following file:
include/parsed_tools/enum.h