Fluid structure interaction suite: Tools::GridInfo< dim, spacedim > Struct Template Reference
Tools::GridInfo< dim, spacedim > Struct Template Reference
Public Member Functions
GridInfo (const Triangulation< dim, spacedim > &tria, const unsigned int info_level=0)
template<typename StreamType >
void print_info (StreamType &out)
Public Attributes
unsigned int info_level
unsigned int n_active_cells
unsigned int n_vertices
unsigned int n_used_vertices
unsigned int n_levels
std::vector< unsigned int > n_active_cells_at_level
std::vector< unsigned int > n_cells_at_level
std::vector< types::boundary_id > boundary_ids
std::vector< types::material_id > material_ids
std::vector< types::manifold_id > manifold_ids
std::vector< ReferenceCell > reference_cell_types
Detailed Description
template<int dim, int spacedim>
struct Tools::GridInfo< dim, spacedim >
Definition at line 79 of file mesh_handler.cc.
Constructor & Destructor Documentation
GridInfo()
template<int dim, int spacedim> Tools::GridInfo< dim, spacedim >::GridInfo (const Triangulation< dim, spacedim > & tria, const unsigned int info_level = 0) inline
Definition at line 81 of file mesh_handler.cc.
References n_active_cells(), and tria.
Member Function Documentation
print_info()
template<int dim, int spacedim> template<typename StreamType > void Tools::GridInfo< dim, spacedim >::print_info (StreamType & out) inline
Definition at line 109 of file mesh_handler.cc.
References n_active_cells(), and Patterns::Tools::to_string().
Referenced by main().
Member Data Documentation
boundary_ids
template<int dim, int spacedim> std::vector<types::boundary_id> Tools::GridInfo< dim, spacedim >::boundary_ids
Definition at line 143 of file mesh_handler.cc.
info_level
template<int dim, int spacedim> unsigned int Tools::GridInfo< dim, spacedim >::info_level
Definition at line 134 of file mesh_handler.cc.
manifold_ids
template<int dim, int spacedim> std::vector<types::manifold_id> Tools::GridInfo< dim, spacedim >::manifold_ids
Definition at line 145 of file mesh_handler.cc.
material_ids
template<int dim, int spacedim> std::vector<types::material_id> Tools::GridInfo< dim, spacedim >::material_ids
Definition at line 144 of file mesh_handler.cc.
n_active_cells
template<int dim, int spacedim> unsigned int Tools::GridInfo< dim, spacedim >::n_active_cells
Definition at line 135 of file mesh_handler.cc.
n_active_cells_at_level
template<int dim, int spacedim> std::vector<unsigned int> Tools::GridInfo< dim, spacedim >::n_active_cells_at_level
Definition at line 140 of file mesh_handler.cc.
n_cells_at_level
template<int dim, int spacedim> std::vector<unsigned int> Tools::GridInfo< dim, spacedim >::n_cells_at_level
Definition at line 141 of file mesh_handler.cc.
n_levels
template<int dim, int spacedim> unsigned int Tools::GridInfo< dim, spacedim >::n_levels
Definition at line 138 of file mesh_handler.cc.
n_used_vertices
template<int dim, int spacedim> unsigned int Tools::GridInfo< dim, spacedim >::n_used_vertices
Definition at line 137 of file mesh_handler.cc.
n_vertices
template<int dim, int spacedim> unsigned int Tools::GridInfo< dim, spacedim >::n_vertices
Definition at line 136 of file mesh_handler.cc.
reference_cell_types
template<int dim, int spacedim> std::vector<ReferenceCell> Tools::GridInfo< dim, spacedim >::reference_cell_types
Definition at line 146 of file mesh_handler.cc.
The documentation for this struct was generated from the following file:
apps/mesh_handler.cc