var searchData=
[
  ['l1norm_13067',['L1Norm',['http://www.dealii.org/developer/doxygen/deal.II/structLinearAlgebra_1_1CUDAWrappers_1_1kernel_1_1L1Norm.html',1,'LinearAlgebra::CUDAWrappers::kernel']]],
  ['ladealii_13068',['LAdealii',['../struct_l_a_c_1_1_l_adealii.html',1,'LAC']]],
  ['lagrangeequidistant_13069',['LagrangeEquidistant',['http://www.dealii.org/developer/doxygen/deal.II/classPolynomials_1_1LagrangeEquidistant.html',1,'Polynomials']]],
  ['lambdaoptimizer_13070',['LambdaOptimizer',['http://www.dealii.org/developer/doxygen/deal.II/structDifferentiation_1_1SD_1_1internal_1_1LambdaOptimizer.html',1,'Differentiation::SD::internal']]],
  ['lapackfullmatrix_13071',['LAPACKFullMatrix',['http://www.dealii.org/developer/doxygen/deal.II/classLAPACKFullMatrix.html',1,'']]],
  ['lapackfullmatrix_3c_20double_20_3e_13072',['LAPACKFullMatrix&lt; double &gt;',['http://www.dealii.org/developer/doxygen/deal.II/classLAPACKFullMatrix.html',1,'']]],
  ['lapackfullmatrix_3c_20number_20_3e_13073',['LAPACKFullMatrix&lt; Number &gt;',['http://www.dealii.org/developer/doxygen/deal.II/classLAPACKFullMatrix.html',1,'']]],
  ['lapackfullmatrix_3c_20number_20_3e_13074',['LAPACKFullMatrix&lt; number &gt;',['http://www.dealii.org/developer/doxygen/deal.II/classLAPACKFullMatrix.html',1,'']]],
  ['lapetsc_13075',['LAPETSc',['../struct_l_a_c_1_1_l_a_p_e_t_sc.html',1,'LAC']]],
  ['laplaceoperator_13076',['LaplaceOperator',['http://www.dealii.org/developer/doxygen/deal.II/classMatrixFreeOperators_1_1LaplaceOperator.html',1,'MatrixFreeOperators']]],
  ['latrilinos_13077',['LATrilinos',['../struct_l_a_c_1_1_l_a_trilinos.html',1,'LAC']]],
  ['lazy_13078',['Lazy',['http://www.dealii.org/developer/doxygen/deal.II/classLazy.html',1,'']]],
  ['lazy_3c_20fevaluesviews_3a_3ascalar_3c_20dim_2c_20spacedim_20_3e_20_3e_13079',['Lazy&lt; FEValuesViews::Scalar&lt; dim, spacedim &gt; &gt;',['http://www.dealii.org/developer/doxygen/deal.II/classLazy.html',1,'']]],
  ['lazy_3c_20fevaluesviews_3a_3asymmetrictensor_3c_202_2c_20dim_2c_20spacedim_20_3e_20_3e_13080',['Lazy&lt; FEValuesViews::SymmetricTensor&lt; 2, dim, spacedim &gt; &gt;',['http://www.dealii.org/developer/doxygen/deal.II/classLazy.html',1,'']]],
  ['lazy_3c_20fevaluesviews_3a_3atensor_3c_202_2c_20dim_2c_20spacedim_20_3e_20_3e_13081',['Lazy&lt; FEValuesViews::Tensor&lt; 2, dim, spacedim &gt; &gt;',['http://www.dealii.org/developer/doxygen/deal.II/classLazy.html',1,'']]],
  ['lazy_3c_20fevaluesviews_3a_3avector_3c_20dim_2c_20spacedim_20_3e_20_3e_13082',['Lazy&lt; FEValuesViews::Vector&lt; dim, spacedim &gt; &gt;',['http://www.dealii.org/developer/doxygen/deal.II/classLazy.html',1,'']]],
  ['lazy_3c_20std_3a_3aunique_5fptr_3c_20fe_5fq_3c_20dim_20_3e_20_3e_20_3e_13083',['Lazy&lt; std::unique_ptr&lt; FE_Q&lt; dim &gt; &gt; &gt;',['http://www.dealii.org/developer/doxygen/deal.II/classLazy.html',1,'']]],
  ['legendre_13084',['Legendre',['http://www.dealii.org/developer/doxygen/deal.II/classFESeries_1_1Legendre.html',1,'FESeries::Legendre&lt; int dim, int spacedim &gt;'],['http://www.dealii.org/developer/doxygen/deal.II/classPolynomials_1_1Legendre.html',1,'Polynomials::Legendre']]],
  ['levelequalto_13085',['LevelEqualTo',['http://www.dealii.org/developer/doxygen/deal.II/classIteratorFilters_1_1LevelEqualTo.html',1,'IteratorFilters']]],
  ['levelsetdescription_13086',['LevelSetDescription',['http://www.dealii.org/developer/doxygen/deal.II/classNonMatching_1_1internal_1_1MeshClassifierImplementation_1_1LevelSetDescription.html',1,'NonMatching::internal::MeshClassifierImplementation']]],
  ['line_13087',['Line',['http://www.dealii.org/developer/doxygen/deal.II/structDynamicSparsityPattern_1_1Line.html',1,'DynamicSparsityPattern']]],
  ['linearelasticity_13088',['LinearElasticity',['../class_p_d_es_1_1_linear_elasticity.html',1,'PDEs']]],
  ['linearindexiterator_13089',['LinearIndexIterator',['http://www.dealii.org/developer/doxygen/deal.II/classLinearIndexIterator.html',1,'']]],
  ['linearindexiterator_3c_20iterator_2c_20accessor_20_3e_13090',['LinearIndexIterator&lt; Iterator, Accessor &gt;',['http://www.dealii.org/developer/doxygen/deal.II/classLinearIndexIterator.html',1,'']]],
  ['linearindexiterator_3c_20iterator_3c_20tabletype_2c_20constness_2c_20storage_5forder_20_3e_2c_20accessor_3c_20tabletype_2c_20constness_2c_20storage_5forder_20_3e_20_3e_13091',['LinearIndexIterator&lt; Iterator&lt; TableType, Constness, storage_order &gt;, Accessor&lt; TableType, Constness, storage_order &gt; &gt;',['http://www.dealii.org/developer/doxygen/deal.II/classLinearIndexIterator.html',1,'']]],
  ['linearoperator_13092',['LinearOperator',['http://www.dealii.org/developer/doxygen/deal.II/classLinearOperator.html',1,'']]],
  ['linearoperator_3c_20range_2c_20domain_2c_20blockpayload_3a_3ablocktype_20_3e_13093',['LinearOperator&lt; Range, Domain, BlockPayload::BlockType &gt;',['http://www.dealii.org/developer/doxygen/deal.II/classLinearOperator.html',1,'']]],
  ['linearproblem_13094',['LinearProblem',['../class_p_d_es_1_1_linear_problem.html',1,'PDEs']]],
  ['linearproblem_3c_20dim_2c_20dim_2c_20lac_3a_3aladealii_20_3e_13095',['LinearProblem&lt; dim, dim, LAC::LAdealii &gt;',['../class_p_d_es_1_1_linear_problem.html',1,'PDEs']]],
  ['linearproblem_3c_20dim_2c_20dim_2c_20lac_3a_3alatrilinos_20_3e_13096',['LinearProblem&lt; dim, dim, LAC::LATrilinos &gt;',['../class_p_d_es_1_1_linear_problem.html',1,'PDEs']]],
  ['linearproblem_3c_20dim_2c_20dim_2c_20lactype_20_3e_13097',['LinearProblem&lt; dim, dim, LacType &gt;',['../class_p_d_es_1_1_linear_problem.html',1,'PDEs']]],
  ['linearsolvercontent_13098',['LinearSolverContent',['http://www.dealii.org/developer/doxygen/deal.II/structSUNDIALS_1_1internal_1_1LinearSolverContent.html',1,'SUNDIALS::internal']]],
  ['linearsolverwrapper_13099',['LinearSolverWrapper',['http://www.dealii.org/developer/doxygen/deal.II/classSUNDIALS_1_1internal_1_1LinearSolverWrapper.html',1,'SUNDIALS::internal']]],
  ['linearviscoelasticity_13100',['LinearViscoElasticity',['../class_p_d_es_1_1_linear_visco_elasticity.html',1,'PDEs']]],
  ['linfty_13101',['LInfty',['http://www.dealii.org/developer/doxygen/deal.II/structLinearAlgebra_1_1CUDAWrappers_1_1kernel_1_1LInfty.html',1,'LinearAlgebra::CUDAWrappers::kernel']]],
  ['list_13102',['List',['http://www.dealii.org/developer/doxygen/deal.II/classPatterns_1_1List.html',1,'Patterns']]],
  ['lobatto_13103',['Lobatto',['http://www.dealii.org/developer/doxygen/deal.II/classPolynomials_1_1Lobatto.html',1,'Polynomials']]],
  ['localintegrator_13104',['LocalIntegrator',['http://www.dealii.org/developer/doxygen/deal.II/classMeshWorker_1_1LocalIntegrator.html',1,'MeshWorker']]],
  ['locallyownedcell_13105',['LocallyOwnedCell',['http://www.dealii.org/developer/doxygen/deal.II/classIteratorFilters_1_1LocallyOwnedCell.html',1,'IteratorFilters']]],
  ['locallyownedlevelcell_13106',['LocallyOwnedLevelCell',['http://www.dealii.org/developer/doxygen/deal.II/classIteratorFilters_1_1LocallyOwnedLevelCell.html',1,'IteratorFilters']]],
  ['localresults_13107',['LocalResults',['http://www.dealii.org/developer/doxygen/deal.II/classMeshWorker_1_1LocalResults.html',1,'MeshWorker']]],
  ['logstream_13108',['LogStream',['http://www.dealii.org/developer/doxygen/deal.II/classLogStream.html',1,'']]],
  ['loopcontrol_13109',['LoopControl',['http://www.dealii.org/developer/doxygen/deal.II/classMeshWorker_1_1LoopControl.html',1,'MeshWorker']]],
  ['lowstoragerungekutta_13110',['LowStorageRungeKutta',['http://www.dealii.org/developer/doxygen/deal.II/classTimeStepping_1_1LowStorageRungeKutta.html',1,'TimeStepping']]],
  ['lsingularityfunction_13111',['LSingularityFunction',['http://www.dealii.org/developer/doxygen/deal.II/classFunctions_1_1LSingularityFunction.html',1,'Functions']]],
  ['lsingularitygradfunction_13112',['LSingularityGradFunction',['http://www.dealii.org/developer/doxygen/deal.II/classFunctions_1_1LSingularityGradFunction.html',1,'Functions']]]
];
