name: github-docker

on: 
  push: 
    branches: [main, 'docker*']

jobs:
  build-master-docker:
    runs-on: ubuntu-latest
    steps:          
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image of master 
        uses: docker/build-push-action@v6
        with:
          context: ./docker/
          file: ./docker/Dockerfile.fsi-suite
          cache-from: type=registry,ref=heltai/dealii:vscode
          cache-to: type=inline
          platforms: linux/arm64,linux/amd64
          push: true
          tags: |
            heltai/fsi-suite:latest
            ghr.io/${{ github.repository }}:latest

